### ISSUE TITLE
Broken PDF when using Canvas file picker - fine otherwise

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#1003]
[Carey - 1993 - THE PURPOSE OF ARISTOPHANES' ACHARNIANS.pdf](https://github.com/hypothesis/lms/files/3671655/Carey.-.1993.-.THE.PURPOSE.OF.ARISTOPHANES.ACHARNIANS.pdf)

The attached PDF works with the Chrome extension, the Bookmarklet in Firefox, and when using the Google picker in Canvas. It fails when using the Canvas file picker.
![image](https://user-images.githubusercontent.com/22603275/65886933-36afaf80-e36b-11e9-8a09-64bd5ca0f1ef.png)

When re-printing the PDF using Mac Preview, the errors remain the same in Canvas. When printing the PDF in Chrome after activating the extension, and when using ocr.space to OCR again, the errors change to:
![image](https://user-images.githubusercontent.com/22603275/65887078-6fe81f80-e36b-11e9-8047-1bda90c01511.png)

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/6238

**Comment by mkdir-washington-edu** [comment]
Note: the file name was "Carey - 1993 - THE PURPOSE OF ARISTOPHANES' ACHARNIANS.pdf" and removing the single apostrophe fixed the issue. This seems to be a Canvas issue and not Hypothesis'.

**Comment by dwhly** [comment]
This seems like likely a common enough character that even if it's a bug in other code we might want to warn users against.

**Comment by klemay** [comment]
Note: we need to first diagnose whether this is a Canvas bug or a Hypothesis bug - need to diagnose first, then determine approach to solving

**Comment by klemay** [comment]
closing in favor of: https://github.com/hypothesis/lms/issues/1003
