### ISSUE TITLE
Do LTI launch params include the necessary info for enabling Canvas sections integration?

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#1004]
Part of https://github.com/hypothesis/lms/issues/419. 

As Sean points out in [a comment on 419](https://github.com/hypothesis/lms/issues/419#issuecomment-506387789), it will be much easier to implement 419 if there is information in a standard LTI launch about Sections. This is a spike to determine whether LTI launches contain the info we need, or if we need to pursue a more complex integration.

As a reminder, here's what we mean by Sections: 

> "Section" is used when an instructor teaches, for example, Chem 101 on Monday-Wednesday and Tuesday-Thursday. The M-W students would be in "Section 1" and the T-R students would be in "Section 2." LMSes allow that instructor to have both Sections in the same course site so they don't have to upload materials in 2 places. These Sections are tied to the roster, so students are automatically sorted.

**Comment by seanh** [comment]
I've re-titled this and re-scoped it to be Canvas-specific. We'll deal with the equivalent features in other LMS's later

**Comment by seanh** [comment]
Closing in favour of https://github.com/hypothesis/lms/issues/1338
