### ISSUE TITLE
Don’t show grading interface to instructors if assignment is not gradable

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#1034]
In Blackboard (and in most other LMSes) instructors have the option of creating readings that are for evaluation ("gradable") or readings that are not meant to be graded. In Blackboard, the option looks like this:

<img width="609" alt="Screen Shot 2019-10-09 at 12 26 52 PM" src="https://user-images.githubusercontent.com/12087705/66500789-2648b480-ea90-11e9-9ceb-405693461500.png">

Currently, our grading view shows for instructors when they launch assignments, even if they select "No" for the "Enable Evaluation" option. Here's what the grading interface looks like for a reading that is not gradable:

![image (2)](https://user-images.githubusercontent.com/12087705/66500918-690a8c80-ea90-11e9-9477-459d6bd34241.png)

Note that even though students have annotated, we see "0 students". The dropdown that says "All Students" does not populate with students who have annotated. 

A better experience would be to just not show the grading interface for readings that aren't gradable.

**Comment by robertknight** [comment]
In Blackboard it appears that we can test whether evaluation is enabled for an assignment when an instructor launches it by checking for a specific LTI launch parameter (`lis_outcome_service_url`). This launch parameter is not actually useful for instructors though so it is possible that other LMSes do not set it.

This means that in other LMSes we may need to find an entirely different approach to determining whether grading is enabled. It may not be possible to determine this at all using standard LTI APIs, in which case we might have to fall back to some other option, such as hiding the grading UI if no grades have yet been submitted for a particular assignment.

One other issue I encountered in testing this with our Blackboard instance is that once evaluation had been enabled for an assignment, disabling it did not seem to work.
