### ISSUE TITLE
Store course descriptions for LMS groups for metrics

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#1094]
## User story
As a Hypothesis team member, I want to be able to segment Humanities vs STEM usage in our LMS app. Currently the only information we have about course groups is a truncated version of the course title. Course descriptions would give us better information about what kinds of courses are using Hypothesis.

Might be worth doing a spike to see if course descriptions come as part of a standard LTI launch, or if we'd need to allow for manual entry of course descriptions (like we do for non-LMS groups).

**Comment by marcospri** [comment]
We already do this for LMSes that provide it via LTI
