### ISSUE TITLE
Instructors unable to annotate the first time a Hypothesis assignment is launched in Blackboard and Moodle

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#1128]
## Overview
The very first time an instructor creates a Hypothesis assignment in a Blackboard course site, they are unable to annotate until they refresh the page or close and re-open the assignment. It’s unclear whether this is specific to our Blackboard instance (does it happen for other Bb institutions?), or whether it’s specific to our app (does the same problem appear for other LTI apps?). 

Note that we are able to reproduce this with and without the grading feature flag, so this is likely not related to the grading portion of our app. 

## Steps to reproduce
1. In our Blackboard instance, [create a new course site](https://help.blackboard.com/Learn/Administrator/Hosting/Course_Management/Creating_Courses) and [enroll yourself as an instructor](https://help.blackboard.com/Learn/Administrator/Hosting/Course_Management/Managing_Enrollments)
2. [Create a Hypothesis-enabled assignment](https://web.hypothes.is/help/creating-hypothesis-enabled-readings-in-blackboard/) (with or without evaluation enabled)
Once you have successfully selected an HTML page or PDF, the assignment will launch

## Expected behavior
The selected document loads with the Hypothesis sidebar on top of it. A group has been created for the course, and as a teacher I can annotate the document. 

## Actual behavior
The group name does not appear as expected. Instead we see “...” in place of the group name. Selecting text and clicking “Annotate” creates a card in the sidebar with no place to type an annotation:

![pasted image 0](https://user-images.githubusercontent.com/12087705/68335190-006ff900-00aa-11ea-9021-634fa7bda8ed.png)

Reloading the browser tab or closing and re-opening the assignment will fix this. Furthermore, you will never run into this problem again in this course site— it seems to only happen with the very first assignment / with group creation.

## Additional details
We have reproduced this with all of the following conditions:
- With and without the grading feature flag enabled
- With a course created through the Course Wizard and through a course created manually
- With HTML pages and with Google Drive PDFs
- With the Hypothesis assignment being the first assignment in a course, and with a non-Hypothesis assignment being the first assignment created in the course.

Again, it’s unclear whether this is unique to our Blackboard instance (as it’s not connected to an SIS system and not a true representation of a working Bb environment like what you’d see at a school). 

In the meantime, we are updating our docs at https://web.hypothes.is/help/creating-hypothesis-enabled-readings-in-blackboard/ to suggest that teachers refresh the page or relaunch the assignment as the final step of assignment creation.

**Comment by klemay** [comment]
Sean just discovered that this happens in Moodle too.

**Comment by seanh** [comment]
Note that the grading UI also fails to appear on first launch. May be the same issue or a separate issue

**Comment by jon-betts** [comment]
I've started a PR about this, but it's only trying to fix the grading issue so far to see if that gets us both. I can't currently login to Blackboard. Looks like our Blackboard instance has been bust in some way.

**Comment by jon-betts** [comment]
There's a fix for the first launch grading issue, I'll re-test to see if it actually fixes the reported issue.

**Comment by jon-betts** [comment]
Looking at my fix in Moodle, some of this seems to be fixed and some doesn't. 

 * The course is now visible
 * You can now highlight text and click annotate
 * Highlights appear in the page and in the numbered trackers on the side bar
 * No editor appears in the side-bar

I wonder if this is a default visibility setting or something similar. @klemay Can we start the process of creating annotations in a way where we can't see them? They are being added to a group we aren't viewing or something similar?

**Comment by klemay** [comment]
@jon-betts this is kind of a stab in the dark, but does this seem like it could be related? https://github.com/hypothesis/client/issues/1542

**Comment by mkdir-washington-edu** [comment]
Note that a user and I fixed this today in Moodle by turning off the grading bar: https://hypothesis.zendesk.com/agent/tickets/7393

**Comment by nadavkav** [comment]
I have the same issue :-( with Moodle.
And @mkdir-washington-edu comment helped me, workaround it. (thanks)

**Comment by jon-betts** [comment]
So this should be fixed now and we are deploying. The fix for being able to view your annotations is a separate issue to do with filtering.
