### ISSUE TITLE
"Hypothesis login lost" error when grading

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1136]
1. As a teacher, open up the Blackboard grading UI (i.e. open an assignment that has grading/evaluation labelled)
2. Wait several minutes (exact time unknown)
3. Continue trying to grade, e.g. try to submit a grade, or change to another student
4. You will see a "Hypothesis login lost" error message and will have to reload the entire browser tab to fix it

Relates to 
https://github.com/hypothesis/lms/issues/1199

![Screenshot from 2019-11-07 18-58-32](https://user-images.githubusercontent.com/22498/68421112-85840c80-0195-11ea-879c-ba3846cc28e7.png)

**Comment by LMS007** [comment]
This fix will be to move to post message and not kill off the iframe over and over.
