### ISSUE TITLE
SpeedGrader focus config should use userid, not username

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1199]
Relates to https://github.com/hypothesis/client/issues/1516

We should convert the the focus mode key `username` to `userid`. It seems we are already using  the actual userid and we just need to use the correct name for it. Once this is done, we should update the client docs to reflect that change.

https://h.readthedocs.io/projects/client/en/latest/publishers/config/#cmdoption-arg-focus

**Comment by LMS007** [comment]
@seanh I have a bit of confusion with this ticket. 

Upon some inspection, it appears that the value we pass to  `focused_user` in the lti_launches param
e.g.
lti_launches?focused_user=

.. is the the h_username value. That to me, seems like its a username, not a userid.  I'm trying to match the param names we have on the client to the ones from the lms. In the lms client grader UI e.g. (moodle, blackboard, etc) we pass a value that looks like this "acct:525d674dcde8cf25a32713290db13b@lms.hypothes.is" around via rpc to set the focused mode.
I am under the assumption this was is userid.

in canvas (we use the url to change focus, not rpc) I see this value that looks like this assigned to focused_user=acea453480dde254bdf1c1058758e2

Is that a username?

**Comment by seanh** [comment]
It looks looks like in SpeedGrader the `js-hypothesis-config["focus"]["user"]["username"]` setting is a username not a userid, yes.

In non-Canvas there instead `js-hypothesis-config["focus"]["user"]["username"]` we use `js-lms-config["students"][i]["userid"]` which is a userid not a username.

So it looks to me like we use a username in Canvas but a userid in non-Canvas LMS's.

We can't do anything about the fact that Canvas passes usernames, not userids, back to the LMS app as the `focused_user` in the launch params. We can change the LMS app to pass Canvas a userid to pass back to us in future. But existing submissions in Canvas instances in the wild will still be passing us a username.

So if you want to remove support for focusing a user by username from the client, we'd have to add code to the LMS app to convert `focused_user` usernames into userids before passing them to the client.

**Comment by LMS007** [comment]
Understood. I think the best approach right now is to close this out and just update the docs on the client end to inform users that either the username or userid work for the focus config.
