### ISSUE TITLE
Annotation on mobile devices - iOS and Andorid - User Experience

### ISSUE THREAD

**Issue by KalanaPerera** [hypothesis/lms#1227]
Does anyone noticed Annotation experience difficult in android and ios devices? 

Is there any way to improve?

Looking forward to discuss and I would like to support is there anything I can help with you guys.

Thank you.

**Comment by KalanaPerera** [comment]
Could you please check this?  @jon-betts

**Comment by robertknight** [comment]
Hi @KalanaPerera what issues specifically are you referring to? For iPad / iPhone specifically there is https://github.com/hypothesis/client/issues/5023, which I'm guessing is the most likely issue. I'm closing this as a duplicate on that assumption.
