### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow' (Moodle)

### ISSUE THREAD

**Issue by nadavkav** [hypothesis/lms#1258]
When I open up a new PDF document in Moodle, I am unable to add comments, with the following error in the JS console (Chrome Version 78.0.3904.108 (Official Build) (64-bit))

postmessage-json-rpc.js:49 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://lms.hypothes.is') does not match the recipient window's origin ('https://via.hypothes.is').
call @ postmessage-json-rpc.js:49
(anonymous) @ fetch-config.js:34
fetchConfig @ fetch-config.js:68
139.../shared/bridge @ index.js:271
i @ _prelude.js:35
e @ _prelude.js:42
(anonymous) @ _prelude.js:10

**Comment by nadavkav** [comment]
Seems related to #1128

**Comment by robertknight** [comment]
This particular "error" is actually normal given the way the LMS app currently works and the way that the Hypothesis communicates with our lms app. Can you provide more details on what exactly is not working when you try to add comments? Can you also provide details of any other errors you see?

**Comment by nadavkav** [comment]
@robertknight , you are right. All seems to work fine, although the error persists.
What was actually enable us to write comments, was disabling the "grades" feature in LTI settings page. as suggested in the comments of #1128 .

**Comment by nadavkav** [comment]
Suddenly, all the PDF document is gone, and I got error: 404 Not Found 
https://via.hypothes.is/static/pdfjs-2/web/
