### ISSUE TITLE
Client's annotations shouldn'be filtered when "All Students" is selected

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1259]
Note: there are actually two separate issues described below:

1. Annotating or replying when a search or filter is active in the client is broken because the in-progress annotation or reply gets filtered out (from the user's point of view: when you click <kbd>Annotate</kbd> or <kbd>Reply</kbd> nothing happens, it's broken). This is a general client issue, not LMS-specific, but it manifests in grading. Client issue for this: https://github.com/hypothesis/client/issues/1244

2. An LMS-specific issue (but not sure whether it's a client bug or an LMS bug): when <kbd>All Students</kbd> is selected in the grading UI a filter is being erroneously applied to the annotations in the client.

**This issue is for 2**, not 1. But below I describe the issues with the LMS grading experience from the teacher's point of view which combines both 2 and 1:

In grading mode, when <kbd>All Students</kbd> is selected, a filter is being applied to the annotation's in the client's sidebar. Broken text labels are displayed in the sidebar and the teacher cannot create annotations or replies.

1. If a teacher launches a gradeable assignment **that does not have any annotations from any students** then when <kbd>All Students</kbd> is selected **"No annotations for"** (with nothing after the "for") is shown in the client

   ![Screenshot from 2019-12-11 12-56-53](https://user-images.githubusercontent.com/22498/70623306-bb456680-1c15-11ea-93bf-96751eb9a5b0.png)

2.  If a teacher launches a gradeable assignment **that does have at least one annotation from at least one student** then when <kbd>All Students</kbd> is selected **Showing 1 annotation** appears in the sidebar, indicating that a filter is active, when in fact no filter is applicable here.

   ![Screenshot from 2019-12-11 12-47-43](https://user-images.githubusercontent.com/22498/70622985-f4310b80-1c14-11ea-8770-de858b00fc78.png)

3. In either case if the teacher who is grading the assignment tries to create an annotation or reply while <kbd>All Students</kbd> is selected, that annotation is not visible in the client. It seems to get filtered out.

   This is caused by a combination of a filter being applied in the client when it shouldn't be, plus this client bug: https://github.com/hypothesis/client/issues/1244

   Due to the preexisting client bug this also happens when a particular student (rather than <kbd>All Students</kbd>) is selected in the grading UI's top bar _and_ <kbd>Showing **STUDENT_NAME** only</kbd> is active in the sidebar: the teacher's own in-progress annotations and replies are filtered out, which means that they can't create annotations or replies. But if <kbd>Showing **all**</kbd> is active then the teacher's own annotations and replies do appear.

**Comment by lyzadanger** [comment]
Early investigation suggests that the state of the config object provided to the client by the RPC `postMessage` communication is putting the client in a sort of undefined state, in which a focus mode is applied, but there is no user information.

See https://github.com/hypothesis/client/blob/5be865365bad02db3b9f2d3f612ddbbae5519dac/src/sidebar/services/root-thread.js#L51-L63

Focus mode is indeed "focused" in these cases, but `store.focusModeUserId()` returns `null`

**Comment by seanh** [comment]
We could change the LMS app to _not_ send a `changeFocusModeUser()` call (with `username: null`) over postMessage to the client on startup. I'm guessing that would fix the issue on startup: no filter would be applied.

But what when the teacher changes to a student and then changes back to _All Students_? It seems like the LMS app needs a way to say to the client "disable focus mode", but I don't see one.

**Comment by lyzadanger** [comment]
> But what when the teacher changes to a student and then changes back to All Students? It seems like the LMS app needs a way to say to the client "disable focus mode", but I don't see one.

Yes, I think the key here is to define state and modes more clearly.

**Comment by seanh** [comment]
I think this fixes it:

```diff
diff --git a/src/sidebar/store/modules/selection.js b/src/sidebar/store/modules/selection.js
index 550e355d..c56a9b9b 100644
--- a/src/sidebar/store/modules/selection.js
+++ b/src/sidebar/store/modules/selection.js
@@ -169,16 +169,26 @@ const update = {
   },
 
   CHANGE_FOCUS_MODE_USER: function(state, action) {
-    return {
-      focusMode: {
-        ...state.focusMode,
-        enabled: true,
-        focused: true,
-        config: {
-          user: { ...action.user },
+    if (action.user.username === undefined) {
+      return {
+        focusMode: {
+          ...state.focusMode,
+          enabled: false,
+          focused: false,
         },
-      },
-    };
+      };
+    } else {
+      return {
+        focusMode: {
+          ...state.focusMode,
+          enabled: true,
+          focused: true,
+          config: {
+            user: { ...action.user },
+          },
+        },
+      };
+    }
   },
 
   SET_FORCE_VISIBLE: function(state, action) {
```

**Comment by seanh** [comment]
Some notes on the fix above:

* The client needs to not be filtering when the assignment first loads and <kbd>All Students</kbd> is selected. But it also needs to have a way to go _back_ from filtering to a student to <kbd>All Students</kbd> and no filter. There needs to be a way to clear the filter

* When you select <kbd>All Students</kbd> in the grading dropdown the LMS app is sending this to the client over JSON-RPC. Note the `username: undefined`

  ```json
  {
    jsonrpc: "2.0",
    method: "changeFocusModeUser",
    params: [
      {
        username: undefined,
        displayName: undefined
      }
    ]
  }
  ```

* [The only method the client makes available to the LMS app to call is `changeFocusModeUser()`](https://github.com/hypothesis/client/blob/5be865365bad02db3b9f2d3f612ddbbae5519dac/src/sidebar/cross-origin-rpc.js#L11-L15). For example there's no separate "clearFocusMode()" method

* When <kbd>All Students</kbd> is selected [the LMS app calls `changeFocusedUser({})`](https://github.com/hypothesis/lms/blob/d6b88fd7e375a4b23899117556b3e39cfe18986b/lms/static/scripts/frontend_apps/components/LMSGrader.js#L46) with a code comment that says that it expects the client to clear the focus if given a "non-real" userid to focus (`undefined`, in this case)

* The client does not, in fact, clear the focus when given `username: undefined`. That's what the diff above fixes

**Comment by lyzadanger** [comment]
The hacky fix seems appropriate to me for now while we track down fixing this the right way.
