### ISSUE TITLE
Phase 1: Allow maximum and minimum grading values to be controlled from the back-end

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#1267]
Partially to enable future work, but partially on it's own merits we should:

 * Move scaling of grades for the LTI calls to the back-end
 * Change front-end presentation to allow arbitrary values rather than assuming 0 - 10
 * We should then allow the value returned to be produced by a `ToolConsumer` service in the back-end
 * This `ToolConsumer` can have a different implementation for every LMS that deviates from the default
 * We should use this to return a default between 0 - 100 for Moodle to match the defaults when creating an assignment

Non-functionals:

 * We are going to swap the grade entering component for a different type soon. This should be extracted from the form it occupies rather than just modified in place
 * It is a goal of this phase to: "begin the process of a plugable grading model in the front-end"
 * All other (non-Moodle) LMS behaviors should be as they were before

**Comment by robertknight** [comment]
The backend now has the ability to specify the maximum numeric value for grades, as part of LTI 1.3 grading support. @marcospri does this cover the "Point" grading method in Moodle specifically per https://github.com/hypothesis/lms/issues/1266, or is there additional work needed for that?

Picking from a discrete list of options for a grade is not yet implemented.

I am inclined to close this issue which is focused on a particular set of internal changes and just keeps https://github.com/hypothesis/lms/issues/1266 which describes the user-facing issue to be solved.

**Comment by marcospri** [comment]
The work done for supporting any scale of numeric grading works in Moodle. Closing this.
