### ISSUE TITLE
Ongoing Refactoring

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#1280]
This is a placeholder for ideas about refactoring to serve a few purposes:

 * To allow us to record refactoring ideas
 * To allow us to note them down so discussion can move on when we think of ideas

----

# Rough notes

## Views

api/lti
  * Separate canvas behavior
  * Name speedgrader end-point something canvas specific

basic_lti_launch
  * Separate configured (and configuring) from un-configured

## Services

LTIOutcomes
 * Rename `GradingAPIClient`

GradingInfo
  * Use an Assignment object instead of context_id + resource_link_id

New service for front-end config
 * Pull in the various different places that all do this sort of thing
   * Context object
   * Various views
   * Helpers scattered about

## The context

Context
  - Split out User
  - Split out Group
  - Split out config to separate services?

## Value/domain objects

ApplicationInstance
  * Holds the oauth_consumer_key
 * User indirection

Assignment
HUSer
  - domain?
  - factories and computed values

**Comment by robertknight** [comment]
I'm closing this since it is a very broad issue that doesn't have a clear endpoint.
