### ISSUE TITLE
Make LMS API accept `0` as a valid grade

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1345]
Should the LMS service handle a grade of zero? 

If not, we should then change the UI client validation to reject a value of less than or equal to 0. Currently it only rejects if it less than 0.

![Screen Shot 2020-01-15 at 12 44 52 PM](https://user-images.githubusercontent.com/3939074/72469717-da935e80-3794-11ea-93a5-b8c1c8c0af2c.png)

**Comment by lyzadanger** [comment]
`0` seems like a valid grade an instructor might want to assign, to me.

**Comment by seanh** [comment]
Which LMS was this tested in? It could be that some or all LMS's don't accept 0 as a grade

**Comment by jon-betts** [comment]
I've definitely seen Moodle accept 0. In fact we have a different potential bug as we interpret None and 0 both as 0. So if you load a student with no grade at all, the UI displays 0. So if you press save, then the grade is actually stored as 0 (the teacher might reasonably expect they weren't altering the score?).

This isn't quite right, and can make a difference in Moodle, as certain assignment editing functions are disabled once the first students grade is in.

**Comment by lyzadanger** [comment]
> Which LMS was this tested in? It could be that some or all LMS's don't accept 0 as a grade

Our Blackboard instance, using a local install for `lms`

> What's the response body from our proxy API, when this happens?

I don't have that at my fingertips, but I can tell you that it is a (appropriately-handled, with UI error) 400 response.

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/7909

**Comment by LMS007** [comment]
In regards to Jons comment https://github.com/hypothesis/lms/issues/1345#issuecomment-575149186

Looking at the client code we handle the null case and have a test for it. If the service returns a null grade, then the grader will not render anything in the input field. In which case, it won't be possible to submit a grade either as validation will not pass. It's possible in the past that this was different, but as of now, it won't be an issue.

If we don't know an LMS can handle a grade of 0, then perhap the client shall not make any assumptions. Currently you can submit a grade of 0. In the case where this is invalid (such as in moodle) a 400 error will be thrown and that error will appear in the client as a modal dialog. 

![Screen Shot 2020-10-13 at 3 06 30 PM](https://user-images.githubusercontent.com/3939074/95921195-b4234380-0d65-11eb-815c-3c1b36560f0e.png)

I can definitely see a desire for teachers to want to submit 0 as a grade because some students may not have done the assignment. And it's also important to distingue between 0 and null (e.g. students that have been graded vs ones that have not) 

But this appears to be an issue with the underlying LMS (moodle, blackboard, etc). Looking at the py code, it does indeed look like 0 is a valid acceptable score from our end.

Closing out this ticket because we can't assume a validation on the client and I don't think there is anything else to do in our service API.

**Comment by LMS007** [comment]
Going to re-open this until we know for sure that some lms's can indeed set 0.
