### ISSUE TITLE
Use h's group upsert API instead of update and create

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1383]
We already have [a group upsert API in h](https://h.readthedocs.io/en/latest/api-reference/v2/#tag/groups/paths/~1groups~1{id}/put) but [the lms app doesn't use it](https://github.com/hypothesis/lms/blob/7e1b85ff0c15690673e3dd471f5cf890b465a5da/lms/services/lti_h.py#L107-L123). The LMS app is going to need to use a new h bulk group upsert API to create its groups in future. As preparation for changing it to use bulk upsert, first change LMS to use single upsert.

**Comment by jon-betts** [comment]
This has been moved to https://github.com/hypothesis/h/milestone/18

It's taken over by the bulk api.
