### ISSUE TITLE
h: Add memberships support to group upsert API

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1384]
This actually needs to be done in [h](https://github.com/hypothesis/h) not lms but I'm creating the issue here in lms so that it can go into the same milestone as the other sections issues.

Add support to [h's group upsert API](https://h.readthedocs.io/en/latest/api-reference/v2/#tag/groups/paths/~1groups~1{id}/put) for also providing a list of users who should be added to the group as members, if they aren't already.

The LMS app currently [makes a separate API call to add the user to the group](https://github.com/hypothesis/lms/blob/7e1b85ff0c15690673e3dd471f5cf890b465a5da/lms/services/h_api.py#L125-L133) but in the future LMS is going to be creating a large number of groups in a single LTI launch request and can't afford to send a separate group members request to add the user to each group.

We're going to need a group bulk upsert API that creates many groups at once and adds users to all of them.

As a first step towards that, add memberships support to h's existing single-group upsert API.

**Comment by jon-betts** [comment]
This has been moved to https://github.com/hypothesis/h/milestone/18

Group membership will be a new top level call.
