### ISSUE TITLE
h: Add a bulk group upsert API with memberships support

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1385]
This actually needs to be done in [h](https://github.com/hypothesis/h) not lms but I'm creating the issue here in lms so that it can go into the same milestone as the other sections issues.

We already have a [group upsert API](https://h.readthedocs.io/en/latest/api-reference/v2/#tag/groups/paths/~1groups~1{id}/put) in h but we're going to need a bulk group upsert API.

The LMS app is sometimes going to need to create or update multiple groups in a single LTI launch. When a student is launching us it'll be one group for each course section the student belongs to. When a teacher is launching us, it'll be groups for _all_ the course's sections. We're [expecting courses with up to 20 sections](https://hypothes-is.slack.com/archives/CBN3DGW02/p1579195520094900) (and maybe more in future).

The LMS app can't make one group upsert for each one of the 20 groups it needs to upsert during a single launch, this would take too long. Based on a glance at New Relic [the LMS app's group update requests to h take about 60ms](https://rpm.newrelic.com/accounts/1385283/applications/76030703/externals?tw%5Bend%5D=1580324027&tw%5Bstart%5D=1579719227#id=5b2245787465726e616c5472616e73616374696f6e2f682d70726f642d6170692e7376632e6879706f746865732e69732f313338353238332332323638383633312f5765625472616e73616374696f6e2f46756e6374696f6e2f682e76696577732e6170692e67726f7570733a757064617465222c22225d). So 20 group updates would add about 1.2 seconds to an LMS response time, on top of other h API and Canvas API requests that it's already making.

**The bulk group upsert API also needs to support adding users to all the groups** that it creates at the same time, because we can't make 20+ requests to the memberships API to add the users to all the groups.

Some other things to consider:

* Should the API be public, and publicly documented? Or should it be "private" (only usable by people who have an auth client) and omitted from the public API docs?

* Should the API have some special rate limiting? Beyond any blanket rate limiting that might already be applied to all of h or to all of h's API

* Should there be a maximum request size? E.g. a maximum number of bulk actions per request?

**Comment by jon-betts** [comment]
This has been moved to https://github.com/hypothesis/h/milestone/18

It's taken over by the bulk api.
