### ISSUE TITLE
Use h's new bulk-group-upsert-with-memberships API instead of single-group-upsert and add-member

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1408]
Depends on:

- [ ] Adding a bulk group upsert API with memberships support to h: https://github.com/hypothesis/lms/issues/1385

Change LMS to use the new bulk group upsert API (even if it's only using it to upsert a list of one groups, for now)

**Comment by jon-betts** [comment]
All commands will now be a single call to the bulk api: https://github.com/hypothesis/h/milestone/18
