### ISSUE TITLE
Remove groups from RPC server 'requestConfig' method

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1556]
Depends on: https://github.com/hypothesis/client/issues/1908

Once the client no longer reads the groups from the config object returned by the LMS app's `'requestConfig'` method (see https://github.com/hypothesis/client/issues/1908) then we can remove the groups from that config object.

**Comment by LMS007** [comment]
@seanh This value now needs to be a specific value: `$rpc:requestGroups` in order for the client to know to query the groups via RPC from the LMS app.

e.g.
`hypothesisConfig: { services: [{ groups: "$rpc:requestGroups" }] }`

**Comment by seanh** [comment]
Gonna close this: we're actually still using the groups in the client's config when sections are not in use. When sections _are_ in use the `"$rpc:requestGroups"` thing has been implemented in both the client and LMS
