### ISSUE TITLE
Layout of assignment creation form is confusing

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#163]
Placing the <samp>Use Google Picker</samp> button immediately to the right of the <samp>Public Document URL</samp> field makes it look as if the <samp>Use Google Picker</samp> button does something with the <samp>Public Document URL</samp> value / as if I'm supposed to click <samp>Use Google Picker</samp> after pasting a URL into <samp>Public Document URL</samp>:
 
![screenshot from 2018-08-02 11-02-01](https://user-images.githubusercontent.com/22498/43597565-56a589d4-967a-11e8-8209-4bfc200f8f83.png)

In fact what you're supposed to do is click the further-away <samp>Submit</samp> button after pasting into <samp>Public Document URL</samp>, and _ignore_ the nearby <samp>Use Google Picker</samp> button.

I'm unable to test it currently because it's broken but I _think_<samp>Use Google Picker</samp> _does_ have something to do with <samp>Public Document URL</samp>: if you use the <samp>Use Google Picker</samp> and pick a document from Google then it pastes the URL of the selected document into <samp>Public Document URL</samp>. But this is unfortunate because we're actually labelling the secret Google Drive URL as <samp>Public Document URL</samp>.

The note <samp>sharing a file in this way creates a shared link for you course to access</samp> is also directly above the <samp>Public Document URL</samp> field but is completely irrelevant to that field: if you paste in a public URL we don't "create a link" at all, we use the one you pasted in. (I think it's questionable whether having this arguably misleading note on the Google Drive and Canvas Files options is a good idea either.)

What we're actually trying to present to the user here is two separate options:

1. Paste in a URL
2. Choose a document from Google
3. Choose a document from Canvas (if Canvas Files enabled)

The layout should make it clear that two (or three) distinct and separate options are available, rather than running the controls for the different options together and confusing things.

P.S. Don't use <samp>Submit</samp> as a label, something more specific like <samp>Create Assignment</samp> is better.

**Comment by seanh** [comment]
A detail to add to this: If you paste in the URL of a public web page or PDF file (e.g. `http://example.com/`) into the <samp>Public Document URL</samp> field and then hit <kbd>Enter</kbd> it activates the <samp>Use Google Picker</samp> button. Opens up the Google auth dialog, asks you to pick a document from Google Drive.

Tested with the Google Picker but not the Canvas Picker enabled. With the Canvas Picker enabled <kbd>Enter</kbd> may open the Canvas Picker instead.

**Comment by seanh** [comment]
Another note: "Google Picker" is the name of a Google product that we used to implement Google Drive support, a "file open" dialog for Google Drive: <https://developers.google.com/picker/>. Our users don't know or care what "Google Picker" is. That's an implementation detail. They care that they care that it lets them choose a file from their Google Drive, or upload a file from their computer to Google Drive and then choose it. So the button label in our UI should say something other than <samp>Use Google Picker</samp>.

**Comment by robertknight** [comment]
I agree. Something like "Choose from Google Drive" would make much more sense.

**Comment by robertknight** [comment]
This will be resolved by https://github.com/hypothesis/lms/issues/502 where we'll be implementing a new UI that has had UX input from Sean and Lyza.

**Comment by seanh** [comment]
This is fixed now that the `new_oauth` feature flag has been released
