### ISSUE TITLE
Assume that Canvas Files must be PDFs

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1632]
We know that a Canvas file must be a PDF and the backend code already knows when we're launching a Canvas file assignment (there's a [separate view for it](https://github.com/hypothesis/lms/blob/35e649bc12a7419e66fe309e7c81fd9f79bf9b0d/lms/views/basic_lti_launch.py#L70-L85)) so we can save network requests by just setting the Via 3 URL to Via 3's `/pdf/` endpoint directly.

**Comment by marcospri** [comment]
This optimization already takes place as part of h-vialib.
