### ISSUE TITLE
Surface teacher names for LMS groups

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#1701]
Previously our Education team was was using the creator of LMS groups to associate teacher names with LMS groups. In the course of recent Sections work, we've changed our group creator from "the first teacher to launch Hypothesis in an LMS course site" to a generic LMS user. 

We've discussed adding the names of group members with instructor roles to a table in the LMS database.

**Comment by judell** [comment]
From Slack:

> seanh
> @judell I'm wondering whether the group_info table is really being used to track courses, and just relying on the fact that it's one h group per course?
> With sections we'll be creating one h group for each section of the course, so if we keep the group_info table as it is you'll get multiple groups per course in there, for Canvas courses that have multiple sections. Is that going to work? 

> judell
> Everything that depends on https://jonudell.info/h/analytics/doc/views.html#lms_course_groups should be fine, but naturally we'll want to be able to provide a higher-level whole-course view.
> So, perhaps an identifier for a course, and course_info table keyed on that id that bundles sets of groups? (edited)

> seanh
> Re the LMS group teacher names: will adding these to the group_info table in the LMS DB (or more likely a related table in the LMS DB) work?

> judell
> Although I had proposed group_info in #1684, a course_info table in the LMS DB seems better in light of the above.
