### ISSUE TITLE
Add `make db` command

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1708]
Often enough we end to edit rows in SQL tables that otherwise cause breaking changes with local dbs for developers. Adding a `make db` command that can run a series of updates would be very useful.

We could also have a local file with a number that is generated only by `make db` and a versioned file that is the same thing. If they ever get out of sync, then `make dev` could give a warning or auto run `make db` which may provide more useful output than whatever broken thing may happened as a result of db out of sync.

From Sean
-----------

 People need to upgrade their LMS dev DBs after we merged a DB migration yesterday. The command to do this without resetting your DB is tox -qe dev --run-command 'alembic -c conf/alembic.ini upgrade head' <- @developers
I'd like to make this easier:
1. I think we should add a make db so you don't have to remember that long tox command. This will also paper over that the DB upgrade command is different in h and lms
2. I'd like to merge make devdata into make db. So make db will both upgrade your DB schema (if it's out of date) and (re-)load devdata.
This'll mean that if anything seems to be wrong with your DB, whether crashes like the above or the apps not working correctly due to missing dev data, just running make db should fix it, and will be the same command across apps.
It's also a very simple incremental improvement on the current set up, that should be quick and easy to add to all our apps, and a very small change to developers existing practices: you just need to start using the new make db command when you have a problem.

**Comment by robertknight** [comment]
See also - https://github.com/hypothesis/lms/issues/1751
