### ISSUE TITLE
Don't ask user to click "Authorize" on every page load

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#171]
The app is causing Canvas to show the user an OAuth 2 authorization dialog and ask the user to click <samp>Authorize</samp> whenever:

* An assignment is created or edited (regardless of whether a public URL, Canvas Files or Google Drive assignment)
* A Canvas files assignment is launched

![screenshot from 2018-08-13 17-32-22](https://user-images.githubusercontent.com/22498/44046365-234ffebe-9f23-11e8-8a11-78e6639b7aa8.png)

It does not show the authorize dialog when a public URL (HTML or PDF) assignment is launched, though.

Repeatedly showing the authorize dialog is annoying for the user, reduces security, and creates a lot of access tokens in Canvas.

* The app should re-use the access token that it has saved for that user in the DB.
* When the saved access token has expired the app should use the user's saved refresh token to get a new access token without user interaction.
* The user should only be asked to click <samp>Authorize</samp> the first time they launch the app and, thereafter, only if both the access token and refresh token have expired.

**Comment by jeremydean** [comment]
I'll just add that this is definitely something people notice and grumble about when using the app. I think it should be prioritized once we get to cleaning up app and not adding features. It'd greatly improve the crispness of the app from a UX POV.

**Comment by jeremydean** [comment]
Here's a user in the wild confused by this part of the workflow:

![image](https://user-images.githubusercontent.com/3261902/51191065-3b016e80-18a9-11e9-8192-0089bb535908.png)

https://community.canvaslms.com/groups/designers/blog/2019/01/14/using-the-hypothesis-collaborative-annotation-tool-in-canvas

**Comment by seanh** [comment]
This is fixed now that the `new_oauth` feature flag has been released
