### ISSUE TITLE
Document which LTI parameters the app needs, now and in the future

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#173]
LMS admins can control which parameters are sent to external apps, and some schools want to make sure they’re only sending us what we need. We should have a documented list of what params we need. This should include params we currently use and params we think we might need for future features.

See Slack discussion: 

https://hypothes-is.slack.com/archives/CBN3DGW02/p1534253092000100

**Comment by jeremydean** [comment]
For some reason, it's important for me to maintain the positive side of this need too. Some LMS admins need to know this same list so that they can be sure they are sending everything needed.

**Comment by jeremydean** [comment]
@ajpeddakotla @lyzadanger it'd be great to get this into a sprint ahead of product release so that we can document it publicly for users as part of outreach and demoing. CC @klemay.

**Comment by lyzadanger** [comment]
@jeremydean Yep, it's on the radar for this sprint!

**Comment by lyzadanger** [comment]
Documentation is taking shape here at present: https://github.com/hypothesis/lms/wiki/LTI-Parameters-Required-for-Hypothesis-LMS-App-Integration

**Comment by lyzadanger** [comment]
@seanh I've taken another pass at https://github.com/hypothesis/lms/wiki/LTI-Parameters-Required-for-Hypothesis-LMS-App-Integration and am ready for your review.

In my second pass, I grepped the codebase for every [parameter documented here](https://www.eduappcenter.com/docs/basics/post_parameters). I recognize that this does not include the OAuth parameters but I'm unsure if we should document them here (i.e. for this audience). That is, is there any kind of configuration a normal admin would need to do vis-a-vis OAuth params? Perhaps so; let me know!

There's one parameter I haven't tracked down yet. I see hits in the code but the logic for when it gets used is unsurprisingly...dense. That parameter is `custom_canvas_course_id`. Any quick ideas on that?

**Comment by seanh** [comment]
It looks like `custom_canvas_course_id` is used for the Canvas Files integration. My guess is that when you use the Canvas picker it shows you the list of files that've been uploaded to that course

**Comment by seanh** [comment]
Without the OAuth params our app can't verify the launch request and so can't (or at least shouldn't) launch. There are examples of apps that don't _need_ to verify launches, e.g. if they're not doing anything private. I don't know whether Canvas allows admins to hide these params or not. I've not seen this config screen in Canvas.

**Comment by seanh** [comment]
I would simplify things and just say that all three of `lis_person_name_full`, `lis_person_name_given` and `lis_person_name_family` are required. The app is gonna suck without them. The teacher can't even tell one student from another, if they're all named "Anonymous".

**Comment by seanh** [comment]
I see `custom_canvas_api_domain` being used

**Comment by seanh** [comment]
I'm actually not sure that `custom_canvas_course_id` and `custom_canvas_api_domain` are Canvas parameters. They're defined in our app's XML here: <https://github.com/hypothesis/lms/blob/c032aad4d5ee73a16473e836913002b38d4a7766/lms/config.xml.jinja2#L18-L21>. I can't find great docs on it right now but I think it's a use of this thing: https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html

**Comment by seanh** [comment]
I think there's a bunch of params we may need in the future for grading: lis_result_sourcedid, lis_outcome_service_url, lis_person_sourcedid, etc (possibly other stuff). However maybe the grading feature will just have to be robust -- if a needed param is missing show an error requesting that param?

**Comment by seanh** [comment]
I think `resource_link_title` and `resource_link_description` are the name and description of the assignment. We don't use them but I can imagine we might one day?

**Comment by seanh** [comment]
I could imagine us maybe needing the `tool_consumer_info_product_family_code` and `tool_consumer_info_version` one day, for example to handle different LMS's differently?

**Comment by seanh** [comment]
`tool_consumer_instance_name` and `tool_consumer_instance_description` are the name and description of the institution (University of Washington or whatever). We don't use those but I could imagine we might want to one day

**Comment by seanh** [comment]
That's all my comments! By the way I can't find how as a Canvas admin I can limit what LTI params it sends to the app, and can't find anything about this in the docs. Would be nice to be able to test out this feature / verify that it actually exists. Does anyone know how to do it?

**Comment by lyzadanger** [comment]
A number of these comments are along the lines of "we may need this parameter one day." There's some wording on the current page about how the app may need more parameters in the future—is that sufficient to cover these? I don't know if it's helpful to admin users to list out everything the app _could_ need in the future. We'd be guessing to some extent.
