### ISSUE TITLE
Improve UI when /sync is loading groups

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1748]
When using canvas with section groups enabled, 2 issues can happen.

**Issue 1:** It's not important to show the spinner when the groups are loading via /sync call. It would be better to just load the PDF and sidebar w/o the groups and the lazily populate when the endpoint resolved.

![spinner](https://user-images.githubusercontent.com/3939074/81874588-02bc7f80-9533-11ea-899f-172b12558131.gif)

**Issue 2.** When the /sync API returns an auth error , the spinner shows while the dialog is also rendered requesting authorization for the user. It would be better to just hide the spinner in this case.

![spinner-and-dialog](https://user-images.githubusercontent.com/3939074/81874594-06500680-9533-11ea-8fd4-5dc6ad877855.gif)

**Comment by robertknight** [comment]
Original context from @seanh in Slack:

First issue: https://hypothes-is.slack.com/archives/C1M8NH76X/p1589384535367400
Second issue: https://hypothes-is.slack.com/archives/C1M8NH76X/p1589384651368200
