### ISSUE TITLE
Create a re-usable hash based Id function

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#1755]
We essentially have the same function in a million places. It always does the same thing with different strings e.g.

```python
hash_object = hashlib.sha1()
hash_object.update(tool_consumer_instance_guid.encode())
hash_object.update(context_id.encode())
hash_object.update(str(section["id"]).encode())
return hash_object.hexdigest()
```

It seems like a good idea to:

 * Create a reusable function which does the core part
 * Maybe pull these together? Or is that the bad kind of togetherness? Not sure, we should talk about this one

**Comment by seanh** [comment]
This got done
