### ISSUE TITLE
Add an "include section group" option to smooth transition for existing customers

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#1756]
Currently users are on two sides of a great divide:

 *  Those who don't have sections and never want them
 * ... and those that have them and never want to go back

To allow the former to become the latter, we need to have a better proposition than "You can swap over but all your existing students work is hidden". For these transitioning groups it would be good to have an option to include the course group in the list of sections so a teacher could see the old annotations.

This is part spike as we'd need to work out the best way to do it.

Considerations:

 * This should be an on-request option (off by default)
 * Course sections often have the same name as one of the sections in that course - So they must be visually distinguished
 * How to make this happen with the new sync API?

Options:

 * LMS could modify the name by having "Course: <coursename>" and have it stored as such in h. This would cause the name to jump back and forward if options were changed
 * Have the client be able to accept a name as well as a group id, so LMS can configure how it's presented - This might be good for other reasons too
 * Something else? An icon? Sounds like this could do with some design input

**Comment by seanh** [comment]
Just noting that we need confirmation from product that this is actually wanted / would actually help users. It could still be that something else, or nothing, is the best thing to do here.

Related Slack thread: https://hypothes-is.slack.com/archives/CBN3DGW02/p1589470495166400

**Comment by seanh** [comment]
We'd need to decide whether the "include section group" option is set:

* For the entire application instance
* For particular courses
* For particular assignments

And whether it's just a flag that we set in the DB for them if they ask us to via support, or whether we provide a button in the app for them to toggle this themselves

**Comment by seanh** [comment]
We've decided not to do this: https://hypothes-is.slack.com/archives/CBN3DGW02/p1589491233176000?thread_ts=1589470495.166400&cid=CBN3DGW02
