### ISSUE TITLE
Python and JavaScript dependencies need to be updated and kept up to date

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#176]
The app's Python and JavaScript dependencies haven't been kept up to date and the pyup bot is complaining that we have Python dependency versions with known security vulnerabilities. The dependencies need to be brought up to date and a system put in place so that they stay up to date in future.

We should do this using Dependabot as we do for bouncer.

**Comment by robertknight** [comment]
Dependabot is now enabled for this repo and we've been merging PRs from it. In the case of JS deps I've also removed everything that we are not using. Do you think we can close this yet @seanh?

**Comment by seanh** [comment]
Yeah, I think we can close this. Dependabot hasn't brought everything up to date yet of course, but we just need to keep merging the PRs as they come in, we don't need to track this on the sprint board anymore. Thanks for the tech-debt label too
