### ISSUE TITLE
Move the /welcome page to /

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#178]
The front page of the app is a blank page (without even a link to the `/welcome` page), meanwhile the registration form is at the URL `/welcome`.

1. Render the registration form at `/` rather than at `/welcome`.
2. Make `/welcome` redirect to `/` so that existing links keep working

This way we don't have a weird, blank page as our app's front page.

**Comment by marcospri** [comment]
This was done when basically removing /welcome. Now both take you to:

https://web.hypothes.is/help/installing-the-hypothesis-lms-app/
