### ISSUE TITLE
Change text re: Canvas integration at https://lms.hypothes.is/welcome

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#1781]
Currently https://lms.hypothes.is/welcome contains the following language:

> Canvas File Picker Integration
> The following fields are only needed if you are using the Canvas LMS and would like to enable the file picker.

Canvas Developer credentials are also required for our Sections feature, so this text is now outdated.

Question for @jeremydean, @mkdir-washington-edu and @ErynHypothesis: what should this text say instead? We could do:

> Canvas Developer Credentials
> The following fields are only needed if you are using the Canvas LMS and would like to enable the file picker and sections features. Please note that these features may not be implemented separately.

**Comment by mkdir-washington-edu** [comment]
@klemay I might add "these features may not be implemented separately". Other than that I think it's good.
