### ISSUE TITLE
Canvas Picker UI is confusing

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#181]
Writing this up because of two tickets that have come up in the past week:

- https://hypothesis.zendesk.com/agent/tickets/2782
- https://hypothesis.zendesk.com/agent/tickets/2879

There are two main points of confusion with the Canvas Picker:
- When a file is selected, there is not sufficient feedback indicating this to the user, so the user thinks they are not able to select a file
- When the browser window is small, the Canvas Picker window is small as well. This hides the Submit button and it's not apparent to the user that they can expand the window.  

### Steps to reproduce
1. Use a Canvas course site with the Canvas File Picker enabled and with at least 2 PDFs uploaded
2. Create a new Module item or assignment using the Hypothesis app and Canvas Picker
3. A window will pop up, showing the files in the course site file repository. It will look like this:
<img width="819" alt="making-the-real-selected" src="https://user-images.githubusercontent.com/12087705/44353656-9ef84600-a475-11e8-91a7-110673879e2f.png">
4. Try to select the first file by clicking on the file title. Your window still looks like this:
<img width="819" alt="making-the-real-selected" src="https://user-images.githubusercontent.com/12087705/44353674-b1727f80-a475-11e8-951f-8750156f1609.png">
5. If you try to select the 2nd file, there is a subtle change in background color, but not enough to tell the user they've successfully selected the file:
<img width="829" alt="pride-and-prejudice-selected" src="https://user-images.githubusercontent.com/12087705/44353714-db2ba680-a475-11e8-8ab0-ca2f60146063.png">

At this point, the user can click "Submit" and successfully create the module item or assignment, but users sometimes stop here, thinking nothing has happened and they can't continue. 

## Not obvious when Submit button is hidden because of window size

When a user is working on a smaller screen or in a smaller browser window, the Canvas File Picker frame will appear shrunken. This leads to users thinking:
- Not all of their Canvas files are available for selection
- The Submit button isn't present

This is remedied by adjusting the frame like so:

![canvas-picker 1](https://user-images.githubusercontent.com/12087705/44354043-c56ab100-a476-11e8-9300-b9d00406d702.gif)

But users don't realize they have the ability to enlarge the window. More concerning is the fact that they think items are just not available rather than hidden by a small window.

**Comment by klemay** [comment]
The "hidden" submit button came up again today: https://hypothesis.zendesk.com/agent/tickets/3624

**Comment by robertknight** [comment]
This will be resolved by #502 where we'll be implementing a new UI that has had UX input from Sean and Lyza.

**Comment by seanh** [comment]
This is fixed now that the `new_oauth` feature flag has been released
