### ISSUE TITLE
Migrate as many of the jinja2 server side templates to client side as reasonable  

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#1817]
We have a large number of server side templates to facilitate interfaces fo LMS.
In some cases the class names and HTML is a copied from the preact client side components and this can lead to a divergence and duplication of code. 

It's possible that some of these templates could be handled client side with some restructuring of the server endpoints. For example, we would return basic template with embedded state values (e.g. `js-config`) for the client to construct the UI entirely on the client. This would allow us to consolidate UI code and have more re-use and consistency of error, and prompt dialogs.

- [ ] Figure out the scope of the migration and what needs to change on the server and client.

_todo: fill in the tasks as this gets scoped out._

![Screen Shot 2020-06-08 at 9 05 02 AM](https://user-images.githubusercontent.com/3939074/84053703-283c7d80-a967-11ea-92ac-3f458b3fb599.png)

**Comment by robertknight** [comment]
I'd suggest taking a step back and just focus on the problem to solve for the moment. Converting server-rendered UI (especially a fairly simple template) to client-rendered has some downsides in terms of adding new failure modes and complexity so we probably don't want to do it for everything. There are some other options to avoid styling inconsistency that we should at least enumerate.

**Comment by robertknight** [comment]
We converted the main template that was a source of problems, the OAuth error dialog, from a server to client-rendered widget. On that basis I'm going to close this for now.
