### ISSUE TITLE
Dialog changes size when displaying an error

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1832]
As you can see in the GIF, the width and height of the dialog changes slightly when it goes from a "loading" state to an "error" state:

![Peek 2020-06-10 15-35](https://user-images.githubusercontent.com/22498/84281153-240f8c00-ab30-11ea-9c9c-a15caddba229.gif)

**Comment by robertknight** [comment]
I hope you don't mind @LMS007 but I took a look at this today as it overlapped with an issue I'd faced when working on the VitalSource prototype.

**Comment by robertknight** [comment]
Oh, sod it. This is the wrong issue. I meant https://github.com/hypothesis/lms/issues/1890.

**Comment by robertknight** [comment]
Kyle reminded me to take another look at an earlier attempt to resolve this: https://github.com/hypothesis/lms/pull/1855

**Comment by lyzadanger** [comment]
This issue should no longer apply with updated, shared components and patterns.
