### ISSUE TITLE
Settings JSON mutation tracking is broken

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1839]
Mutating JSON model fields does not work -- the mutations aren't being saved.

**This applies to everywhere we've used JSONB columns** (ApplicationInstance, Course, and GroupInfo).

For example, here's me changing an application instance settings, and then verifying that the setting was not, in fact, changed:

```python
In [32]: request.tm.begin()                                                                                                                                                                             
Out[32]: <transaction._transaction.Transaction at 0x7f847d6f93c8>

In [33]: ai = request.db.query(ApplicationInstance).filter_by(consumer_key='Hypothesis320fc6b08d98904f353cb032b671e13d').one()                                                                          

In [34]: ai._settings["canvas"]["sections_enabled"]                                                                                                                                                     
Out[34]: False

In [35]: ai._settings["canvas"]["sections_enabled"] = True                                                                                                                                              

In [36]: request.tm.commit()                                                                                                                                                                            

In [37]: request.tm.begin()                                                                                                                                                                             
Out[37]: <transaction._transaction.Transaction at 0x7f8477e9dcc0>

In [38]: ai = request.db.query(ApplicationInstance).filter_by(consumer_key='Hypothesis320fc6b08d98904f353cb032b671e13d').one()                                                                          

In [39]: ai._settings["canvas"]["sections_enabled"]                                                                                                                                                     
Out[39]: False
```

The reason is that, even though we're using `MutableDict.as_mutable(JSONB)`, that still doesn't detect mutations of sub-objects. There's some explanation and links to the relevant SQLAlchemy docs in this blog post: https://amercader.net/blog/beware-of-json-fields-in-sqlalchemy/ Unfortunately that post suggests that the solution is to use a third-party library with no tests.

If you instead change the setting via the `ApplicationSettings` class (`ai.settings.set("canvas", "sections_enabled", True)`) that _does_ work. It seems to be because `ApplicationSettings` uses `setdefault`, and somehow changes _are_ picked up when `setdefault` is used:

```python
In [2]: from lms.models import ApplicationInstance                                                                                                                                                      

In [3]: ai = request.db.query(ApplicationInstance).filter_by(consumer_key='Hypothesis320fc6b08d98904f353cb032b671e13d').one()                                                                           

In [4]: ai._settings                                                                                                                                                                                    
Out[4]: {'canvas': {'sections_enabled': False}}

In [5]: ai._settings.setdefault("canvas", {})["sections_enabled"] = True                                                                                                                                

In [6]: request.tm.commit()

In [7]: request.tm.begin()                                                                                                                                                                              
Out[7]: <transaction._transaction.Transaction at 0x7f63862a1710>

In [8]: ai = request.db.query(ApplicationInstance).filter_by(consumer_key='Hypothesis320fc6b08d98904f353cb032b671e13d').one()                                                                           

In [9]: ai._settings["canvas"]["sections_enabled"]                                                                                                                                                      
Out[9]: True
```

Nonetheless, we need to fix the first instance where mutating `_settings` directly doesn't work, because that's just a bug waiting to happen.

**Comment by seanh** [comment]
I think we should consider doing away with the `ApplicationSettings` class because it's a bit fiddly, and instead write our own custom SQLAlchemy type.  This is what https://github.com/edelooff/sqlalchemy-json does, for example. But we want slightly more than that. We want two custom behaviours that the standard JSON types don't have:

1. We want it to return `None` if requesting a key that doesn't exist (even in a sub-object that doesn't exist). Also support setting values in sub-objects that don't exist yet

2. We want mutation tracking, even into sub-objects

The fact is that JSON in SQLAlchemy does not work in the way that we want it to work / are trying to use it, and this is causing us fiddly code and multiple bugs.

So I think if we want to do this we need to write a custom SQLAlchemy type that works how we expect it to work

**Comment by jon-betts** [comment]
A library has been written to try and fix this: https://github.com/hypothesis/sqlalchemy-frozenjson

It needs a review, (and hasn't actually been tested in an SQLAlchemy context yet!), but I think it'll do the job.
