### ISSUE TITLE
Dialog changes size when expanding "Error Details"

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#1890]
When I expand or collapse the **Error Details** the whole dialog changes size both horizontally and vertically:

![changingsize](https://user-images.githubusercontent.com/22498/87021201-d046a000-c1cc-11ea-941c-007a18abe51e.gif)

![changingsizeagain](https://user-images.githubusercontent.com/22498/87022433-64fdcd80-c1ce-11ea-832f-1059e6a14191.gif)

**Comment by robertknight** [comment]
I'm intending to make some changes to the dialog to make setting a minimum size easier. However, we may decide to ignore this issue or only fix it for some dialogs as it may not look great in some cases to reserve space for dialogs which is only used if `Error Details` is actually toggled.

**Comment by seanh** [comment]
Look at Jon's implementation of the same dialog design in Via 3 (which is shown in the same place as the LMS app's dialogs in the LMS context) for an example of one that extends vertically but not horizontally:

![Peek 2020-07-30 10-33](https://user-images.githubusercontent.com/22498/88907158-3c5a7800-d250-11ea-8243-dc86e74b0639.gif)

(Also note that LMS's own implementation of this same dialog didn't have this problem until recently.)

I think it's fine for an error dialog to extend downwards when Error Details is expanded but it's weird for it to unnecessarily extend in all four directions as it does currently.

Extending up as well as down may (which Via 3's version does) may be acceptable because it's a result of the vertical centering of the whole dialog, although I think it would be better if it extended downwards only.

Extending horizontally as well as vertically is quite bad though, IMO.
