### ISSUE TITLE
Canvas file picker is not allowing users to scroll

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#2003]
I’ve had a few folks complain about the Canvas picker, and I think this may be a change in Canvas. The Canvas picker list of files is extending past the scrollable window and can’t be scrolled through. I keep having to expand the Canvas window to see my files.

![image](https://user-images.githubusercontent.com/22603275/90271221-753a4580-de29-11ea-96a1-8e071076350a.png)

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/11998
https://hypothesis.zendesk.com/agent/tickets/11972

**Comment by robertknight** [comment]
I have deployed a fix for this issue. As described in https://github.com/hypothesis/lms/pull/2018, this involved reverting a part of some accessibility improvements for dialogs in the LMS app. Fortunately the accessibility feature that was removed is nice-to-have rather than essential.

**Comment by robertknight** [comment]
I'm closing this issue as fixed for the moment, although investigation into re-introducing dialog descriptions is on-going.
