### ISSUE TITLE
Harmonize button styles with Hypothesis client

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#2208]
As noted by Lyza [in a review](https://github.com/hypothesis/lms/pull/2203#pullrequestreview-518988348) (, the style for buttons in the LMS frontend is a little different than the Hypothesis client. This can be jarring when both are visible on screen at the same time.

From the linked review:

> Specifically, [the LMS buttons are] one grey-shade too dark, and the hover is bright red, whereas it's a much more subtle darker-grey in the client

**Comment by lyzadanger** [comment]
There are a couple of custom buttons in the grading components that don't use shared components yet, but they are of a _completely_ different style to standard buttons, so I don't think they fall under this directive.

This is, thus, otherwise, done/fixed!
