### ISSUE TITLE
Investigate why course copy does not work in Moodle and Blackboard

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#2218]
See also:

* [EPIC: Course copy](https://github.com/hypothesis/lms/issues/2241)

This is a follow up to https://github.com/hypothesis/lms/issues/555#issuecomment-706367981 and [this Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1604423482033100). We know why course copying can cause problems in Canvas if the assignment uses Canvas files. However we're not yet certain why the [problems](https://github.com/hypothesis/lms/issues/555#issuecomment-706367981) described in Moodle and Blackboard occur.

This issue covers investigating the steps to reproduce mentioned in https://github.com/hypothesis/lms/issues/555#issuecomment-706367981 and finding out why they happen. One speculation is that the copied assignment has a different ID and this breaks the link to assignment metadata in our DB. If so, what can we do about that?

**Comment by robertknight** [comment]
Related Slack thread about LTI specification support for course copying: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1604478759046900

**Comment by seanh** [comment]
Steps to reproduce in Blackboard: https://github.com/hypothesis/support/issues/146#issuecomment-706360142

Steps to reproduce in Moodle: https://github.com/hypothesis/support/issues/146#issuecomment-706363912

**Comment by seanh** [comment]
## Copying a Web Link Assignment in Blackboard

1. Create a Hypothesis assignment in a Blackboard course by following the **If an administrator has not installed the app** instructions in [our docs](https://web.hypothes.is/help/creating-hypothesis-enabled-readings-in-blackboard/) (Build Content -> Web Link, check _This link is to a Tool Provider_, enter a key and secret, then launch the assignment to choose its document)

2. Copy the course by following the instructions here: https://help.blackboard.com/Learn/Instructor/Course_Content/Reuse_Content/Copy_Courses

Result:

* The assignment doesn't appear in the copied course when _Edit Mode_ is off. You can't launch the assignment
* When _Edit Mode_ is on you can see the assignment and edit it, but when you edit it the key and secret are gone
* Blackboard forces you to re-enter the key and secret. If you re-enter those then you can see the assignment when _Edit Mode_ is off again and can launch it, but our LMS app then asks you to re-select the assignment's document
* The assignment ID (`resource_link_id`) that Blackboard launches the assignment with has changed, so Hypothesis can no longer find the assignment's configuration in the DB
* Blackboard includes the original assignment ID in a `resource_link_id_history` launch param
* The original course ID is also in `context_id_history`

**Comment by seanh** [comment]
## Course Copy in Moodle

The issue is the same as in Blackboard: the `context_id` and `resource_link_id` params change when the course is copied so we can't find the assignment's settings in the DB.

Moodle doesn't include the `resource_link_id_history` and `context_id_history` launch params, or any other launch params that can help with this.
