### ISSUE TITLE
Remove unused dependencies

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#223]
The app has various Python and JavaScript dependencies that it doesn't actually use. These should be removed. We need to go over all the app's dependencies and check which aren't used.

**Comment by robertknight** [comment]
I have gone through and removed all of the JS dependencies that we are not actually using:

- https://github.com/hypothesis/lms/pull/240
- https://github.com/hypothesis/lms/pull/241
- https://github.com/hypothesis/lms/pull/247

**Comment by robertknight** [comment]
I've had a look through the Python dependencies in `requirements.in` and the only one I can see that we are not currently using is `pyramid_services`. I'm almost certain we will want to use that though, so I haven't rushed to remove it.

Do you think we can close this now @seanh or are there any other places to check?

**Comment by seanh** [comment]
We're expecting to use pyramid_services pretty soon, yeah. Thanks for looking through these! Yes, I think we can close this now
