### ISSUE TITLE
Broken dialog is briefly shown between authorizing API access and showing the list of Canvas files

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2232]
Slack thread: https://hypothes-is.slack.com/archives/C1M8NH76X/p1604921777441800

## Reproducing

To reproduce this issue you need to create a situation where the user's Canvas access token is either missing or incorrect so that the app will ask them to re-authorize. One way to do this is to break all the access tokens in your local DB:

    tox -qqe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo', refresh_token = 'foo';"

It can also help to slow down API response times to make the issues easier to spot. Here's a diff that will make requests take 3 seconds to respond and that will also make every 2/3 requests respond with no files and every 3/3 request respond with the actual list of files:

```diff
diff --git a/lms/views/api/canvas/files.py b/lms/views/api/canvas/files.py
index d978e1cc..1f94534a 100644
--- a/lms/views/api/canvas/files.py
+++ b/lms/views/api/canvas/files.py
@@ -3,6 +3,8 @@ from pyramid.view import view_config, view_defaults
 
 from lms.views import helpers
 
+foo = 0
+
 
 @view_defaults(permission="api", renderer="json")
 class FilesAPIViews:
@@ -18,7 +20,17 @@ class FilesAPIViews:
         :raise lms.services.CanvasAPIError: if the Canvas API request fails.
             This exception is caught and handled by an exception view.
         """
-        return self.canvas_api_client.list_files(self.request.matchdict["course_id"])
+        files = self.canvas_api_client.list_files(self.request.matchdict["course_id"])
+
+        global foo
+        import time; time.sleep(3)
+
+        if foo < 2:
+            foo += 1
+            return []
+
+        foo = 0
+        return files
 
     @view_config(request_method="GET", route_name="canvas_api.files.via_url")
     def via_url(self):
```

## Problem

![Peek 2020-11-09 11-27](https://user-images.githubusercontent.com/22498/98536004-f6657500-227e-11eb-9f3a-374ef7db8f0a.gif)

The list-files dialog is temporarily shown with an empty table and with incorrect buttons (the <kbd>Authorize</kbd> button). The table also seems to overlap the top of the button:

![Screenshot from 2020-11-09 11-29-15](https://user-images.githubusercontent.com/22498/98536283-755aad80-227f-11eb-90d6-11c3aa78efaa.png)

## Solution

After the user clicks <kbd>Authorize</kbd> in the popup window the UI should transition smoothly from the previous view (the **Select web page or PDF view**) to the **Select a file** view (whether showing the files or showing the empty-files dialog) without any glitches in-between.

**Comment by esanzgar** [comment]
I have triaged this issue and it seems to be caused by a CSS rule in this line:

https://github.com/hypothesis/lms/blob/5db1f39e927e534d03c6f01a481933e2b4c666d8/lms/static/styles/components/_FileList.scss#L13

![Edit-assignment (1) (1)](https://user-images.githubusercontent.com/8555781/98664756-12364d00-234b-11eb-8e2a-8e147e53b36f.gif)

See also #2234

**Comment by seanh** [comment]
I think this is a bigger problem than just the table height. Even if the table height were corrected, the app is showing the **Select a file** dialog with the <kbd>Authorize</kbd> button on it. The <kbd>Authorize</kbd> button belongs to another dialog, it should never be shown on the **Select a file dialog**.

**Comment by esanzgar** [comment]
There are three general ways to update a UI:

1. an optimistic update, in which one _assumes_ the action just performed
has a positive outcome and presents that in the UI. If that's not the case,
it is reverted. In our particular case, it would mean to _inmediately_
present the `Select` button and revert back to `Authorize` if the request
for files failed.

2. pessimistic update: just the opposite of the above.

3. wait _until_ the outcome of the request is known. This will mean to show
a general spinner, remove the button or show a spinner on the button.

Based on [your comment on a previous PR](https://github.com/hypothesis/lms/pull/2219#issuecomment-721833947, I
implemented a pessimistic update.

I am happy to implement either one of these options. We should agree on the
best approach.

**Comment by seanh** [comment]
We should always do option 3 -- show a spinner and wait until the outcome of the network request is known before progressing to the next dialog. We need to avoid flickering, popping / jumping and general "glitching" of the UI when it's changing between states, and option 3 is the way to do this.

In this particular case you need to wait for the result of the network request in order to know whether to show the **Select a file** dialog or the **Allow file access** dialog. The problem seems to be that the app is moving straight to the **Select a file** dialog as soon as the button is clicked and then, when it gets the response to the network request, it changes to the **Allow file access** dialog. This means that the **Select a file** dialog is briefly shown and then changes to **Allow file access**, so you have a flicker. The version of the **Select a file** dialog that's shown also has a broken layout and has an <kbd>Authorize</kbd> button that doesn't belong. But the app shouldn't be going to the **Select a file** dialog at all, it should go directly from **Select web page or PDF** to **Allow file access**.

**Comment by esanzgar** [comment]
This was the situation before #2219:

![Optimistic update](https://user-images.githubusercontent.com/8555781/99543741-ccfdc500-29b3-11eb-8db3-a444bb819437.png)

After #2219:

![Pessimistic-optimistic update](https://user-images.githubusercontent.com/8555781/99543791-dbe47780-29b3-11eb-9534-78b07600c53b.png)

And I based on @seanh's comments this could be a way to do it:

![Pessimistic -- proposal](https://user-images.githubusercontent.com/8555781/99544066-2b2aa800-29b4-11eb-8801-6557b2a0e7e1.png)
