### ISSUE TITLE
Some red buttons have an incorrect black border

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2233]
It only seems to affect some buttons not all, but some of the red buttons in the app seem to have grown a black border that isn't supposed to be there. Examples:

![Screenshot from 2020-11-09 12-07-39](https://user-images.githubusercontent.com/22498/98539630-9671cd00-2284-11eb-9421-371393c4e9d3.png)

![Screenshot from 2020-11-09 12-06-47](https://user-images.githubusercontent.com/22498/98539633-970a6380-2284-11eb-94fa-8a242453c907.png)

**Comment by esanzgar** [comment]
@seanh reported this in Chrome 86.0.4240.183

**Comment by esanzgar** [comment]
I don't see this on my Chrome 86.0.4240.183 on a Mac:

![Screenshot 2020-11-10 at 14 53 29](https://user-images.githubusercontent.com/8555781/98682904-be386200-2364-11eb-930b-5019b73eabeb.png)

Neither on Firefox

**Comment by esanzgar** [comment]
The text on these dialogues are different. I wonder if @seanh needs to update his local copy...

**Comment by seanh** [comment]
You can find these in the production app so it's not due to my local copy. Some buttons have the border and some don't, though, so you have to click around within the app to find them all. Some buttons show the black border on hover and some only show it when clicked.

@esanzgar note that the dialog shown in your screenshot is a different dialog than the examples I posted above. That's a different button

**Comment by esanzgar** [comment]
@seanh I tried on the dialogue `Select web page or PDF` too, which I guess is the same, but failed to reproduce.

**Comment by esanzgar** [comment]
I believe these are the `focus` ring. If you press `tab` key, it should move to the next element with tabindex.

I believe focus ring may show differently among browser and platforms.

**Comment by esanzgar** [comment]
I have checked and LMS doesn't use any custom style for the focus ring, so this style must be the default browser's stylesheet.

**Comment by esanzgar** [comment]
If this [PR](https://github.com/hypothesis/lms/issues/2280) from @LMS007  gets merge it will make the focus ring more subtle: that's because the red background colour when a button is hovered has been removed. Hence, when a button is both focused and hovered the focus ring will be less apparent.

This may be a bad for accessibility purposes: https://developer.mozilla.org/en-US/docs/Web/CSS/outline#Accessibility_concerns

**Comment by robertknight** [comment]
Sean opened two new, more specific issues which replace this one: https://github.com/hypothesis/lms/issues/2295 and https://github.com/hypothesis/lms/issues/2296.

Note that because we are using system-provided focus rings, the color depends on the browser and OS.
