### ISSUE TITLE
`make sure` failing on BDD tests

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#2248]
I like to use `make sure` as a sanity check before pushing up working branches to origin. Right now, LMS' `make sure` is failing for me:

```
$ make sure
All done! ✨ 🍰 ✨
275 files would be left unchanged.
___________________________________________________________________________________ summary ___________________________________________________________________________________
  checkformatting: commands succeeded
  congratulations :)
************* Module tests.bdd.steps._compiled_feature_steps
tests/bdd/steps/_compiled_feature_steps.py:7:0: E0611: No name 'step' in module 'behave' (no-name-in-module)
```

**Comment by seanh** [comment]
@lyzadanger can you try deleting your `.tox` directory and re-running?

**Comment by lyzadanger** [comment]
@seanh Thanks for the suggestion. I had already done that before filing the issue, and just re-verified that it doesn't rectify the issue for me.

**Comment by marcospri** [comment]
Can't find a slack thread for this but it must have resolved itself.
