### ISSUE TITLE
Fix course copy in Moodle

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2281]
Course copied Hypothesis assignment's don't work in Moodle -- they forget the assignment's configured document URL, and the teacher has to select it again. See https://github.com/hypothesis/lms/issues/2218#issuecomment-732988452

**Comment by seanh** [comment]
We're waiting for a chance to speak to Moodle developers about this in order to figure out a solution.

**Comment by marcospri** [comment]
Still no fix: https://github.com/hypothesis/lms/issues/5061
