### ISSUE TITLE
Error dialog when fetching a grade fails is different from other error dialogs

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2320]
## Problem

The error dialog that's shown when fetching a grade fails is different from other dialogs in the app:

![Screenshot from 2020-12-21 11-15-07](https://user-images.githubusercontent.com/22498/102771458-d6e16200-437d-11eb-9e9c-4eb9e2280646.png)

![Screenshot from 2020-12-21 11-14-51](https://user-images.githubusercontent.com/22498/102771459-d779f880-437d-11eb-9368-8fd17e1765e7.png)

## Reproducing

Apply the diff below to cause fetching grades to fail. Then log in to hypothesisuniversity.moodlecloud.com as a teacher, launch an assignment, and go to a student.

```diff
diff --git a/lms/services/lti_outcomes.py b/lms/services/lti_outcomes.py
index 5bf7cd77..bccd62d6 100644
--- a/lms/services/lti_outcomes.py
+++ b/lms/services/lti_outcomes.py
@@ -134,6 +134,7 @@ class LTIOutcomesClient:
             status = header["imsx_POXResponseHeaderInfo"]["imsx_statusInfo"][
                 "imsx_codeMajor"
             ]
+            foo = data["foo"]
 
         except KeyError as err:
             raise LTIOutcomesAPIError("Malformed LTI outcome response") from err
```

## Solution

This dialog should re-use the HTML and CSS used for other dialogs elsewhere in the app, including:

- [x] It shouldn't have the **: (**
- [x] The font should be smaller
- [x] The font color should be darker
- [x] The dialog should be less wide
- [x] The dialog should be less tall

There are probably other differences too. If it can re-use the HTML and CSS that should catch them all.

**Comment by LMS007** [comment]
Repurposing this ticket to change the fetch/submit error dialogs to behave more like LaunchErrorDialogs with retry buttons that re-send the appropriate requests and can not be dismissed on click (and possible don't have a "X") -- TBD.

Also, the CSS/Styling of all dialogs should be consistent across the app. Some of those changes were addressed here that still need to be merged https://github.com/hypothesis/lms/pull/2329/files
