### ISSUE TITLE
Ordinary auth errors for canvas produce lengthy stack traces

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#2385]
Loading an assignment could produce an exception followed by a long stack trace in the logs. This seems excessive for ordinary 403 errors. 

_If there is a particular reason for this, then please close this ticket._

Steps to reproduce:

Load a new assignment in canvas with an expired auth token, or clear the token first
```
tox -qqe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo1', refresh_token = 'foo1';"
```

![Screen Shot 2021-02-02 at 8 48 27 PM](https://user-images.githubusercontent.com/3939074/106699596-05b34080-6598-11eb-8efa-0132c09b211f.png)

It's probably reasonable to produce a single log message, such as
"We don't have a Canvas API access token for this user" and possible print the users name, but an entire stack trace seems excessive. Such 403 errors do not report any log message or exceptions when connected to other LMS systems such  moodle.

**Comment by marcospri** [comment]
This a bit better now, it shows:


```DEBUG [lms.views.api.exceptions:165][MainThread] Exception view for: OAuth2TokenError```
