### ISSUE TITLE
Fix default and dialog colors in LMS

### ISSUE THREAD

**Issue by LMS007** [hypothesis/lms#2421]
1. There is no default color so it defaults to black. We probably want to set it to grey-7 to match the client.
2. The color in the LMSGrader's error dialogs is grey-6 and this currently does not match the default (black) on other dialogs. It would be best to remove this color, but perhaps maintain a lighter grey-6 for the LMSGrader's text if desired -- grey-7 may also work.

**Comment by lyzadanger** [comment]
All dialogs use shared components, so colors should be aligned now.
