### ISSUE TITLE
Make form input styling consistent between client and LMS frontend

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#2422]
Text input fields in the client currently use different styling than the LMS frontend. In particular the LMS frontend uses the browser's default focus ring whereas the client uses a [custom style](https://github.com/hypothesis/client/pull/2953) that was introduced to fix https://github.com/hypothesis/lms/issues/2296.

LMS frontend:

<img width="413" alt="lms-input" src="https://user-images.githubusercontent.com/2458/107771029-169b4900-6d32-11eb-8bc4-a6ae3eca2f2e.png">

Client:

<img width="417" alt="client-input" src="https://user-images.githubusercontent.com/2458/107771049-1bf89380-6d32-11eb-995f-10d51a475b27.png">

**Comment by lyzadanger** [comment]
This is done in all places except for the grading controls, which are covered in https://github.com/hypothesis/lms/issues/3292
