### ISSUE TITLE
Replace pycrypto

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#2451]
The LMS app currently depends on pycrypto which is unmaintained and does not work with the newest Python versions (3.9 at the time of writing).

We currently use this package for:

- A secure random number generator. This could be replaced with the builtin `secrets` package in Python
- Encrypting and decrypting the Canvas developer secret that is stored in the database with a server-instance specific secret - the `LMS_SECRET` var. I presume the logic was to limit the risk to third parties if an unauthorized copy of a database dump was obtained.

Possible replacements include [pycryptodome](https://github.com/Legrandin/pycryptodome), intended as a drop-in replacement for pycrypto, and [cryptography](https://cryptography.io/en/latest/).

**Comment by seanh** [comment]
I think this was done
