### ISSUE TITLE
Show the user a helpful error message when an application instance has groups enabled but the developer key doesn't have the necessary scopes

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2561]
The _Developer key scopes missing_ error dialog is already shown if sections is enabled and the developer key lacks the sections scopes. This same error message also needs to be used if groups scopes are missing

**Comment by marcospri** [comment]
Same message as for sections but now with the extended list of scopes:

![Screenshot from 2021-06-14 14-31-30](https://user-images.githubusercontent.com/1433832/121892940-ac190a80-cd1d-11eb-858e-e34ca434e6f8.png)
