### ISSUE TITLE
Add groups scopes to our developer key scopes docs

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2562]
Add the scopes needed by the groups feature to the docs here: https://github.com/hypothesis/lms/wiki/Canvas-API-Endpoints-Used-by-the-Hypothesis-LMS-App

**Comment by marcospri** [comment]
Updated on 
- Working Production API Key with All Required Scopes
- Working QA API Key with All Required Scopes
- 'Working localhost (make devdata) API Key with All Required Scopes'
