### ISSUE TITLE
Provide Canvas file picker-like functionality for other LMSs 

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#257]
The Canvas file picker provides a key piece of functionality for the workflow of teachers using the LMS app. They are able to use PDFs housed in the course itself where they typically store course materials, rather than hosting them somewhere else like Google Drive or the web. Providing a similar option for users of the app in other LMSs would bring parity to those institutions.  

My understanding is that these file repositories operate differently in the various LMSs. Sometimes there are knowable public URLs for the files. Sometimes APIs would be needed to access them. Sometimes those APIs are not available.

If this work is indeed specific to each LMS, we should prioritize the job for each based on some combination of market share and current usage of Hypothesis, likely starting with Blackboard and then Moodle.

**Comment by jeremydean** [comment]
I'm assuming this is likely to be relatively customized per each LMS. If that's the case I can provide a prioritized list of LMSs from a business/partnership POV. 

Also to be considered is how robust the APIs are for the various LMSs as we'll likely be leveraging those as we do with Canvas. I've heard that the APIs for Blackboard are not great, for example.

**Comment by jeremydean** [comment]
Here's a resource on Moodle file APIs that might be useful when we get to this issue:

https://docs.moodle.org/dev/File_API_internals

**Comment by robertknight** [comment]
#500 and #502 are steps towards this as we'll be removing much of the Canvas-specificness from the file picker. We will still have to do some additional work to support other LMSes here, but it will get us much closer.

**Comment by seanh** [comment]
This is too broad. Let's open separate issues for specific LMS's (Blackboard, Brightspace, ...) or other file storage solutions that people use, as and when it becomes a priority to add them

**Comment by klemay** [comment]
@jeremydean I've created issues for Blackboard and Moodle. Are those still the 2 you want to start with?

**Comment by jeremydean** [comment]
@klemay Blackboard should definitely be next in line. Let's chat about whether Sakai or Moodle should follow.

By the numbers, Moodle should probably follow, but we do have several high profile Sakai potential partners who have asked for this as well.
