### ISSUE TITLE
LMS app not launching in D2L / Brightspace

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#258]
Right now, the LMS app does not launch properly in the D2L Brightspace LMS. Here's what happens when attempting to open an H assignment after adding the Hypothesis app as a "External learning tool link" to a course:

User sees this:

![image](https://user-images.githubusercontent.com/3261902/46086525-e6a57800-c16d-11e8-8dd9-6dde5ff4ee9d.png)

Console reads:

![image](https://user-images.githubusercontent.com/3261902/46086564-fae97500-c16d-11e8-8bea-eb294a92822b.png)

It's possible that custom parameters need to be entered during the creation of the external learning tool link.   

D2L has provided us with access to an install for testing [here](https://partners.brightspace.com/d2l/login). The credentials are as follows:

Administrators

Hypothesis.A1
Hypothesis.A2
Hypothesis.A3
Hypothesis.A4
Hypothesis.A5 

Instructors

Hypothesis.F1
Hypothesis.F2
Hypothesis.F3
Hypothesis.F4
Hypothesis.F5

Students

Hypothesis.S1
Hypothesis.S2
Hypothesis.S3
Hypothesis.S4
Hypothesis.S5

Password: See [Slack link](https://hypothes-is.slack.com/archives/C0FK6RWKG/p1537973594000100).

**Comment by robertknight** [comment]
Figured out the OAuth issue. It was issue (3) from that list. The input field where the secret key is entered is limited to 100 chars, but the lms app generates 128-char secrets. When pasting the secret into the link secret field, it gets silently truncated to 100 chars, which is often not noticeable.

I changed the secret key for my test instance to be the first 100 chars of the original key, reset the key in the lms app and was then able to launch the assignment.

**Comment by robertknight** [comment]
In order to successfully launch an assignment _without_ provisioning, at least the following options have to be checked when configuring the LTI link:

<img width="400" alt="brightspace minimum details for lms app" src="https://user-images.githubusercontent.com/2458/49377448-1dfe4b00-f702-11e8-8b15-417152ce3b3d.png">

**Comment by lyzadanger** [comment]
I'd wager that for the app to function successfully and usefully, the following checkboxes should likely also be checked:

* `Send course information to tool provider` (we use course name as the group name and the course's ID to generate a unique ID for the group)
* `Send user name to tool provider` (we need a user's name to create a display name for them)

@klemay Maybe one for you to track (i.e. "how to set up Hypothesis in D2L/Brightspace")?

**Comment by robertknight** [comment]
> I'd wager that for the app to function successfully and usefully, the following checkboxes should likely also be checked:

When provisioning is enabled, you do indeed also need to check "Send user name to tool provider". If you don't, the user name shows up as "Anonymous" in the app. The group name shows up correctly even though I haven't checked the "Send course information to tool provider" checkbox. The group name gets passed via the `context_title` form parameter. In other words, this is covered by the "Send context information" option. 

<img width="300" alt="Brightspace LTI config" src="https://user-images.githubusercontent.com/2458/49378924-ceba1980-f705-11e8-867d-f2dc970a57a9.png">

<img width="400" alt="hypothesis client brightspace" src="https://user-images.githubusercontent.com/2458/49378975-f4472300-f705-11e8-8a04-82e8349ef61e.png">
