### ISSUE TITLE
Audit buttons for replacement with components in `frontend-shared` package

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#2587]
We want to start replacing button elements and the `Button` component in preact components here with variants from the `frontend-shared` package. The first step is to audit the existing buttons to see which have immediately-available drop-in replacements. If you are running your local web server for the `client`, you can see [available shared UI button patterns in the pattern library](http://localhost:3000/ui-playground/shared-buttons). Are there buttons in the LMS frontend components that can't be covered by those patterns?

**Comment by LMS007** [comment]
### FilePickerApp

![Screen Shot 2021-04-21 at 3 51 09 PM](https://user-images.githubusercontent.com/3939074/115750584-2ac07f80-a34d-11eb-8eb4-af4e33a9b641.png)


**Proposal:**
Convert to LabeledButton


**Differences from frontend-shared button(s):**
Hover is red
Padding/Margin slightly different
No color transition on hover

### LaunchErrorDialog :: BaseDialog :: Dialog

![Screen Shot 2021-04-21 at 12 52 57 PM](https://user-images.githubusercontent.com/3939074/115759119-c1446f00-a354-11eb-8fb6-c26a279020f5.png)

**Proposal:**
Convert to LabeledButton


**Differences from frontend-shared button(s):**
Hover is red
Padding/Margin slightly different
No color transition on hover



### CanvasOAuth2RedirectErrror :: Dialog


![Screen Shot 2021-04-21 at 12 59 09 PM](https://user-images.githubusercontent.com/3939074/115759299-f224a400-a354-11eb-9110-ca297dcf0b40.png)


![Apr-21-2021 13-22-13](https://user-images.githubusercontent.com/3939074/115759320-f8b31b80-a354-11eb-85f6-e72275adf00e.gif)


This does not use the Dialog default button, but instead passes in a custom Button that more or less looks the same. We could probably do away with the custom button and just allow the default cancel button to close the dialog. Additionally, using the Dialog’s cancel will also render a secondary “X” button which is also missing from this component.



**Proposal:**
Convert to a LabeledButton(primary variant) for “Try again”
Convert to a LabeledButton for “Close”


**Differences from frontend-shared button(s):**
Hover has red text and/or background
Padding/Margin slightly different
No color transition on hover



### URLPIcker :: Dialog


![Apr-21-2021 13-34-25](https://user-images.githubusercontent.com/3939074/115759983-b76f3b80-a355-11eb-92ab-2a4a16023f58.gif)


**Proposal:**
Replace the “Submit” button with LabeledButton(primary variant)
Replace the “Cancel” button with a LabeledButton. 
Replace the close “X” button with an IconButton

**Differences from frontend-shared button(s):**
Hover has red text and/or background
Padding/Margin slightly different
No color transition on hover
Font size for “X” icon button is a bit large (19px) and font-weight is lower



### LMSFilePIcker :: Dialog


![Screen Shot 2021-04-21 at 1 40 24 PM](https://user-images.githubusercontent.com/3939074/115760081-cc4bcf00-a355-11eb-8f5e-4bdf05335d95.png)


**Proposal:**
Replace the “Select” button with LabeledButton(primary variant)
Replace the built in Cancel button with a LabeledButton. 
Replace the close “X” button with an IconButton

**Differences from frontend-shared button(s):**
Hover has red text and/or background
Padding/Margin slightly different
No color transition on hover
Font size for “X” icon button is a bit large (19px) and font-weight is lower



### SubmitGradeForm :: StudentSelector

![Apr-21-2021 14-50-02](https://user-images.githubusercontent.com/3939074/115760122-d66dcd80-a355-11eb-8847-4e071f57d857.gif)


The student left and right selection buttons are constructed out of custom HTML buttons.  We can probably convert these to IconButton albeit with some styling overrides specific to the grading bar. More on that below...



### SubmitGradeForm :: StudentSelector (continued)


The submit button is similar to the left/right buttons in that it is customized specifically to match the style of the grader bar. Replacing this with a LabeledButton with a left-aligned icon makes sense. One issue will be that the new shared buttons are very light and so if we are going to continue to have matching adjacent border colors, then they will be just too faint. 

There may be some experimentation with implementing the LabeledButton with custom css overrides to see what looks best. This pattern may end up lookin very similar if not identical to the InputButton in the client. If that’s the case, it may benefit us to bring that up into the shared package. 


![Screen Shot 2021-04-21 at 3 18 05 PM](https://user-images.githubusercontent.com/3939074/115760168-e4235300-a355-11eb-999e-4f683a4e9421.png)


Another option could be to style the button with a primary variant so they show up dark. Then use that same dark color as the border for the adjacent input elements. This may be a bit too high contrast, but it’s still an option to consider.

![Screen Shot 2021-04-21 at 3 14 09 PM](https://user-images.githubusercontent.com/3939074/115760188-eb4a6100-a355-11eb-9e79-68fb8c573c50.png)


A third option could be to go in a different direction and no longer render the buttons adjacent at all and instead just use standalone LabeledButton with no modifications and have margin between them and any respective inputs.  



### SubmitGradeForm :: ValidationMessage


While not an “button”, this is an input type=”button” and does have a click behavior. This is a custom component specific to the LMS grader but worth mentioning to see if we want to continue using this here or even outside of the grader. I would not recommend converting this to any of the shared buttons at this time.

![Screen Shot 2021-04-21 at 3 23 07 PM](https://user-images.githubusercontent.com/3939074/115760245-fac9aa00-a355-11eb-969e-3a1c606b70c7.png)


_There are several other error dialogs not covered, but use the same Dialog code path and so the above proposed changes would cover them too._

**Comment by lyzadanger** [comment]
This is done in all places except for the grading controls, which are covered by https://github.com/hypothesis/lms/issues/3292
