### ISSUE TITLE
User identity should be passed to Hypothesis from LMS

### ISSUE THREAD

**Issue by fishfree** [hypothesis/lms#274]
I set up Moodle & Hypothes.is, but when I started to annotate, it required me to login in first. The user identity from Moodle had not been passed to Hypothes.is.

**Comment by klemay** [comment]
Hi @fishfree we're actually working on automatic account and group creation for the next version of our app. For now, you and students will need to create and log in to Hypothesis accounts in order to use Hypothesis in the LMS.

**Comment by fishfree** [comment]
@klemay Sounds great!
