### ISSUE TITLE
Hypothesis LMS app should appear in LTI app store

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#277]
It would be great if the LMS app appeared in the LTI app store here:

https://www.eduappcenter.com/

Then teachers could discover our app and install it themselves. Also, the app center appears inside the LMS when installing an app. Sometimes schools control who is whitelisted here for visibility by instructors. 

Possible complications:

1) Would instructors be able to install the app with the Canvas picker piece in Canvas since that requires a dev key?
2) Does the provisioning piece of the app require a dev key?
3) Would the gradebook piece require a dev key?

**Comment by jeremydean** [comment]
I have created a Google doc where I'm filling out the form we would need to submit for this:

https://docs.google.com/document/d/1ilgisOCom7ZBjYfi_PE3johemBlRJtNXvTmrj_syQKc/edit?usp=sharing

There are a few technical questions that I could use help with.

**Comment by seanh** [comment]
Closing this as it's being tracked here https://github.com/hypothesis/lms/issues/725
