### ISSUE TITLE
Provide basic wireframes for VitalSource configuration flow

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#2862]
Part of #2861

The current plan is to implement a VitalSource content selection assignment configuration workflow that involves the instructor:

* Selecting the VitalSource content option from the presented content options (buttons)
* Pasting a link to a VitalSource book
* Selecting a chapter from that book

To make sure we're all talking about the same thing here, it would be good to provide some basic (very basic!) wireframes of this flow.

**Comment by lyzadanger** [comment]
Here are a few quick-prototyped UI states for the “select a VitalSource book” assignment-configuration workflow. 

The steps for configuring an assignment to use a VitalSource book chapter are:

1. *Select the VitalSource content option*. This has already been implemented:
![4C33A0B4-5F18-440E-9CEC-8C710728F9E8](https://user-images.githubusercontent.com/439947/123099083-d5155b80-d3ff-11eb-9b5b-68a4bca822f6.png)

2. *Enter a URL to select a VitalSource book*. The prototype implemented this as a “select a book from a list of books”, but we need to implement it as “enter a URL to find a book”. **This is what these wireframes pertain to.**
3. *Select a chapter within the selected book*. This UI has already been implemented, though could use some tuning:
![17C47C30-A5A6-4B06-9A1E-072611B2A716](https://user-images.githubusercontent.com/439947/123099113-df375a00-d3ff-11eb-9de8-7c2d05d3dd55.png)


### State 1: starting point of book selection

Note that these were prototyped in the current Pattern Library and reflect common, consolidated patterns for panels, dialogs and other patterns. Actual implementation may vary, as those common components and patterns are not yet in use in the LMS project. These are meant to be viewed in a wireframe fidelity context.

The starting point here is after an instructor has clicked the _Select book from VitalSource_ content option from the set of presented content options (buttons).

<img width="720" alt="Screen Shot 2021-06-23 at 8 28 39 AM" src="https://user-images.githubusercontent.com/439947/123099158-eb231c00-d3ff-11eb-8787-72583622662f.png">

* The dialog title is based on the “Enter URL” dialog title for the “Enter URL of web page or PDF” content option. It may not be ideal.
* The explanatory text is placeholder only here; we need to provide clearer directions.
* Input is focused when dialog opened
* Note that the “Select” button is disabled as a valid book has not been identified yet
* As I’m looking at this, I’m wondering if we should provide an option for the user to paste a URL _or_ a VBID. 

### State 2: happy path

User has entered a URL from which we were able to extract a VBID and get a valid response from VS' API.

<img width="697" alt="Screen Shot 2021-06-23 at 8 28 50 AM" src="https://user-images.githubusercontent.com/439947/123099212-faa26500-d3ff-11eb-99ab-fef610890c93.png">

* Specific design note: Checkmark is from existing icon set; green color is our “success” color that we haven’t used in many places yet (it’s used in “toast messages” in the client).
* Metadata here based on response from metadata variant of [GET v4/products/:vbid - Title, TOC, Metadata – VitalSource Developer Network](https://developer.vitalsource.com/hc/en-us/articles/360010967153-GET-v4-products-vbid-Title-TOC-Metadata)
* “Select” button is now enabled

### State 3: Sad path

This is a stub of what a sad path could look like. There are multiple sad paths to accommodate: URL is invalid, URL doesn't contain anything that looks like a VBID, the URL contained a VBID but we couldn't get book information for it...

<img width="697" alt="Screen Shot 2021-06-23 at 8 28 55 AM" src="https://user-images.githubusercontent.com/439947/123099265-0857ea80-d400-11eb-80ef-97b3f6a847a5.png">

* The error message and input styling are new patterns; the `x` icon is from our icon set (“cancel”). The red is our “error” color.
* The line height/typography on the error message itself is gross (we need typography patterns!). I would tune it in actual implementation.

_Note_ These wireframes do not represent the “loading” state (user has entered a book URL; we are sending a request to the VitalSource API…)

**Comment by robertknight** [comment]
In almost all cases we expect the user to perform a very specific workflow of opening the VitalSource book reader, opening the book, copying a link and pasting it here. On that basis I think it might be better to use the text "Paste a link". This is a little different to the "Create assignment from URL" workflow where the user might have gotten the link from many sources, and maybe even by typing it manually.

In modern browsers I think it should be possible to add a button that actually pastes the link, saving the user the need to focus the input field and then click Edit => Paste. This is probably a bonus feature though.

**Comment by robertknight** [comment]
Is the arrow to the right of the input field there to trigger the book lookup? I think we could do that automatically as soon as there is a link in the field. Since we don't expect the user to be typing the link in manually we don't have to worry too much about presenting an error before they have finished typing.

**Comment by lyzadanger** [comment]
> Is the arrow to the right of the input field there to trigger the book lookup? I think we could do that automatically as soon as there is a link in the field.

I intended it as a sort of placebo to indicate that there's an action to take on the field. I intend that we'd wire up both: looking things up on change and on button click. Does that sound OK?

**Comment by lyzadanger** [comment]
> On that basis I think it might be better to use the text "Paste a link".

Good feedback! This does indeed sound more intuitive.

**Comment by dwhly** [comment]
> As I’m looking at this, I’m wondering if we should provide an option for the user to paste a URL or a VBID.

I noticed this comment originally, but then it disappeared. :)

It felt like a good idea... I'm wondering if there are cases in which the ID is what the teacher might have handy, and whether we should allow for it so that they don't have to go separately hunting for it.  (Also wondering whether or in which cases the VBID maps to an ISBN  like ... here? https://msstate.bncollege.com/shop/BNCB_TextbookDetailView?storeId=10058&productId=600011422964&urlRequestType=Base&item=N&langId=-1&catalogId=10001)

2nd thought:  I think I've seen that a bookshelf URL can link to a specific chapter.  In that case, would we skip the chapter selection step?

**Comment by robertknight** [comment]
> Does that sound OK?

OK.

> 2nd thought: I think I've seen that a bookshelf URL can link to a specific chapter. In that case, would we skip the chapter selection step?

Bookshelf URLs generally point to wherever the reader is in the book. That may or may not be the chapter they want to use for the assignment. We could preselect the matching chapter in the next step, but I think we'd want confirmation from the user.

**Comment by lyzadanger** [comment]
I believe we have a clear enough direction to move forward at this point. Closing this issue, but it can be reopened as needed.
