### ISSUE TITLE
Don't store group pubids in the LMS app's database

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#287]
Related to but not exactly the same thing as https://github.com/hypothesis/lms/issues/253

The LMS app needs a group create or upsert API in h where the group to be created (if it doesn't already exist) is identified by a unique ID **that is provided by the LMS app**, not the pubid generated by h that is currently used. This ID needs to be something that the LMS app can re-compute deterministically based on the LTI launch params from the LMS (for example by taking a SHA-1 of the `tool_consumer_instance_guid` and `context_id` launch params).

This would mean that the LMS app would no longer need to keep a record of which groups have already been created in h by saving their pubids in its own DB.

This is how creating users already works in the LMS app -- `username` is a SHA-1 of some LTI launch params and no h user data is copied to the LMS app's DB.

This is needed for groups as well because keeping a copy of group pubids in the LMS app's DB introduces a new class of errors:

1. If a group for the Canvas course exists in h but does not exist in the LMS app, then the app will create a second group for the same course. Users may be members of both groups, in which case they will see what appears to be the same group twice in the client. Previously created course annotations will be in the first copy of the group. Newer annotations may go into either group -- depends what the user selects in the menu. Other uses may be members of the new group only and will be unable to join the old one.

2. If a group exists in the LMS app but doesn't exist in the h DB then the LMS app will crash.

There are actually three DBs, not two, that need to be kept in sync: The QA LMS DB, production LMS DB, and production h DB.

Both kinds of sync issues do occur (they've occurred the last two times I tried to deploy new LMS app features related to groups).

Both issues can only be fixed by manually hacking the h and LMS production databases to re-sync them.

It's very time consuming and confusing and I don't think it would be tenable to have developers other than me deploying the LMS app while these problems exist.

The only reason why I've been able to fix these issues so far is that the provisioning features are only being used by us for testing, so there are few groups involved and the groups don't contain any annotations that matter. You can simply delete the groups (and the group memberships, and the copies of the groups in both LMS DBs) and allow the app to re-create them correctly. This will not be possible once the app is being used by real users and one of these issues happens -- there will be a lot more groups and we won't be able to delete them and lose their memberships and annotations. An actual in-place merge will be necessary.

User data loss is a real possibility.

**Comment by lyzadanger** [comment]
Dev TODO list for backend/API changes (a.k.a. "the UPSERT endpoint):

- [x] The new group identifier field needs to be added:
	- [x] migration
	- [x] model
	- [x] ~comparator—similar to `userid`~
- [x] Need a new role for forwarded users to be used to protect the UPSERT endpoint
- [x] Need a service for fetching groups (this does not presently exist), modeled after the user service `fetch`:
	- [x] Make group traversal’s `__getitem__` use service instead of model query
	- [x] Can take either a `pubid` or a `groupid`
- [x] We need a service to update an existing group
	- [x] The group service may need to be broken into multiple services; it’s getting huge
- [ ] Update `group_create` service to be able to set the new identifier field
- [ ] JSON representation of group needs to include identifier
	- [ ] update the presenter
	- [ ] update API docs to indicate this field exists
- [ ] Add new field to group API schema
	- [ ] logic in schema or in the consuming view will need to validate that only third-party authorities may set this field (else HTTP 400/ValidationError)
	- [ ] Validate that `POST` endpoint correctly supports new field
	- [ ] Update API docs
- [ ] Create UPSERT (`PUT /api/groups/{id}`)endpoint :
	- [ ] View logic:
		- [ ] validate payload against create schema
		- [ ] try to fetch group
			- [ ] If exists, update
			- [ ] If not, create
- [ ] Update admin-groups view
	- [ ] Use update service instead of updating group models directly
	- [ ] Evaluate: Adding identifier field to admin form (however, recall that this field doesn’t mean anything for first-party groups)
