### ISSUE TITLE
Provisioning features should be opt-out, not opt-in

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#288]
At a point in the near future, we'll want to by-default enable provisioning features in newly-installed Hypothesis LMS applications. Thus, we'll need to swap the way we're enabling the feature for an explicit opt-in based on the installed-app's key to an opt-out mechanism.

**Comment by seanh** [comment]
Notes on deploying this:

* The blacklist should be added as a new envvar, not reusing the existing envvar.
* Add the new blacklist envvars, with the correct lists of blacklisted consumer keys, to the QA and prod environments _before_ deploying the code. And leave the old whitelist envvar present, so both envvars will be present at once.
* Deploy the code that changes from whitelist logic based on the old whitelist envvar to blacklist logic using the new blacklist envvar
* Once the code is deployed all the way out to prod and tested, the old whitelist envvar can be safely removed

This should ensure that there's no temporary "glitch" where instances that should not have the feature do have it, or vice-versa.
