### ISSUE TITLE
Don't show other course groups in dropdown  

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#294]
As I understand it, we're planning to include other courses/groups in the groups dropdown besides the course/group that the user is annotating in. That is, if Jeremy is annotating a doc in the h group English 101 in a Canvas course of the same name, the H sidebar would show Biology 101 and any other course I'm active in that are also using H in the groups dropdown, even if that's not the course I'm currently in. 

I don't think we should do this because it could lead to students accidentally annotating in the Bio 101 group on an Eng 101 document. Annotating in the wrong group is one of the top user mistakes we see with H in the classroom. Additionally, I can't think of any reason what I'd want to annotate in a different group than the course I'm in. It'd be different if the group dropdown menu was a pathway to activity in another group, but it's not in third party accounts.

CC @lyzadanger @seanh @ajpeddakotla

**Comment by seanh** [comment]
Right -- all of the other groups would be empty (no annotations) unless the user was a member of two different courses that contained assignments for annotating the same document, which seems unlikely. (Or if someone had accidentally annotated in the wrong group.)

**Comment by ajpeddakotla** [comment]
I agree with the approach @jeremydean has outlined. 

As a student using Hypothesis within the LMS, there is no need for students to navigate between groups using the groups drop down menu. 

At best having the group drop down menu present will only confuse students and persist the main issue that is there currently, which is that students will annotate in the wrong group. 

Removing other groups from the menu and leaving the menu empty makes no sense either, as the student will still be able to click on it and see what looks like a broken piece of UI. 

I would vote to remove the groups drop down menu from client for the LMS app.

**Comment by dwhly** [comment]
> I would vote to remove the groups drop down menu from client for the LMS app.

A note that we already have an example of a situation in which there's only one group, and no ability to leave it.  Here:

<img width="442" alt="screen shot 2018-10-18 at 2 28 41 pm" src="https://user-images.githubusercontent.com/1413074/47186158-82955000-d2e4-11e8-98d8-d81326e72de6.png">

*Whatever we do*, presumably we can just keep the same pattern in an equivalent situation?  (Argument for consistency).

Note: if we're going to be adding functionality to view activity pages for 3rd party groups (or create private groups for 3rd party implementations), we'd most likely make it available through the groups control.  So we'd need to re-add the control back later if we took it out.  

Regardless of what we do (cc @dwolfe) we might break changes/rethinking the UX as a separate card, which shouldn't block us from the intent of this card which is simply "don't show any other groups".

**Comment by lyzadanger** [comment]
@dwhly My recommendation for at least the short term would be that we only disable the groups menu in the LMS context. We can absolutely do that (and it won't affect the current eLife experience).

**Comment by dwolfe** [comment]
Reading through this now, I think we should disable the menu. I take the consistency argument very seriously, but in this case I think we shouldn't show it in either LMS or the eLIFE instances. For LMS, switching groups would essentially put any annotations created there in a broken state, which ideally we shouldn't allow. For eLIFE, we're showing a control that doesn't (and can't) change anything, which wastes time, attention, and trust in the case of a user who clicks it out of curiosity; and potentially causes frustration in the case of a user who expects to be able to switch groups. So I think the pattern (active control with no possible, valid actions) is actually broken in both places.

Agree that this is part of a larger conversation about the groups menu generally, and that we'll need to do that work sooner rather than later; but for now, I think removing the menu is not only the most expedient solution, I also think it's better UX. Do we have an issue already created for a design spike to tackle this? Maybe as part of activity pages for third party groups?

**Comment by dwhly** [comment]
> Reading through this now, I think we should disable the menu

Great.  So we're saying for *this* card, we'll limit groups to one for LMS, and *also* create a design card for the larger UX work (together with potentially other group control UX work) which we would prioritize it along with everything else?

**Comment by lyzadanger** [comment]
@dwhly 

> So we're saying for this card, we'll limit groups to one for LMS

Assuming "limit groups to one for LMS" == disable drop-down menu and make the (single) active group a static header element (no "menu" caret)?

**Comment by dwolfe** [comment]
> Assuming "limit groups to one for LMS" == disable drop-down menu and make the (single) active group a static header element (no "menu" caret)?

That's my recommendation.

>also create a design card for the larger UX work (together with potentially other group control UX work) which we would prioritize it along with everything else?

Yep, I'll create one now.

**Comment by seanh** [comment]
Closing this because we've decided to do <https://github.com/hypothesis/product-backlog/issues/868> instead.
