### ISSUE TITLE
App with provisioning fails to launch in Blackboard

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#295]
Installing the new app and getting @seanh to authorize the installation for provisioning, the app fails at the point when it should display a PDF or URL with H added. Everything works smoothly until one is asked to select URL or PDF. The failure occurs upon hitting save after selection. 

This is the message in the console:

![image](https://user-images.githubusercontent.com/3261902/47177222-78238800-d2dd-11e8-9a6f-f68c21b72c16.png)

I'm finding this to be the case in both instances we have for testing things in BB:

I have also tried this and gotten the same result in another BB testing instance here:

https://www.coursesites.com

https://preview-learn.blackboard.com/ultra/courses/_244252_1/cl/outline

Credentials for both instances can be found here:

https://docs.google.com/document/d/1p7XiZclKWDlkOxlcuHXdkrsGtemGeR5gQiJ4qUq7o00/edit?usp=sharing

**Comment by jeremydean** [comment]
I have also tried this and gotten the same result in another BB testing instance here:

https://www.coursesites.com

Credentials for both instances can be found here:

https://docs.google.com/document/d/1p7XiZclKWDlkOxlcuHXdkrsGtemGeR5gQiJ4qUq7o00/edit?usp=sharing

**Comment by jeremydean** [comment]
When installing the tool I cam given the option of filling in custom parameters:

![image](https://user-images.githubusercontent.com/3261902/47726300-36bda180-dc28-11e8-8a5d-5aa8900399d4.png)

**Comment by seanh** [comment]
I think everything is working in both original and new Blackboard Learn now
