### ISSUE TITLE
App with provisioning fails to launch in Moodle

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#296]
Unlike in Blackboard (see [295](https://github.com/hypothesis/lms/issues/295)) when the app fails AFTER selection of a document for annotation, the app fails in Moodle BEFORE selection of resource from Google Picker (PDF) or Web (URL).

This is the error I received:

![image](https://user-images.githubusercontent.com/3261902/47725536-bfd3d900-dc26-11e8-9eca-edc05092ce70.png)

And this is what the console said:

>Failed to load resource: the server responded with a status of 504 ()

Moodle course can be accessed here:

https://hypothesisuniversity.moodlecloud.com/course/view.php?id=4

Credentials are here:

https://docs.google.com/document/d/1p7XiZclKWDlkOxlcuHXdkrsGtemGeR5gQiJ4qUq7o00/edit?usp=sharing

**Comment by jeremydean** [comment]
Note, as in BB, there is a space when installing the tool to add "Custom parameters" in addition to some other privacy settings related to LTI params. This is how I configured it on the most recent test:

![image](https://user-images.githubusercontent.com/3261902/47725442-931fc180-dc26-11e8-8544-e09e0cb283ba.png)

This is the error I received:

![image](https://user-images.githubusercontent.com/3261902/47725536-bfd3d900-dc26-11e8-9eca-edc05092ce70.png)

And this is what the console said:

>Failed to load resource: the server responded with a status of 504 ()

**Comment by robertknight** [comment]
I tested the "Hypothesis with provisioning" exercise here: https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=25

And with the current lms prod app it appears to be working:

<img width="1028" alt="hypothesis lms app in moodle" src="https://user-images.githubusercontent.com/2458/49388222-6bd37d00-f71b-11e8-9702-67d8f0167c0b.png">

**Comment by robertknight** [comment]
I've tested all the existing exercises in our test Moodle instance under the "Hypothesis with provisioning" and "Hypothesis without provisioning" courses. They all worked as expected. I'm going to close this now, but feel free to do any additional testing you want to and re-open if you find a problem.
