### ISSUE TITLE
Remove "API call failed" from error dialogs

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#2997]
Slack thread: https://hypothes-is.slack.com/archives/C1M8NH76X/p1626949395014200

### Problem

Log in to <https://hypothesis.instructure.com/> as an instructor and launch [localhost (make devdata) Canvas Files Assignment Whose File Has Been Deleted](https://hypothesis.instructure.com/courses/125/assignments/1370). You'll see this error dialog:

![Screenshot from 2021-07-22 11-19-37](https://user-images.githubusercontent.com/22498/126631592-f2bb10a9-040c-4410-8523-5bfdf65ee43e.png)

The "API call failed" string isn't supposed to be there:

* "API call failed" is a technical detail that doesn't belong in the title or body of our user friendly error dialogs. Technical details belong in the _Error Details_ section
* The string is in a non-sensical location in the error dialog
* The string doesn't add any useful information on top of what the error dialog says

Note that the problem isn't related to just this one error dialog. I think "API call failed" has been added to an entire class or classes of dialog.

### Solution

Just remove "API call failed" from all error dialogs, it's not useful.

**Comment by marcospri** [comment]
I think a similar behavior happens on the "missing canvas copes" dialog, which we know what the error is but we show: `An unknown error occurred`
![Screenshot from 2021-08-17 13-28-14](https://user-images.githubusercontent.com/1433832/129718450-c628a747-b0d8-46d4-88c1-043fc5d6ce0a.png)

**Comment by lyzadanger** [comment]
> Note that the problem isn't related to just this one error dialog. I think "API call failed" has been added to an entire class or classes of dialog.

Specifically, it's what's rendered if `APIError`'s constructor's `data` parameter lacks a `message` property.

https://github.com/hypothesis/lms/blob/2c983af3550171e5de5d7e4d045ea7c306178e62/lms/static/scripts/frontend_apps/utils/api.js#L5-L52

**Comment by lyzadanger** [comment]
> I think a similar behavior happens on the "missing canvas copes" dialog, which we know what the error is but we show: An unknown error occurred

@marcospri Yep, this appears to be fallback behavior of `ErrorDialogApp`, which it looks like you authored in the recent past: https://github.com/hypothesis/lms/commits/master/lms/static/scripts/frontend_apps/components/ErrorDialogApp.js

It sounds like the idea here is: If we don't have anything useful to show, just don't show anything :). i.e. default error messages should be empty. I think that's certainly doable.

**Comment by marcospri** [comment]
> It sounds like the idea here is: If we don't have anything useful to show, just don't show anything :). i.e. default error messages should be empty. I think that's certainly doable.

@lyzadanger Yup exactly :+1: , but I think that behaviour comes from https://github.com/hypothesis/lms/blob/2c983af3550171e5de5d7e4d045ea7c306178e62/lms/static/scripts/frontend_apps/components/ErrorDisplay.js not ErrorDialogApp (which happens to also use `ErrorDisplay` but is not involved on the missing scopes dialog). 

I think the trickiest (tedious-est?) part here might be making changes to ErrorDisplay and check how they affect different dialogs. I can help with that if needed
