### ISSUE TITLE
Investigate whether security updates to Google Drive URLs impact LMS:H file picker

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/lms#3024]
Only July 27, 2021, Google sent the following notice out: 
<img width="528" alt="Screen Shot 2021-07-30 at 8 57 04 AM" src="https://user-images.githubusercontent.com/7463523/127663798-79934b12-c982-4987-8dfe-41d44da181d1.png">

After asking if this is something we needed to worry about, @robertknight has done an initial investigation. His comments are below: 
Hello Arti,

It wasn't clear from the linked FAQ whether this would affect our usage of Google Drive or not. I did some tests with a file which has this update has already been applied and it still works in the LMS app. The change appears to have affected the URL that is used when sharing a link to a file, but has not the URL used when downloading a file, which is what the LMS's Google Drive integration relies on. I am unclear whether this is because Google hasn't finished making changes or because it doesn't affect these URLs.

It would be a good idea to try and contact Google to confirm whether download URLs for PDF files (eg. [3]) will be affected by this change.

Manual test notes:

On the Google Drive home page there is a banner at the top which links to a list of affected files in your Drive account. I tried creating a Google Drive assignment with one of the affected PDF files [1] in the LMS app and it still works. For this file, I can see that the sharing link has changed (an extra `resourcekey` query parameter has been added to the URL), but if you try to download the file within Google Drive, that URL ([3]) has not changed.

[1] https://drive.google.com/file/d/0Bx7aaYEfzIONNGtseEZVV3JBWEU/view?usp=sharing&resourcekey=0-TMgSyIxJsVVArstX-G4Kog - Note the `resourcekey` query param in the URL. This indicates that the URL has had the update applied.
[2] https://support.google.com/a/answer/10685032?hl=en
[3] https://drive.google.com/u/0/uc?id=0Bx7aaYEfzIONNGtseEZVV3JBWEU&export=download

Next steps: Do some more digging to determine if there are any impacts from this security update to our google file picker implementation.

**Comment by robertknight** [comment]
The LMS file picker now captures the `resourcekey` for newly created assignments. See https://github.com/hypothesis/lms/pull/3070. There is ongoing work to look into whether we can add it to existing assignments. See [this Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1630052369070600).

**Comment by seanh** [comment]
I think this spike is done. The TLDR is that some Google Drive assignments will be broken and there's a bunch of work that we need to do to ensure that they keep working. It's all been added to this project board: https://github.com/orgs/hypothesis/projects/49
