### ISSUE TITLE
How to deploy a production instance?

### ISSUE THREAD

**Issue by fishfree** [hypothesis/lms#3057]
I'd like to deploy a production instance with my own H instance, however, no detailed docs to follow. Any help would be appreciated very much!

**Comment by seanh** [comment]
Hi @fishfree, our dev mailing list would be a better place to ask for support: https://web.hypothes.is/developers/

I'm afraid the LMS app isn't really meant to be deployed by third-parties so this isn't something that's well supported by documentation. There is a `make docker` command that will build a Docker image that you can deploy. There are various environment variables you'd have to set, I'm afraid they're not well documented
