### ISSUE TITLE
Increase the size of Canvas iframes for assignment configuration

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#3113]
When configuring an assignment in the Canvas LMS, Hypothesis controls show up in a fairly dinky iframe. While we've adapted the Hypothesis-controlled interface elements to fit in such a small space, the fact remains that it is quite a small space, and UI that we cannot control—for example, the Google Drive picker—are nigh unusable:

![image](https://user-images.githubusercontent.com/439947/133431834-285f92e9-acf6-4d58-a789-1aeb5934db84.png)

It turns out that the sizing of this iframe is configurable using the `selection_height` and `selection_width` properties. This is documented:

* https://canvas.instructure.com/doc/api/file.lti_dev_key_config.html
* https://canvas.instructure.com/doc/api/file.content_item.html
* https://canvas.instructure.com/doc/api/file.tools_xml.html

As I understand it, if we changed this to a larger size, all existing installs would still have the tiny iframe (new installs would have more space). This creates a potential testing burden: we will need to make sure we test at both sizes (note that the Canvas iframe can be resized and dragged around once it's open, making this not a horrible burden) in the future. But I think it may well be worth it in terms of user comfort for future installs.

These settings would likely go here: https://github.com/hypothesis/lms/blob/28f158a9cb5edfaca254848581ed35edfbf5d242/lms/templates/config.xml.jinja2

**Comment by marcospri** [comment]
This is now possible see https://github.com/hypothesis/lms/pull/5260
