### ISSUE TITLE
Refresh icon not appearing in Canvas using LMS app

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#331]
The new annotations icon is not appearing in the sidebar when using the LMS app with provisioning. 

Reported by user in Canvas [here](https://hypothesis.zendesk.com/agent/tickets/3340) and confirmed by Jeremy in Canvas. Time was allowed for delayed appearance but only a hard refresh revealed new annotations.

I have confirmed that this issue is happening on all types of files: _URLs, Google PDFs, and Canvas PDFs_. 

I have confirmed that this is happening in the _production app without provisioning_ enabled as well.

I have confirmed the issue in Sakai as well.

Logged in as Provisioned teacher:

![image](https://user-images.githubusercontent.com/3261902/48437536-2ee11f80-e747-11e8-986f-e72316db03c7.png)

Logged in as Provisioned Student:

![image](https://user-images.githubusercontent.com/3261902/48437567-44564980-e747-11e8-8b6e-f7b3834bf6ea.png)

Not that reply in one is not showing in the other and new annotation in one is not showing in the other.

**Comment by klemay** [comment]
Note: this does appear to be isolated to the LMS environment. I was not able to reproduce while annotating a regular web page, or a PDF outside of the LMS environment.

**Comment by robertknight** [comment]
This was caused by https://github.com/hypothesis/h/issues/5406, which is now resolved.
