### ISSUE TITLE
Make `errorDetails` in `JSConfig` always be a dict

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3333]
The backend sometimes includes `errorDetails` in the `js-config` object that it sends to the frontend. For example [`enable_oauth2_redirect_error_mode()`](https://github.com/hypothesis/lms/blob/566cf7084773265314ebe46d51f17bd4510fa4e3/lms/resources/_js_config/__init__.py#L106-L146) does it:

https://github.com/hypothesis/lms/blob/566cf7084773265314ebe46d51f17bd4510fa4e3/lms/resources/_js_config/__init__.py#L142

[`enable_error_dialog_mode()`](https://github.com/hypothesis/lms/blob/566cf7084773265314ebe46d51f17bd4510fa4e3/lms/resources/_js_config/__init__.py#L148-L157) also does it:

https://github.com/hypothesis/lms/blob/566cf7084773265314ebe46d51f17bd4510fa4e3/lms/resources/_js_config/__init__.py#L154

`errorDetails` is an empty string by default. Sometimes we pass a non-empty string value for it:

https://github.com/hypothesis/lms/blob/52216dd7ddf878124c2bdd83c4c92718e7e2d45d/lms/views/api/canvas/authorize.py#L119

But at other times we pass a dict:

https://github.com/hypothesis/lms/blob/0bc9fb6fe553c344550a807837ad17867cdbc733/lms/views/exceptions.py#L55-L58

The `details` that the backend's API error responses sometimes contain (which the frontend shows in the same **Error Details** box that it uses for `errorDetails` from the `js-config`) is always a dict.

It would be good if `errorDetails` in `js-config` could always be a dict as well, and never a string, as this will make the frontend code easier.

**Comment by lyzadanger** [comment]
Looks like the missing scopes key error is returning its `errorDetails` as a string. This would likely format a little nicer if provided as an object, though again, the frontend can _cope_ with what it's doing presently:

![image](https://user-images.githubusercontent.com/439947/140172920-3ac461c7-8b6d-45a5-a069-604977992278.png)

**Comment by seanh** [comment]
Slack thread: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1635953166158600
