### ISSUE TITLE
Error dialog is broken when LTI Outcomes (grading) requests fail

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3352]
![Screenshot from 2021-11-08 14-00-37](https://user-images.githubusercontent.com/22498/140757931-914c6d8f-4af0-4c7a-b813-9a16a6f4a7ea.png)

Here's how it looks after expanding the **Error Details**:

![Screenshot from 2021-11-08 14-19-42](https://user-images.githubusercontent.com/22498/140758316-a9298781-6507-4f1e-a908-9bec09903ac4.png)

To reproduce it hack the code like so:

```diff
diff --git a/lms/services/lti_outcomes.py b/lms/services/lti_outcomes.py
index 51e1bda0..18bfcd3e 100644
--- a/lms/services/lti_outcomes.py
+++ b/lms/services/lti_outcomes.py
@@ -127,7 +127,7 @@ class LTIOutcomesClient:
         """Return the POX body element, checking for errors."""
 
         try:
-            body = data["imsx_POXEnvelopeResponse"]["imsx_POXBody"]
+            body = data["imsx_POXEnvelopeResponse"]["foo"]
             header = data["imsx_POXEnvelopeResponse"]["imsx_POXHeader"]
             status = header["imsx_POXResponseHeaderInfo"]["imsx_statusInfo"][
                 "imsx_codeMajor"
```

Then launch any Moodle assignment as a teacher and select a student from the grading bar. (You may have to launch the assignment as a student first, in order to get a student to appear in the grading bar.)

Here's the body of the backend's 400 error response to the `/api/lti/result` response looks like:

```json
{"message": "Malformed LTI outcome response", "details": {"request": {"method": null, "url": null}, "response": {"status_code": 200, "reason": "OK"}, "validation_errors": null}}
```

**Comment by lyzadanger** [comment]
Fortunately, this one should be easy to fix. There is a `white-space: nowrap` rule on `.SubmitGradeForm` that is causing this. If I disable this rule in my web inspector, things look correct. Of course will need to make sure that that rule _does_ still apply where it's needed, but this shouldn't be a hard fix.
