### ISSUE TITLE
Show file name after choosing a file from OneDrive or Sharepoint

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#3365]
In cases where Canvas groups are available (and presumably, in future, possibly Blackboard Groups), there is a "second step" to assignment configuration after selecting a file. If a OneDrive file is selected, it presently looks like this:

![image](https://user-images.githubusercontent.com/439947/141303473-1ad700a5-c1dd-4b51-87f8-ea2458dc73cd.png)

The URL presented here is not helpful to the user. We should show something more helpful, even if it's just static "A file from OneDrive" text (if we don't have any access to a filename or path).

## Scenario

:bust_in_silhouette: As an instructor, when I select a file in OneDrive or Sharepoint, I see the file's name in the Assignment content section. E.g., "H Developer Documentation.pdf."

**Comment by mattdricker** [comment]
Note that selecting PDF from Google Drive also presents similarly unhelpful URL.
<img width="805" alt="Screen Shot 2021-11-11 at 12 23 29 PM" src="https://user-images.githubusercontent.com/71603629/141342058-a2a340c6-4665-4aa9-bb04-dfb98ee5982e.png">
