### ISSUE TITLE
Clicking outside of the dialog box in the popup window closes the window

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3404]
When an error dialog is shown in the authorization popup window:

![Screenshot from 2021-11-17 12-29-18](https://user-images.githubusercontent.com/22498/142200847-be875e49-72eb-42bd-924a-b190224845b2.png)

Clicking anywhere outside of the dialog box (so anywhere in the darker coloured area) causes the popup window to close, which is confusing: it's confusing for a window to suddenly close when you click on it, especially since one reason to click on the window might be to focus / raise the window if it's not the currently focused window.

I suspect that this may have been implemented (who knows how long ago) because in other cases when these error dialogs are shown it makes sense for clicking outside to close them because closing the error dialog will reveal the other dialog beneath it?

Anyway, the dialog has a close button and also an x, so I don't think it's necessary for clicking-outside-the-dialog to also close it. I suggest just globally removing this behaviour.

### Reproducing

There's a "missing developer key scopes" test course with prod, QA and localhost assignments that will reproduce an error dialog in the popup window: https://hypothesis.instructure.com/courses/121/assignments/

**Comment by esanzgar** [comment]
Many UI framework allow modal to be closed by clicking outside the modal.

**Comment by lyzadanger** [comment]
Fixed by #5293
