### ISSUE TITLE
Handle potential need to re-authorize when re-fetching groups in (Blackboard) grading

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#3417]
We need to be able to re-fetch groups after initial launch without relaunching the sidebar (see #3416 ) in grading mode for assignments configured with Blackboard groups. There is a potential the related request(s) to our "sync API" will raise an authorization issue. This case is already handled in `BasicLTILaunchApp`'s `fetchGroups` callback; we'll need to account for it in the grading context as well. If we're able to re-use `BasicLTILaunchApp`'s `fetchGroups` for re-fetching groups in grading mode, then all the better as this work may already be "done."

**Comment by marcospri** [comment]
One way to replicate this would be something like:


```diff --git a/lms/views/api/blackboard/sync.py b/lms/views/api/blackboard/sync.py
index 0bd4b324..11b36391 100644
--- a/lms/views/api/blackboard/sync.py
+++ b/lms/views/api/blackboard/sync.py
@@ -81,6 +81,8 @@ class Sync:
 
         try:
             groups = self.blackboard_api.group_set_groups(course_id, group_set_id)
+            from lms.services import OAuth2TokenError
+            raise OAuth2TokenError()
         except ExternalRequestError as bb_api_error:
             if bb_api_error.status_code == 404:
                 raise BlackboardGroupSetNotFound(
```


This would be similar to the unlikely but possible scenario of successfully getting a token on the launch but it expiring a few ms later when the sync request arrives.

I'd say it's working as expected at the moment but can't tell where the error handling comes from.

**Comment by lyzadanger** [comment]
@marcospri 

Ah, yes, the error handling there is part of `BasicLTILaunchApp` (via `LaunchErrorDialog`) as the auth fail on sync is part of the front-end app launch before it "gets" to the grading "part" of things. 

What we're looking for is some way to raise an error on _subsequent_ calls to the sync API. In the grading case, this is when we ask for groups for a given student ID. This diff:

```diff
diff --git a/lms/views/api/blackboard/sync.py b/lms/views/api/blackboard/sync.py
index 0bd4b324..68f8813c 100644
--- a/lms/views/api/blackboard/sync.py
+++ b/lms/views/api/blackboard/sync.py
@@ -72,12 +72,8 @@ class Sync:
             return groups

         if grading_student_id := self.request.parsed_params.get("gradingStudentId"):
-            return self.grouping_service.get_course_groupings_for_user(
-                course,
-                grading_student_id,
-                type_=Grouping.Type.BLACKBOARD_GROUP,
-                group_set_id=group_set_id,
-            )
+            from lms.services import OAuth2TokenError
+            raise OAuth2TokenError()

         try:
             groups = self.blackboard_api.group_set_groups(course_id, group_set_id)
```

May be more like it? This particular situation might be impossible, but it demonstrates the "place" where errors could happen in the cases I'm trying to chase down. Could a "real" error ever arise here?

**Comment by marcospri** [comment]
> What we're looking for is some way to raise an error on subsequent calls to the sync API

If I remember correctly, while grading, switching back to "all students" doesn't re-query the sync api but uses the previously fetched group list?

If that's the case, no real "OAuth2TokenError" can't happen on that block (the `if grading_student_id :=` one).

That block, as is implemented now, doesn't talk to the BB API (so no auth errors could happen) and I can't think of any edge cases that could happen there (eg an empty group list, etc).

But if the goal is to tie together different error handling mechanism in the frontend you could simulate an error like that.
