### ISSUE TITLE
Handle error responses from Blackboard's "course group sets" API

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3473]
### Problem

If requests to Blackboard's "course group sets" API (the API that returns the list of group sets in the course) fail then our UI gets stuck in an "authorization" loop and fails to show any error message to the user or to log anything about the error to Papertrail or Sentry.

You can simulate a failure from the course group sets API like this:

```diff
diff --git a/lms/services/blackboard_api/client.py b/lms/services/blackboard_api/client.py
index e8acae7e..09c1b5a7 100644
--- a/lms/services/blackboard_api/client.py
+++ b/lms/services/blackboard_api/client.py
@@ -103,7 +103,7 @@ class BlackboardAPIClient:
     def course_group_sets(self, course_id):
         response = self._api.request(
             "GET",
-            f"/learn/api/public/v2/courses/uuid:{course_id}/groups/sets",
+            "/foo",
         )
 
         return BlackboardListGroupSetsSchema(response).parse()
```

Here's what happens:

https://user-images.githubusercontent.com/22498/144611650-3bc3266f-319f-4607-bbb3-71cd33ed8943.mp4

### Solution

It needs to:

- [x] Show the details of the failed request to the user
- [x] Show the details of the error response from Blackboard to the user
- [x] Give the user a way to <kbd>Try again</kbd>
- [x] Give the user a way to report the problem to Hypothesis if it persists
- [x] Give the user a way to <kbd>Cancel</kbd> and do something else (e.g. create a non-groups assignment instead)
- [x] Log the details of the failed request to Papertrail
- [x] Log the details of the error response from Blackboard to Papertrail
- [x] Report the details of the failed request to Sentry
- [x] Report the details of the error response from Blackboard to Sentry

For reference you can see how the above are handled for other API requests, for example when the Blackboard list files request fails:

```diff
diff --git a/lms/services/blackboard_api/client.py b/lms/services/blackboard_api/client.py
index e8acae7e..a4ed2cdd 100644
--- a/lms/services/blackboard_api/client.py
+++ b/lms/services/blackboard_api/client.py
@@ -57,7 +57,7 @@ class BlackboardAPIClient:
         results = []
 
         for _ in range(PAGINATION_MAX_REQUESTS):
-            response = self._api.request("GET", path)
+            response = self._api.request("GET", "/foo")
             results.extend(BlackboardListFilesSchema(response).parse())
             path = response.json().get("paging", {}).get("nextPage")
             if not path:
```

The user sees this:

![Screenshot from 2021-12-03 13-45-58](https://user-images.githubusercontent.com/22498/144612744-40a45f69-c212-4772-970d-d70240483b6c.png)

In Sentry we receive an event including this:

![Screenshot from 2021-12-03 13-48-18](https://user-images.githubusercontent.com/22498/144613085-7c229ea9-64c3-4d52-9d56-2b4e797d241b.png)

This is mostly implemented by [`ExternalRequestError`](https://github.com/hypothesis/lms/blob/72b7dd9e0eb60570936311c0cc6b1f8f224d2be4/lms/services/exceptions.py#L4-L91) and the [`external_request_error()` exception view](https://github.com/hypothesis/lms/blob/72b7dd9e0eb60570936311c0cc6b1f8f224d2be4/lms/views/api/exceptions.py#L105-L147).

**Comment by seanh** [comment]
I think the backend may already be doing the right thing here. The response from the backend's `group_sets` API is a 400 with:

```json
{"message": "External request failed", "details": {"request": {"method": "GET", "url": "https://aunltd-test.blackboard.com/foo"}, "response": {"status_code": 200, "reason": ""}, "validation_errors": {"_schema": ["response doesn't have a valid JSON body"]}}}
```

But the frontend isn't displaying the error dialog.

Although why does the backend seem to be saying that Blackboard responded with a 200? That might be something to do with how I've tried to simulate the error though.

**Comment by marcospri** [comment]
This behaves the same in Canvas groups. 

400s with a message result in a authorization loop instead of displaying the error to the user

```diff
diff --git a/lms/services/canvas_api/client.py b/lms/services/canvas_api/client.py
index c4e7d707..8ddd4002 100644
--- a/lms/services/canvas_api/client.py
+++ b/lms/services/canvas_api/client.py
@@ -292,7 +292,7 @@ class CanvasAPIClient:
     def course_group_categories(self, course_id):
         return self._client.send(
             "GET",
-            f"courses/{course_id}/group_categories",
+            f"courses/{course_id}/group_categoriess",
             schema=self._ListGroupCategories,
         )
```

**Comment by lyzadanger** [comment]
>  I think the backend may already be doing the right thing here.

It looks like the back-end is returning some language related to Canvas when there is a problem with fetching Blackboard groups; that's likely going to need to be updated:

```
{"message": "Calling the Canvas API failed", "details": {"request": {"method": "GET", "url": "https://aunltd-test.blackboard.com/api/v1/courses/None/group_categories"}, "response": {"status_code": 200, "reason": ""}, "validation_errors": {"_schema": ["response doesn't have a valid JSON body"]}}}
```

I get the above response body if I hack the `blackboard_api/client` as demonstrated in the PR description.

**Comment by marcospri** [comment]
> > I think the backend may already be doing the right thing here.
> 
> It looks like the back-end is returning some language related to Canvas when there is a problem with fetching Blackboard groups; that's likely going to need to be updated:
> 
> ```
> {"message": "Calling the Canvas API failed", "details": {"request": {"method": "GET", "url": "https://aunltd-test.blackboard.com/api/v1/courses/None/group_categories"}, "response": {"status_code": 200, "reason": ""}, "validation_errors": {"_schema": ["response doesn't have a valid JSON body"]}}}
> ```
> 
> I get the above response body if I hack the `blackboard_api/client` as demonstrated in the PR description.

@lyzadanger  I think the canvas wording here comes from possibly having both canvas & blackboard groups enabled locally in `Hypothesis14af0fe87c9deb2e461f88be4a8d5364` which we should tackle but probably in a different issue.
