### ISSUE TITLE
Handle Blackboard Groups assignments whose group set no longer exists

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3479]
There's a **localhost (make devdata) Groups Assignment Whose Group Set Has Been Deleted** test assignment for this. Needs to show a specific "group set has been deleted" error dialog.

**Comment by marcospri** [comment]
Not sure about this one. We can use a 404 to check for this case but that seems happen in other situations like:

https://hypothes-is.slack.com/archives/C4K6M7P5E/p1639385430121500?thread_ts=1639157257.110600&cid=C4K6M7P5E
