### ISSUE TITLE
Google Picker is broken in Blackboard when the provisioning feature is enabled

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#350]

**Comment by seanh** [comment]
Hmm, actually I'm seeing Google Picker problems in Blackboard both with and without the provisioning feature. It may differ between original and new Blackboard

**Comment by seanh** [comment]
We're unable to debug this without access to a Blackboard Learn instance that we have an admin account on. Marking as blocked for now

**Comment by seanh** [comment]
Some clues in this Slack thread: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1542899352076800

**Comment by robertknight** [comment]
It looks like there is a problem with `window.DEFAULT_SETTINGS.lmsUrl` configuration value that comes from the Python app. This is used to [configure the Google File Picker](https://github.com/hypothesis/lms/blob/ca3651b8438232e7f2e0a8a65eabfc8b3e722c32/lms/static/scripts/content-item-selection.js#L149). It should be the URL of the top-level frame, which is https://preview-learn.blackboard.com/ when using the test site at https://new.coursesites.com/index.html and logging in as jeremydean, but instead this value is set to the invalid URL https://webapps/portal/frameset.jsp?url=%2Fwebapps%2Fblackboard%2Fexecute%2Flauncher%3Ftype%3DCourse%26id%3D_505296_1%26url%3D.

If I manually fix this key before clicking the Google file picker button, the file picker works.

**Comment by seanh** [comment]
Spoke too soon, Rob found the solution and we fixed it. Worth knowing though that a user can enter an invalid URL on the `/welcome` page and everything will appear to work fine, except that Google Picker will break. I created a separate issue for that: 9f46c29e611c558cc147dbad40151444297690ac18a4443513fcab0a2b0e9a39b01796efbc43f5b33c41085189d7c19141777242af5592318d56bf58982672fe
