### ISSUE TITLE
Record `GroupingMembership`'s for all groupings

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3640]
Apparently [we only record `GroupingMembership`'s in the DB for Blackboard groups](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1643811404185479?thread_ts=1643808229.962529&cid=C1MA4E9B9). We should record these for courses, Canvas groups and Canvas sections as well.

**Comment by marcospri** [comment]
Depending on https://github.com/hypothesis/private-issues/issues/65#issuecomment-1028506873 we have to decide if for instructors we want to store only strict membership (ie a teacher himself belongs to a section). 

We don't query this information at the moment. We query membership for students but we try to get all the relevant groups/sections the teachers can see.

For canvas groups for example it doesn't seem possible to add instructors to group sets.

**Comment by marcospri** [comment]
We store memberships for:

- Students in canvas groups
- Students in canvas sections
- Students in blackboard groups

We don't currently store memberships for teachers in those and for anybody when there's no group/sections involved, ie for top level courses.
