### ISSUE TITLE
Don't send simultaneous OAuth refresh requests for the same user

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#3667]
# Problem

See https://github.com/hypothesis/product-backlog/issues/1230 for the original bug report and how to reproduce the issue locally.

Slack threads:

* <https://hypothes-is.slack.com/archives/C1MA4E9B9/p1644342948547379>
* <https://hypothes-is.slack.com/archives/C4K6M7P5E/p1644338894692669>
* <https://hypothes-is.slack.com/archives/C1MA4E9B9/p1644405136981779>
* <https://hypothes-is.slack.com/archives/C4K6M7P5E/p1644416393843629>

Our backend's API handles OAuth 2 refresh requests in a way that is transparent to the frontend:

1. The frontend sends a request to the backend's API. For example this might be a `/api/canvas/assignments/{resource_link_id}/via_url` request, which requests a public Via URL for the identified Canvas Files assignment.
2. The backend receives this request and sends a request on to the Canvas API's public URL endpoint
3. The backend receives an error response from Canvas indicating that our access token for this user has expired
4. The backend sends a refresh token request to Canvas and gets a new access token
5. The backend re-sends the original request to Canvas's public URL endpoint and this time gets a successful response
6. The backend returns the public Via URL to the frontend

So the frontend just received a successful response from the backend (after some waiting) and is blissfully unaware that a token refresh had to happen.

This solution worked great until the frontend started sending multiple requests to the backend in parallel. For example one request for a public Via URL for the assignment's PDF file and another request to the "sync API" that returns the list of groups to show for this user. The two requests from the frontend cause the backend to send _two_ refresh requests to Canvas at the same time:

1. Request A sends a refresh request to Canvas
2. Request B sends a refresh request to Canvas
3. Request A receives a refreshed access token from Canvas
4. Canvas receives request B's refresh request and invalidates the refreshed access token that it just send to request A
5. Request A re-tries its original Canvas API request using its now-invalided refreshed access token, and gets an error
6. Request A sends an authorization error back to the frontend
7. The frontend shows the "You need to re-authorize" dialog to the user

Request B will have succeeded and will most likely have stored a refreshed, working access token in the DB (although there are race conditions here) but it doesn't matter: if _either_ of the requests fails then the frontend shows the authorization dialog.

# Potential Solutions

One way or another we need to coordinate only sending one refresh request at a time for a given user.

## Solution 1: Have the frontend coordinate refresh requests

Our backend already has an authorization error response that causes the frontend to start a user-facing authorization flow. This authorization error response is used when we don't have an access token for the user or when refreshing an access token fails (e.g. if the refresh token has been expired, or if the access token has been revoked).

We could:

1. Remove the automatic "refresh-and-retry" behaviour from the backend's API code. If the backend gets an error from the Canvas API it will immediately send an authorization error to the frontend, without trying to refresh the access token first.
2. Add a new "refresh this user's access token" API. This is a new separate API endpoint that the frontend would call in order to get the backend to attempt a refresh request with Canvas.
3. Currently when the frontend receives an authorization error from the backend it starts the user-facing authorization flow. Instead, on receiving an authorization error the frontend should:
   1. Send a "refresh this user's access token" request to the backend
   2. If the request gets a successful response, then the frontend should re-try the originally failed request(s)
   3. If the request does not get a successful response or if re-trying the original request(s) fails the frontend should trigger the user-facing authorization flow

Pros:

* Probably the simplest solution overall
* Does not involve Postgres locking. Low risk. I'm pretty sure we can safely say that we know this will work
* Will make the backend code simpler than it currently is by removing the automatic "refresh and retry"
* Will reduce request queueing. We no longer have requests occupying a web worker while they make a failed request to the Canvas API, make a refresh request, and re-try the original request to the Canvas API.

Cons:

* Requires both backend and frontend changes
* Will make the frontend code more complex than it currently is by moving "refresh and retry" logic into the frontend

## Solution 2: Use Postgres locking to make requests wait

Before sending a refresh request the backend could acquire a Postgres [advisory lock](https://www.postgresql.org/docs/11/explicit-locking.html#ADVISORY-LOCKS). Other simultaneous requests for the same user would wait on this lock and, after waiting, would see that the access token has already been refreshed and use it.

Pros:

* Requires only backend changes

Cons:

* Introduces usage of Postgres locking, risk of unforeseen issues with this. We don't know if this will work (we haven't actually tried implementing the locking)
* We have multiple requests blocking and occupying scarce web workers while one request does a refresh with the Canvas API

## Solution 3: Use Postgres locking to make requests fail

Acquire a lock before making a refresh request. Instead of blocking, simultaneous requests will immediately respond to the frontend with a new type of error response that means "re-try me again later".

Pros:

* Less blocking than solution 2. We still have one request doing an API request to Canvas that fails, then doing a refresh, then re-doing the original request. But any simultaneous requests fail immediately rather than holding their web workers while waiting on the first request.

Cons:

* More blocking than solution 1 because we still have one request doing an API request to Canvas that fails, then doing a refresh, then re-doing the original request
* This is probably the most complex of the three solutions overall. Will make both the backend and frontend code more complex than currently
* Requires both backend and frontend changes
* Introduces usage of Postgres locking, risk of unforeseen issues with this. We don't know if this will work (we haven't actually tried implementing the locking)

## Solution 4: Use Celery to refresh access tokens asynchronously from web requests

See [Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1644416393843629)

**Comment by seanh** [comment]
My early opinion is that solution 1 described above issue is the best solution. It unfortunately requires both backend and frontend changes. But it should result in overall the simplest code (backend + frontend), doesn't require Postgres locking, it's low risk (it'll definitely work), and it does the best job of avoiding performance issues by reducing request blocking and queuing on the backend.

Solution 2 would require only backend changes but it's more risky (introduces Postgres locking) and will result in poorer application performance as it maximise request blocking and queuing on the backend.

**Comment by seanh** [comment]
We decided to go with solution 1 (have the frontend coordinate refresh requests). The decision was made in [this Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1644416393843629).

Pull requests that have been merged so far:

- [x] Add the new `POST /api/canvas/oauth/refresh` and `POST /api/blackboard/oauth/refresh` APIs: https://github.com/hypothesis/lms/pull/3685 and https://github.com/hypothesis/lms/pull/3730
- [x] Disable backend refresh requests when the `frontend_refresh` feature flag is on: https://github.com/hypothesis/lms/pull/3695 and https://github.com/hypothesis/lms/pull/3718
- [x] Include refresh API info in error responses when the `frontend_refresh` feature flag is on: https://github.com/hypothesis/lms/pull/3701 and https://github.com/hypothesis/lms/pull/3721 

Still todo:

- [ ] Have the frontend call the new refresh API and retry requests as appropriate
- [ ] Delete the `frontend_refresh` feature flag and refresh-and-retry support from the backend

# Testing

## Enable the `frontend_refresh` feature flag

You'll want to enable the `frontend_refresh` feature flag for testing and development:

    export FEATURE_FLAG_FRONTEND_REFRESH=true

This feature flag does two things:

1. It disables the backend's existing refresh-and-retry function. It'd be impossible to test frontend refresh-and-retry if the backend kept automatically refreshing expired tokens

2. It causes the backend to put refresh API request info into its error responses as appropriate.

   This means that the frontend code itself doesn't need to be feature flagged. Without the feature flag the backend will never send the refresh API info to the frontend

## Testing in Canvas

1. Log in to <https://hypothesis.instructure.com/> using any of the test accounts in 1Password

2. Make sure you have an access token for the current user in your DB. For example by launching [localhost (make devdata) Canvas Files Assignment](https://hypothesis.instructure.com/courses/125/assignments/875) and clicking through the authorization flow if you get it

3. Invalidate the access token in your DB. You can either wait for an hour for the access token to expire or you can run this command:

       tox -qe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo';"

4. Re-launch the assignment. You should see the authorization dialog. In the browser's dev tools you should see that API requests like `sync` and `via_url` have failed with 400 Bad Request and the bodies of these requests contain info about how to make a refresh request:

   ```json
   {"refresh": {"method": "POST", "path": "/api/canvas/oauth/refresh"}}
   ```

## Testing in Blackboard

1. Log in to <https://aunltd-test.blackboard.com/> using any of the test accounts in 1Password

2. Make sure you have an access token for the current user in your DB. For example by going to [Developer Test Course with Original Course View](https://aunltd-test.blackboard.com/ultra/courses/_19_1/cl/outline) and launching a groups or files assignment, for example **localhost (make devdata) Blackboard Files Assignment**. Click through the authorization flow if you get it

3. Invalidate the access token in your DB:

       tox -qe dockercompose -- exec postgres psql -U postgres -c "update oauth2_token set access_token = 'foo';"

4. Re-launch the assignment. You should see the authorization dialog. In the browser's dev tools you should see that API requests like `sync` and `via_url` have failed with 400 Bad Request and the bodies of these requests contain info about how to make a refresh request:

   ```json
   {"refresh": {"method": "POST", "path": "/api/blackboard/oauth/refresh"}}
   ```

# What the frontend needs to do

Recall that when an API request fails with a 400 Bad Request there are three possibilities:

1. If the error response body does not contain any `message` or `error_code` then the frontend shows the authorization dialog
2. If the body contains an `error_code` then the frontend shows the error dialog matching that `error_code`
3. If the body contains a `message` then the frontend shows a generic error dialog containing the given `message`

(In case 2 or 3 the body may also contain a `details` that the frontend also displays.)

See [the docstring](https://github.com/hypothesis/lms/blob/459e923e4fc83a93412cfaf22caac0cdc5890927/lms/views/api/exceptions.py#L35-L101) for details.

When the `frontend_refresh` feature flag is on these error response bodies may also contain a `refresh` object that instructs the frontend to try doing a refresh request and then re-trying the original failed request, before showing the authorization or error dialog:

* When calling the backend's API if the frontend receives a 400 Bad Request with refresh info in the body it should:
  * Make a single refresh request
  * If the refresh request succeeds then:
    * Re-try the original failed request(s) once only
    * If one or more of the requests fails again on the second attempt then show either the authorization dialog or the error dialog (according to the body of one of the failed requests)
  * If the refresh request fails then:
    * Show either the authorization dialog or the error dialog (according to the body of the failed refresh request)

When the frontend makes multiple API requests simultaneously more than one of them may fail with refresh info in the error body. When this happens the refresh info will always be the same in each response.

The frontend must ensure that it doesn't make more than one refresh request at the same time. (At least within a given tab. It's okay if the user having multiple tabs open can cause simultaneous requests.)

The frontend must ensure that it only refreshes and retries the original request(s) once and then gives up (showing the authorization or error dialog). It mustn't continually refresh-and-retry in a loop even if the backend continues to include `"refresh"` in its error responses.

**Comment by robertknight** [comment]
When testing the feature flag on QA I noticed that the body of the refresh response is a not-very-useful empty object (`{}`), if the refresh fails due to the access token having been revoked by the user. The frontend still handles this as expected by prompting the user to re-authorize.

**Comment by robertknight** [comment]
I have enabled the `frontend_refresh` feature flag in the lms-qa and lms-prod environments. I suggest we give it a few days and then remove the feature flag. At that point we can close out this issue.
