### ISSUE TITLE
Allow front-end to specify submission date on `api/lti/submissions`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#3669]
For:

 * https://github.com/hypothesis/lms/issues/3647

To satisfy https://github.com/hypothesis/lms/issues/3647 (only submit an assignment after qualifying annotation activity), the front-end will need to be able to specify the submission date for the current submission.

The reason that it would be preferable to have the front-end specify the submission date instead of the backend using current server timestamp is that we'd like to be able to use the exact timestamp from the associated annotation that triggered the submission. That could theoretically make it easier to track down what activity triggered a given submission in the future.

If this parameter (`data` property) were made optional, this work could be done anytime without coordinating with front-end work on https://github.com/hypothesis/lms/issues/3647

Part of https://github.com/hypothesis/lms/issues/3647

**Comment by lyzadanger** [comment]
I poked at this just a little to see if I could be self-sufficient, but there's enough domain expertise required here that I'm going to need a hand. If I'm reading specs correctly, the [LTI Basic Outcomes spec](http://www.imsglobal.org/spec/lti-bo/v1p1/) doesn't know anything about "submission dates", and by reading just that spec it would seem like any submission would need to have a grade associated with it.

It looks like Canvas muddles with this/extends it in two ways that are relevant:

1. You can create a "submission" with no grade associated with it, and
1. It has a "Submission Submitted At Timestamp Extension" (documented on [this page](https://canvas.instructure.com/doc/api/file.assignment_tools.html) ) that allows you to associated a timestamp with the submission

(This is not news, likely, for folks who have worked in this part of the app before; just getting my head around it). We are currently taking advantage of item 1 here by submitting submissions with no grade the first time the assignment is launched by a student. We don't send a timestamp, so all submissions look like they were submitted at whatever Canvas' default timestamp is, something like Dec, 2000. In any case, a static date way in the past.

It looks like the proxy API [has some logic not to create multiple submissions](https://github.com/hypothesis/lms/blob/master/lms/views/api/lti.py#L78-L84). If I'm extrapolating this behavior correctly in terms of adding a timestamp to our submissions, that would mean that the timestamp associated with a student's first qualifying annotation activity on an assignment will be that student's "permanent" submission date for the given assignment. That is, the submission date would not update if the student performed qualifying annotation activity on subsequent launches because there's already a submission recorded for that student/assignment combination.

This may not be expected behavior for instructor-users, or I may be making mistaken assumptions, so I want to talk it through.

**Comment by marcospri** [comment]
Enabled custom dates with https://github.com/hypothesis/lms/pull/3877
