### ISSUE TITLE
LTI 1.3 certification

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#3687]
https://www.imsglobal.org/ltiadvantage

 - [ ] LTI 1.3 Core
 - [ ] LTI 1.3 Deep Linking
 - [x] ~LTI 1.3 Names and Roles~ (Not necessary for certification https://github.com/hypothesis/lms/issues/3692)

**Comment by chrisshaw** [comment]
Looks like a duplicate of https://github.com/hypothesis/lms/issues/933, or are these different? Do you want to keep yours or the really old one?

**Comment by marcospri** [comment]
Duplicate of #933
