### ISSUE TITLE
Unable to set up prod install of Hypothesis with provisioning in course where QA is installed

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#371]
While trying to set up a set of test assignments [in Moodle](https://hypothesisuniversity.moodlecloud.com/course/view.php?id=7) I ran into an issue where I was unable to launch assignments using the prod LMS app within a course that already had the QA LMS app installed. Provisioning was enabled for both installs.

**Steps to reproduce:**

1. Log in to our Moodle instance and go to the Hypothesis 101 course: https://hypothesisuniversity.moodlecloud.com/course/view.php?id=7

2. Attempt to launch any of the "Production" assignments

   <img width="300" alt="moodle hypothesis 101" src="https://user-images.githubusercontent.com/2458/49445555-15714780-f7ca-11e8-9dc5-e27ed09de537.png">

**Expected result:**

Assignment launches.

**Actual result:**

<img width="500" alt="lms moodle groupid conflict" src="https://user-images.githubusercontent.com/2458/49445547-1013fd00-f7ca-11e8-97fb-b8918a833ea2.png">

**Notes:**

@seanh thinks this might be because the LMS QA and prod apps use a separate DB and therefore separate records of which groups they have created in h, but there is only one group in the h DB for a given LMS course. This should be resolved by work in progress to avoid storing group IDs in the LMS DB.

Once this issue is resolved the Production assignments need to be configured.

**Comment by seanh** [comment]
Fixed by https://github.com/hypothesis/lms/pull/364
