### ISSUE TITLE
Un-deploy the old "lti" application

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#393]
The predecessor to this project, https://github.com/hypothesis/lti, has been archived but is still deployed to Elastic Beanstalk.

We need to undeploy it.

This will basically involve going through our [app deployment guide](https://github.com/hypothesis/playbook/blob/master/docs/deploying-a-new-app.md) and removing any resources or configuration that were created in the process. A non-exhaustive list includes:

- [x] The Elastic Beanstalk environment
- [x] Security groups for lti app instances (I can't see any SGs referencing "LTI" in the name as of 2022-06-20 - robertknight)
- [x] Jenkins jobs and workspace contents for the lti app
- [x] Cloudflare sub-domain configuration
- [x] Pingdom
- [x] PagerDuty? (PagerDuty references the various monitoring services we use, not the apps directly. - robertknight)
- [x] Other monitoring services?
- [x] Any other references in the "playbook" repo (https://github.com/hypothesis/playbook/pull/919)
- [x] Any other references in the "deployment" repo. Done: <https://github.com/hypothesis/deployment/pull/32>

**Since this is the first time we have undeployed an app, it would be very useful if whoever did this wrote down a list on this issue of what they did.**

Lastly, searches for LTI / LMS queries are still turning up issues in the hypothesis/lti repo, despite it having been archived. We should find some way to fix that, or at least send a request to GitHub to ask them to consider it.

**Comment by seanh** [comment]
I've done enough of this card so that there are no longer a live and potentially usable apps at https://lti.hypothes.is and qa-lti.hypothes.is and checked some of the boxes but much of the lti app's stuff is still not removed.

**Comment by hmstepanek** [comment]
I have deleted lti from NewRelic

**Comment by robertknight** [comment]
There are still some references to the "lti" app in the playbook:

```
[I]  ~/h/playbook > ag '\blti\b'
bootstrap/roles/groups/tasks/groups.yml
111:- name: lti application instances security group
113:    name: app-lti
114:    description: LTI application instances
161:      - # Allow postgres from lti app hosts
165:        group_name: app-lti

configure/roles/rds/tasks/lti.yml
1:- name: create lti-qa user
15:- name: create lti-qa database
26:- name: update lti-qa database owner
37:- name: create lti-prod user
51:- name: create lti-prod database
62:- name: update lti-prod database owner

configure/roles/rds/tasks/main.yml
7:- include: lti.yml

docs/running-tasks-on-qa-and-prod.md
38:Running lti tasks
41:Running tasks for the QA or prod environments of the lti application works the [same as for h](#running-h-tasks).
43:The only difference is that you need to run the tasks from the [lti-tasks][jenkins-lti-tasks] Jenkins job.
45:[jenkins-lti-tasks]: https://jenkins.hypothes.is/job/lti-tasks/

secret/common.yml
30:# RDS lti user/password for prod and qa
32:lti_qa_db_name: lti-qa
33:lti_qa_db_user: lti-qa
35:lti_prod_db_name: lti-prod
36:lti_prod_db_user: lti-prod
```

**Comment by robertknight** [comment]
This is now complete as far as I can see. The EB environment has been retired, the repo has been archived, documentation in the playbook has been removed.
