### ISSUE TITLE
Determine tech approach for generating metrics

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#401]
Part of https://github.com/hypothesis/lms/issues/394

We're determining some internal metrics needs for LMS (see https://github.com/hypothesis/lms/issues/394). We'll need a tech approach for providing these metrics. Metabase has certainly been bandied around as a viable option. There's some interestingness here because we'll need to query both the `h` (users, groups, annotations) db and the `lms` db (installs, launches).

This task is done when we've decided on a platform/approach. If feasible and within reasonable spike scope, we should go ahead and spin up what we need (e.g. Metabase instances). If it ends up being larger in scope, we'll open a subsequent issue for the implementation of things.

**Comment by marcospri** [comment]
We done a second past to this since 2018
