### ISSUE TITLE
Doc selection dialogue box not visible depending on page height 

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#407]
If a user's screen is not large enough, the dialogue box where they choose the document to be annotated (pictured below) isn't visible at first. The user needs to scroll down to find as it appears centered in the page space rather than weight to the upper left.

![image](https://user-images.githubusercontent.com/3261902/50665323-c9a2f100-0f75-11e9-9b22-59363a9b84a5.png)
  
Here's how a user in Sakai described it:

>I toyed around with this once more and realized that the launched tool appears, but if the frame height is tall enough, the picker URL info shows up farther down the page - so it looks like it's a blank page unless you scroll.

You can see this at around :26 of this video:

https://www.useloom.com/share/17d44ffe274a4689b24956db51246dd0

**Comment by robertknight** [comment]
I was able to reproduce this using the [Sakai Docker](https://github.com/hypothesis/sakai-docker) image.

After setting up Sakai, adding Hypothesis as a tool and clicking the link in the sidebar to see the tool, I was presented with a blank white space in the middle of the screen:

<img width="878" alt="screenshot 2019-02-25 12 49 36" src="https://user-images.githubusercontent.com/2458/53338522-d7348180-38fb-11e9-99fb-be41596774e0.png">

The blank white space on the right is a 1200px tall iframe displaying the URL https://lms.hypothes.is/module_item_configurations.

After scrolling down the selection dialog becomes visible:

<img width="1142" alt="screenshot 2019-02-25 12 51 37" src="https://user-images.githubusercontent.com/2458/53338647-224e9480-38fc-11e9-8a26-6f2ae4811c5f.png">

**Comment by seanh** [comment]
This has been fixed now that the `new_oauth` feature flag has been released
