### ISSUE TITLE
Create a new domain for LTI1.3 pointing to the current LMS servers

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#4071]
LMSs keep track of which applications are "the same" based on domain and for example Blackboard treats upgrading as a non-reversible operation.

Having a separate lti13 domain will allow us to:

- Test the LTI1.3 app in Blackboard, using the new domain to avoid triggering the update flow.
- Test the upgrade flow in all LMS using thew new domain as both an LTI1.1 app and then upgrading to LTI1.3 (without affecting the main app domain).

### Proposed domains:

https://qa-lti13-lms.hypothes.is/admin
https://lti13-lms.hypothes.is/admin
(and the Canadian one)

qa.lti13.lms would work too. Anything with "LTI" and "1.3" in the names would do.

We don't know if having a separate domain will have any functional effects on the LMS app so **we'll start pointing a new name to the QA** server and validating the process there.

**Comment by indigobravo** [comment]
https://qa-lti13-lms.hypothes.is has been created and points to the QA LMS service in the US. Once we have tested and found all to be working. I will create records to the production service in the US and Canada.

**Comment by marcospri** [comment]
This won't be necessary in production for now.

The QA domain is very useful for testing but adding it to production without a clear need could be confusing. We can revisit this if we ever need it.
