### ISSUE TITLE
Change wording on welcome page: Canvas Developer Secret --> Canvas Developer Key

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#412]
I propose we change the wording of the last field on the welcome form to read **Canvas Developer Key**

The change we made in https://github.com/hypothesis/lms/issues/184 helped with some confusion, but we still have one inconsistency wrt the Canvas interface. 

We ask for a Canvas Developer Secret, but when admins look at Canvas Developer credentials, there is a button that says "Show Key": 

Our welcome page:
<img width="552" alt="screen shot 2019-01-09 at 11 59 04 am" src="https://user-images.githubusercontent.com/12087705/50915074-fe93c580-1405-11e9-9527-14de7cbfd7b1.png">

The Canvas admin page:
![screenshot-hypothesis instructure com-2019 01 09-11-56-30](https://user-images.githubusercontent.com/12087705/50914920-ad83d180-1405-11e9-9379-f837cf470760.png)

**Comment by lyzadanger** [comment]
I want to point out [this issue](https://github.com/hypothesis/lms/issues/155) which suggest changing the name of the data/stored value as well.

**Comment by klemay** [comment]
The change will be made [here](https://github.com/hypothesis/lms/blob/master/lms/templates/application_instances/new_application_instance.html.jinja2), specifically the `label` at line 38: 

<img width="634" alt="screen shot 2019-02-04 at 2 35 40 pm" src="https://user-images.githubusercontent.com/12087705/52232309-2bfb5400-288a-11e9-9284-d5588415a28f.png">

I have a small question before submitting my PR:

Should I change the label `for` and input `id` attributes on lines 33-34 and 38-39 to match the label text as part of this PR? As a separate PR after the value itself is changed? Or just leave it alone?

**Comment by klemay** [comment]
Documentation has been updated as well!
