### ISSUE TITLE
Identify and track replies on Noodle assignments

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4199]
The metric to decide whether the Noodle project is successful is number of replies on Noodle assignments. We expect there to be a 25% increase (over what time period?)

We need to be able to:

 * Identify which assignments are Noodle assignments (How?)
 * Get the number of replies
 * Present the data somewhere (Where?)

### Questions

 * This ticket is listed as a spike as I've no idea how to solve it yet
 * What if we can't track this? Would we still continue with the project?

**Comment by jon-betts** [comment]
If we collect details to update users application instances, we would at least know which AI's to limit our search to.

**Comment by chrisshaw** [comment]
Per our convo, the right outcome to track is **one of**:

- We completed it to a degree they can build something
- We activated more teachers on the Noodle Learning Platform
  - And what we're really saying here is we got more students that we get paid for
- We validated that out-of-context feeds/notifications increase social engagement (via replies)
