### ISSUE TITLE
Google Picker not working for assignments launched in a new window

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#421]
**Note: this issue shows that the Google Picker is broken in Moodle for one install configuration. Choosing to load assignments in an embedded iframe does not cause Google Picker to break, and that is what I've advised users to do in the meantime.**

When you install the Hypothesis app for Moodle, whether for an individual course or at the institutional level, you have the option to have Hypothesis-enabled assignments launch in the same window or in a new window:

![pasted image 0](https://user-images.githubusercontent.com/12087705/51278751-6ec3bd80-19a9-11e9-94b9-88b3ab68597b.png)

Choosing the "new window" option is preferable for many instructors, in order to maximize the space given to the original text and annotation sidebar.  

However, choosing this option now causes the Google Picker to break. Note that an instructor can still copy-and-paste a public URL during the assignment creation process and it'll work just fine - it's only the Google Picker that is broken. 

I have edited our Moodle app so that a dev can easily reproduce this:

## Steps to reproduce

1. Log in to our Moodle instance (note that you can access our Moodle instance using [credentials in this doc](https://docs.google.com/document/d/1p7XiZclKWDlkOxlcuHXdkrsGtemGeR5gQiJ4qUq7o00/edit#heading=h.xcv7oqstt3uq)). 
2. Choose any course; you're welcome to use the one called [Katelyn's testing environment](https://hypothesisuniversity.moodlecloud.com/course/view.php?id=8). 
3. Turn editing on and create a new assignment (you might find [these instructions](https://docs.google.com/document/d/17poBMaXGEp93MdL1MvAcS2uCYKbobh027kfQa_qVZ_s/edit#heading=h.wq28g2mnwz80) helpful))
4. After you click "Save and Display," click on your new assignment. You'll be prompted to enter a public URL or use the Google Picker. Select **Use Google Picker**.
5. Authorize a Google account

### Expected behavior
A list of your Google Drive files shows 

### Actual behavior
A blank window:

<img width="1586" alt="screen shot 2019-01-16 at 4 24 28 pm" src="https://user-images.githubusercontent.com/12087705/51279370-38873d80-19ab-11e9-8c6f-c6b3cdf3febf.png">

The browser console shows the following errors:
<img width="1204" alt="screen shot 2019-01-16 at 4 24 05 pm" src="https://user-images.githubusercontent.com/12087705/51279379-40df7880-19ab-11e9-90f0-ea64af604329.png">

**Comment by klemay** [comment]
This has now been reported in Blackboard and Sakai as well as Moodle.

**Comment by robertknight** [comment]
The Google Picker integration has been re-implemented as part of the new file picker implementation, so it is possible this issue is resolved. I'll test once https://github.com/hypothesis/lms/pull/678 is deployed.

**Comment by klemay** [comment]
Good to know!!

**Comment by robertknight** [comment]
It looks like the problem still occurs with the new implementation, I created this test assignment on QA: https://hypothesisuniversity.moodlecloud.com/mod/lti/view.php?id=79&forceview=1

**Comment by seanh** [comment]
Note that this only applies in LMS's without content item selection.

**Comment by seanh** [comment]
Problem and solution: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1560338316206300
