### ISSUE TITLE
Conduct survey to see if we reduced login issues

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4217]
When teachers and students today use the VitalSource integration, they get blocked by a login screen, in which they must log into **VitalSource’s** Bookshelf account every time.

25% of students using the tool told us in an end-of-pilot survey they had problems logging in, and VitalSource has said this is a primary blocker to scaling the partnership.

By the end of the Fall 2022 semester, we are aiming to reduce login issues by 50%. We should design and disseminate a survey to track this.

### Questions

 * Do we want to track anything else?
 * Could / should we record primary data about how many times people run into the error scenarios we are trying to avoid?
 * Maybe the exact numbers don't matter if user sentiment gets better or worse?

### Survey design

 * TBC

**Comment by chrisshaw** [comment]
The survey sits within the [project drive folder](https://drive.google.com/drive/folders/1Bl0x2hyfAmfcre4S6X--6IQ-vl7doDo3).
