### ISSUE TITLE
LMS admin pages fixes and improvements

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#4304]
- [x] Add an option to downgrade LTI1.3 AI to 1.1 in the admin pages
- [ ] Handle (show an error message) when editing an AI conflicts with another one (ie duplicated deployment_id)
- [x] Strip trailing `/` in the issuer. The issuer/lms url split makes this very confusing. https://github.com/hypothesis/lms/pull/4380
- [x] Allow editing of Canvas API keys in the application instance. https://github.com/hypothesis/lms/pull/4376
- [x] Allow editing of registration URLs. https://github.com/hypothesis/lms/pull/4388

**Comment by mkdir-washington-edu** [comment]
I verified today in our Canvas instance that including a Canvas Developer API ID/Key in the new deployment, and **also** including an LTI 1.1 Consumer key that does **not** have a Canvas Dev API ID/Key, makes it so the saved deployment does not have the Canvas API ID/Key.

Subaccount install: https://hypothesis.instructure.com/accounts/111/settings/configurations#tab-tools

https://lms.hypothes.is/admin/instance/id/5536/

**Comment by mattdricker** [comment]
Rendering issue when viewing list of app instances from a given reg page. The ai box doesn't dynamically adjust to the browser width, and the browser doesn't know to provide a horizontal scroll bar to get to the **View** button at the right of the ai item.
![Screen Shot 2022-08-18 at 2 02 18 PM](https://user-images.githubusercontent.com/71603629/185464289-5cba526f-378b-4d88-9126-3dffd6c813e5.png)

**Comment by marcospri** [comment]
> I verified today in our Canvas instance that including a Canvas Developer API ID/Key in the new deployment, and also including an LTI 1.1 Consumer key that does not have a Canvas Dev API ID/Key, makes it so the saved deployment does not have the Canvas API ID/Key.


This hasn't been "fixed" as now those fields are not present in the upgrade path. For updating them you can directly update them on he AI details page.
