### ISSUE TITLE
Add tracking user ID and user agent to JSTOR PDF URL requests

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#4340]
JSTOR have requested that we add a tracking user ID to requests to their API for usage accounting purposes.

_Update 2022-09-07: JSTOR have informed us that forwarding the User-Agent to them is more important than we initially thought._

When a user accesses JSTOR PDFs directly via their website, they would normally do this with a cookie. In our application however, we are fetching the content on behalf of the user, so they have no ability to set a cookie.

Some notes:

- The user ID is mainly needed for when we fetch a PDF URL via the `/pdf/{doi}` endpoint in the API. See Slack thread for confirmation of which API calls need to include this
- The user ID format they are used to dealing with is a UUID, although they could convert it to another format themselves if needed
- The longevity and origin of the user ID do not need to be strongly guaranteed, since it is a substitute for a cookie which could be cleared at any time
- The location of the user ID in API requests is TBD, I suggested a `Tracking-UserID` header

See discussion at https://hypothes-is.slack.com/archives/C02T75RKBTK/p1660577524314679.

**Comment by robertknight** [comment]
See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1661267330080879 for discussion around the details of how we'll generate a user ID. Current thought is `hash(LMS guid + LMS user ID)`.

**Comment by robertknight** [comment]
A related request from JSTOR is to also forward the `User-Agent` from the browser, so they can do some user segmentation (eg. by device) on their side. From https://hypothes-is.slack.com/archives/C02T75RKBTK/p1660657856860449?thread_ts=1660577524.314679&cid=C02T75RKBTK:

> See Also, and if it's easy, passing the User-Agent would be useful as our logging/reporting tools are able to do some level of user segmentation reporting..

**Comment by rsnyder** [comment]
I've come to understand that the User Agent is an important data item used in COUNTER usage reporting/aggregation.  In light of this I'd put the passing of a User Agent header in the request as a "must have" rather than "nice to have" item.
