### ISSUE TITLE
Discuss performance of article metadata endpoint with JSTOR

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#4341]
The JSTOR metadata endpoint is currently slow, with an average response time of ~3s when I tested this morning (2022-08-02). It would improve the user experience of configuring and viewing JSTOR assignments if this was improved. See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1659525786576519. When viewing assignments this endpoint is only used to display the banner, and we fetch the data for that banner concurrently with everything else. However this means that the banner only gets populated after several seconds, rather than right away.

**Comment by robertknight** [comment]
I discussed the issue with JSTOR in a call on 2022-08-03. They agreed to look into changes on their end. I'm leaving the issue open as a reminder under it is resolved on their end. On our side, we mitigate the delay by ensuring that it does not block assignment loading. All the requests needed for the assignment to load happen in parallel with fetching the data for the content banner.

If it turns out that the problem cannot be resolved soon on their side, we can potentially improve the user experience when launching assignments by showing the content banner in an empty/loading state before we make the call to JSTOR to fetch the data for it.

**Comment by rsnyder** [comment]
The metadata endpoint has been updated and now returns responses in less than a second in most cases.

**Comment by robertknight** [comment]
Thanks. From doing a quick tests just now and looking in New Relic I see an average of ~700ms for metadata lookup calls and ~1000ms for thumbnails. I think this can be considered done for the moment.
