### ISSUE TITLE
Remove support for application instances that are not using provisioning

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#4381]
Slack thread: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1661199058107549

A user encountered an error when launching an assignment, where the LMS frontend had crashed because the `services` field was missing from the Hypothesis client config. This field is omitted by the backend when user/group provisioning is disabled for the application instance (ie. `ApplicationInstance.provisioning` is `False`).

User/group provisioning is a feature that we assume is used by all LMS installations nowadays, but is still a configuration setting of app instances. This is a vestige of when the feature was introduced originally. It appears that small number of old LMS app installations still have this feature turned off. The frontend assumes that it is always enabled. If one of these old app installations with the feature turned off is used in an assignment, that is most likely a mistake.

We should remove support for application instances that do not use provisioning. For example, we could make launches with such instances fail loudly when a launch happens, to smoke out any remaining usage, and then remove the remaining DB entries some time later.

**Comment by marcospri** [comment]
The only usage of this concept now is to throw an error about it. We'll keep that around just in case one of the clients want to promote their instance.
