### ISSUE TITLE
Add the ability to (re-)allocate an application instance to an organisation

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/lms#4417]
In order to allow users to arrange application instances into organisations correctly we need to let them change values.

We need to support:

 * [x] Moving an application instance from one organisation to another
 * [ ] Adding an application instance which has no organisation to one

These could be achieved with a text field which accepted and verified an org public id.

**Comment by marcospri** [comment]
Tacking: 

`Adding an application instance which has no organisation to one`

with the option to create new orgs from scratch
