### ISSUE TITLE
Look into redesigning the picker view in LMS

### ISSUE THREAD

**Issue by darylhedley** [hypothesis/lms#4437]
![Image](https://user-images.githubusercontent.com/3483708/189702959-16bc7b28-424e-4712-b440-5201e79370cf.png)

The image above shows how the current picker is displayed to the end teacher when setting up an assignment. This design will not scale as we add more inputs. If was also mentioned by Jeremy that JSTOR and VitalSource should be moved lower down the pecking order.

**Comment by robertknight** [comment]
A redesign of the picker was shipped since this issue was filed.
