### ISSUE TITLE
Use D2L nomenclature for group sets

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#4678]
We use the name "group sets" in various parts of the UI but we should match the nomenclature 
of the LMS we are running in.

For D2L that's "group categories".

For instances of this in error modals that are based on a error code we can create a version of dialog with the right name.

When this is part of the general UI for example in:

https://github.com/hypothesis/lms/blob/lms/static/scripts/frontend_apps/components/GroupConfigSelector.js#L44

we could rely on the new product config option:

https://github.com/hypothesis/lms/blob/main/lms/static/scripts/frontend_apps/config.js#L181

and either:

- Use the family property and a few conditionals in the FE to pick the right value
- Send a new "group_set_naming" or similar from the BE and just use that
- Trying to use a more generic name in all LMS
  Not a fan of this one.
- ???

I reckon I'd prefer the first option.

**Comment by robertknight** [comment]
> I reckon I'd prefer the first option.

I agree. The risk with trying to send a value from the backend is that you run into a wall as soon as you need just a bit more flexibility. Also when we come to translate to other languages, there may be issues with other parts of a sentence around the changed terminology needing to change.

> Trying to use a more generic name in all LMS. Not a fan of this one.

I agree here too. It seems like it will be important to use the same terminology as the LMS the user is in.
