### ISSUE TITLE
Can only create Google Drive assignment in Chrome

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#4696]
### Steps to reproduce
1. In Firefox (102) or Safari (15) open Canvas and create an Assignment
2. Choose the Google Drive option
3. The connection seems to hang, see errors in Console:
Examples:

![image](https://user-images.githubusercontent.com/22603275/180839645-c89f1477-62b6-4896-83f5-b5e193c21452.png)

![image](https://user-images.githubusercontent.com/22603275/180839687-a750ecf0-8f16-46d6-96f5-22e40019c4db.png)

### Expected behaviour
In Chrome the Drive window opens.

### Actual behaviour
I'm not sure if the Chrome warnings matter, but Firefox and Safari aren't displaying the Google Drive window after authenticating in.

### Browser/system information
Firefox 102, Safari 15
macOS BigSure 11.6.5

### Additional details
When fixed Support needs to email the user here: https://app.hubspot.com/contacts/6291320/ticket/1008730292

**Comment by robertknight** [comment]
In Safari, the call to either `signIn` or `getAuthResponse` is not returning in https://github.com/hypothesis/lms/blob/fd75b22e0e16065588fca871a9fef79bf39935f3/lms/static/scripts/frontend_apps/utils/google-picker-client.js#L85.

**Comment by robertknight** [comment]
Authentication for the Google Drive Picker and Google Drive API has been migrated from the "auth2" library to Google Identity Services. This fixes the authorization flow in Safari and Firefox and also the console warning about use of a deprecated auth library.

**Comment by mkdir-washington-edu** [comment]
I've emailed all three linked tickets. @mattdricker FYI.
