### ISSUE TITLE
Prototype the revised Canvas file selection flow

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#470]
This part of https://github.com/hypothesis/lms/issues/460.

Build a standalone application to prototype the revised UX of Canvas (or other LMS) file selection, in which OAuth authorization will happen only when the user chooses to select a file from Canvas (or other LMS) and only once for a particular user.

The purpose of this is both to help with working out some implementation details but also to investigate various aspects of the UX, such as what happens while waiting for authorization to occur.

The output of this task should be:

- A standalone app which shows the revised Canvas/LMS file selection flow
- Potentially frontend code and tests that we can integrate back into the existing app, although the main task is to figure out the details of how the flow works and how it integrates with the LMS app's backend

**Comment by robertknight** [comment]
The code for the WIP prototype is being developed in the [lms-file-picker-prototype](https://github.com/hypothesis/lms-file-picker-prototype) repo. I've also posted a live version on Glitch: https://robertknight-lms-file-picker-prototype.glitch.me/

**Comment by lyzadanger** [comment]
@robertknight And I just had a discussion and I presented some possible UI high-level sketches for the file-picker interface—focused just on that step and putting the OAuth prompts, etc., aside for now.

My main idea here is that there are two things that an instructor-type user does during this process:

* Selects what source the assignment content is going to come from (web, Google Drive, Canvas file), then
* Selects the content itself (via URL, selecting a Google PDF, selecting a Canvas PDF)

Thus, the first file-select interface could look something like this:

![image](https://user-images.githubusercontent.com/439947/53898634-79442000-4006-11e9-8619-22bdd4627c6d.png)

In the above, I've been more specific on wording to denote "PDF" for Google Drive and Canvas docs. This likely bears some further discussion, but I think it could be helpful to be specific. 

It is already the case that if you click on the Google Drive or Canvas buttons in the file picker interface, you get a dialog to then select the file you want. Thus, I think it could be a sensible flow that if a user clicks on the "Web Page or PDF by URL" option, they'd get a dialog, also, something like:

![image](https://user-images.githubusercontent.com/439947/53898754-bc9e8e80-4006-11e9-974d-0445c6751793.png)

"Cancel" in this case would close the dialog, allowing the user to select a different source (Canvas, Google) if they wanted.

Now, there are cases where by-URL is the only option (if Google Drive is not enabled, nor Canvas files available). In that case, I think it could be OK to have a single-step "file picker," like so:

![image](https://user-images.githubusercontent.com/439947/53898846-e35cc500-4006-11e9-8d91-0025271edb9c.png)

I'm using the terminology "dialog" here, but that's sort of an implementation detail. My main argument is that the user should have the _same type of flow experience_ for all three buttons in the first interface, whether they're entering a URL or selecting a file from somewhere. Consistency FTW!

**Comment by robertknight** [comment]
I have implemented the suggestions above and pushed them to Glitch: https://robertknight-lms-file-picker-prototype.glitch.me

There is a bunch of visual polish that still needs to be done obviously, but I want to confirm we're happy with the overall flow and layout at the moment.

**Comment by robertknight** [comment]
Lyza, Sean and myself discussed this on Slack. At this point I think we're in a pretty good place with the overall user flow. I think the following needs to happen before we can close this out:

- [x] I will post a link to the demo in the #internal-lms channel to solicit feedback from outside the dev team
- [ ] I need to sync up with @seanh about the interaction between the frontend and backend to make sure we're agreed on how that will work. We should also talk about how the roll-out (presumably behind a feature flag) will work
- [ ] I will create some follow-up issues to track the front-end work that needs to happen to build a production ready version in the lms repo

**Comment by robertknight** [comment]
Next steps are identified in the follow up issues above.
