### ISSUE TITLE
Documentation for missing files in D2L

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#4770]
Linked when the filepicker returns no files in a given folder.

We currently link to:

- Canvas: https://community.canvaslms.com/t5/Instructor-Guide/How-do-I-upload-a-file-to-a-course/ta-p/618
- Blackboard: https://web.hypothes.is/help/bb-files

**Comment by mattdricker** [comment]
Here's the new [Using Hypothesis With D2L Course Content Files](https://web.hypothes.is/help/using-hypothesis-with-d2l-course-content-files/) kb
