### ISSUE TITLE
What is the desired wording and content of instructor digest emails?

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#4915]

**Comment by seanh** [comment]
[Slack thread](https://hypothes-is.slack.com/archives/C04J58NGMC4/p1674564624237159) with a draft of the email content

**Comment by darylhedley** [comment]
Document being worked on here: https://docs.google.com/document/d/1e_CB4uEwAVM6MVqFrbMDtQ1Pd4ZtkII5gmTVfqhF1gs/edit

**Comment by seanh** [comment]
# Iterations

Below I've outlined the sequence of iterations on the email template that I intend to ship as part of incrementally shipping this feature. Notes:

* We don't have to release the very first iteration to any real users. But maybe we should? Product can decide when the feature is ready to release. But we will be able to test the feature internally from the very first iteration.
* The iterations are presented in a fixed chronological order below but they don't actually have to be done in that order, we can re-order them. I may not have them in the best priority order below
* I've given examples of the actual subject lines and body texts for illustration but the exact wording doesn't have to be exactly as shown here. That can easily be changed in the template. The point of this is more to fix the template data for each iteration.
* There are various open questions about how exactly the various numbers involved are calculated. I've noted these questions on the iterations. We can answer each question as we come to that iteration

## First iteration: the simplest possible thing

Everything missing except the total number of annotations:

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in assignments yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> Hypothesis Team

The template data that we would send to Mailchimp would be:

```json
{"num_annotations": 64}
```

Implementation questions:

* What counts towards the number of annotations: top-level annotations? Page notes? Replies? Highlights? Shared versus private annotations?

## Next iteration: add the name of the LMS instance (no link)

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in assignments at **Hypothesis University** yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> Hypothesis Team

Template data:

```json
{"num_annotations": 64, "lms_name": "Hypothesis University"}
```

## Next iteration: link the name of the LMS instance

This is the same as the previous iteration except the name of the LMS instance is linked to the LMS instance's front page.

Template data:

```json
{
  "num_annotations": 64,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/"
}
```

## Next iteration: per-course breakdown

This adds in the course titles and the numbers of annotations per course. Course titles are not linked to the courses yet.

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in assignments at [Hypothesis University](https://hypothesis.instructure.com/) yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> **Making sociology fun**  
> Students made 30 annotations in assignments.  
> 
> **History of jazz music**  
> Students made 4 annotations in assignments.  
> 
> Hypothesis Team

Template data:

```json
{
  "num_annotations": 64,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {"title": "Making sociology fun", "num_annotations": 30},
    {"title": "History of jazz music", "num_annotations": 4}
  ]
}
```

## Next iteration: linking course titles

This is the same as the previous course breakdown except that the course titles are linked to the course's pages within the LMS's. This will probably actually be multiple separate iterations: we'll probably ship course links for each LMS separately (Blackboard, Canvas, Brightspace, ...).

```json
{
  "num_annotations": 64,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {"title": "Making sociology fun", "url": "https://...", "num_annotations": 30},
    {"title": "History of jazz music", "url": "https://...",  "num_annotations": 4}
  ]
}
```

## Next iteration: adding reply counts

This adds the **including 7 replies to your annotations**:

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in assignments at [Hypothesis University](https://hypothesis.instructure.com/) yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> **[Making sociology fun](https://example.com)**  
> Students made 30 annotations in assignments, including 7 replies to your annotations.  
> 
> **[History of jazz music](https://example.com)**  
> Students made 4 annotations in assignments.  
> 
> Hypothesis Team

Template data:

```json
{
  "num_annotations": 64,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {
      "title": "Making sociology fun",
      "url": "https://...",
      "num_annotations": 30,
      "num_replies_to_recipient": 7
    },
    {
      "title": "History of jazz music",
      "url": "https://...",
      "num_annotations": 4,
      "num_replies_to_recipient": 0
    }
  ]
}
```

Implementation questions:

* What counts as a "reply to your annotations"? Are we talking only about direct replies to the recipient's top-level annotations (i.e. the student actually clicked the reply button on the teacher's top-level annotation)? What about replies-to-replies, when the top-level annotation in the thread is the teacher's? What about when the top-level annotation is not the teachers but the teacher does have a reply in the thread, and then students reply to the teacher's reply (and then reply to those replies...)?

## Next iteration: adding "launcher" counts

This adds the **56 students opened assignments in this course**. Note that this is not the number of assignment launches, it's **the number of students who have launched assignments** in the course. "Launchers" not "launches".

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in assignments at [Hypothesis University](https://hypothesis.instructure.com/) yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> **[Making sociology fun](https://example.com)**  
> Students made 30 annotations in assignments, including 7 replies to your annotations.  
> 56 students opened assignments in this course.
> 
> 
> **[History of jazz music](https://example.com)**  
> Students made 4 annotations in assignments.  
> 22 students opened assignments in this course.
> 
> 
> Hypothesis Team

```json
{
  "num_annotations": 64,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {
      "title": "Making sociology fun",
      "url": "https://...",
      "num_annotations": 30,
      "num_replies_to_recipient": 7
      "num_launchers": 56,
    },
    {
      "title": "History of jazz music",
      "url": "https://...",
      "num_annotations": 4,
      "num_replies_to_recipient": 0
      "num_launchers": 22,
    }
  ]
}
```

Implementation questions:

* If the same user launches the same assignment multiple times, does that count multipled times toward the "opened assigments" number? **I'm thinking no**
* If the same user launches the **multiple different assignments**, does that count multipled times toward the "opened assigments" number? **I'm thinking no**
* If the email recipient launches an assignment, does that count? **I'm thinking no**
* If **other instructors** launch assignments, does that count? **I'm thinking ideally no,** but if that's hard to implement then it's fine to just let these count

## Next iteration: active assignment counts

This adds the **in 8 assignments** and to both the overall count and the per-course counts:

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in **8 assignments** at [Hypothesis University](https://hypothesis.instructure.com/) yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> **[Making sociology fun](https://example.com)**  
> Students made 30 annotations in 2 assignments, including 7 replies to your annotations.  
> 56 students opened assignments in this course.
> 
> 
> **[History of jazz music](https://example.com)**  
> Students made 4 annotations in 1 assignment.  
> 22 students opened assignments in this course.
> 
> 
> Hypothesis Team

```json
{
  "num_annotations": 64,
  "num_active_assignments": 8,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {
      "title": "Making sociology fun",
      "url": "https://...",
      "num_annotations": 30,
      "num_active_assignments": 2,
      "num_replies_to_recipient": 7
      "num_launchers": 56,
    },
    {
      "title": "History of jazz music",
      "url": "https://...",
      "num_annotations": 4,
      "num_active_assignments": 1,
      "num_replies_to_recipient": 0
      "num_launchers": 22,
    }
  ]
}
```

## Next iteration: per-assignment breakdown

This adds the assignment titles and the numbers of annotations, replies and launchers per assignment.

Note that I haven't thought of nice example assignment titles--"Assignment One" etc are meant to be the actual assignment titles from the LMS.

> **Subject:** There has been some activity in Hypothesis
> 
> **Body:**
> 
> Hi,
> 
> Your students made **64 annotations** in **8 assignments** at [Hypothesis University](https://hypothesis.instructure.com/) yesterday. Let your students know about the activity to encourage the ongoing conversation.
> 
> **[Making sociology fun](https://example.com)**  
> **Assignment One**  
> Students made 15 annotations in this assignment, including 7 replies to your annotations.  
> 56 students opened this assignment.  
> **Assignment Two**  
> Students made 15 annotations in this assignment.
> 25 students opened this assignment.
> 
> 
> **[History of jazz music](https://example.com)**  
> **Assignment A**  
> Students made 4 annotations in this assignment.  
> 22 students opened this assignment.
> 
> Hypothesis Team

```json
{
  "num_annotations": 64,
  "num_active_assignments": 8,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {
      "title": "Making sociology fun",
      "url": "https://...",
      "assignments": [
        {
          "title": "Assignment One",
          "num_annotations": 15,
          "num_replies_to_recipient": 7
          "num_launchers": 56
        },
        {
          "title": "Assignment Two",
          "num_annotations": 15,
          "num_replies_to_recipient": 0
          "num_launchers": 25
        }
      ]
    },
    {
      "title": "History of jazz music",
      "url": "https://...",
      "assignments": [
        {
          "title": "Assignment A",
          "num_annotations": 4,
          "num_replies_to_recipient": 0
          "num_launchers": 22,
        }
      ]
    }
  ]
}
```

## Next iteration assignment links

This is the same as the previous course breakdown except that the assignment titles are linked to the assignment's pages within the LMS's. This will probably actually be multiple separate iterations: we'll probably ship course links for each LMS separately (Blackboard, Canvas, Brightspace, ...).

```json
{
  "num_annotations": 64,
  "num_active_assignments": 8,
  "lms_name": "Hypothesis University",
  "lms_url": "https://hypothesis.instructure.com/",
  "courses": [
    {
      "title": "Making sociology fun",
      "url": "https://...",
      "assignments": [
        {
          "title": "Assignment One",
          "url": "https://...",
          "num_annotations": 15,
          "num_replies_to_recipient": 7
          "num_launchers": 56
        },
        {
          "title": "Assignment Two",
          "url": "https://...",
          "num_annotations": 15,
          "num_replies_to_recipient": 0
          "num_launchers": 25
        }
      ]
    },
    {
      "title": "History of jazz music",
      "url": "https://...",
      "assignments": [
        {
          "title": "Assignment A",
          "url": "https://...",
          "num_annotations": 4,
          "num_replies_to_recipient": 0
          "num_launchers": 22,
        }
      ]
    }
  ]
}
```

**Comment by seanh** [comment]
^ We discussed the iterations proposed above in the product meeting today. Some notes:

* We want to ship _something_ (some kind of minimal email template) to a small cohort of test users ASAP and start gathering feedback
* We might be willing to ship the second or third iteration (just the total number of annotations and the name of the LMS instance, maybe linked)
* But the real target that we want to shoot for at first is the fourth iteration (per-course breakdown) as we think this is the point at which it starts to become genuinely useful to users
* We don't want to spend time discussing the further iterations after that yet: what priority order we'd do them in (it probably doesn't matter), how we'd implement them, etc. We're more focused on getting the per-course breakdown shipped to users ASAP so we can begin gathering feedback. Once we ship that and product are in that gathering feedback stage developers will then have breathing time to do implementation planning about the future iterations.
