### ISSUE TITLE
Discuss/prototype UI for editing assignment configuration

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#4928]
In non-Canvas LMSes there is no way to edit the configuration for an assignment after it is created. Adding such an ability would solve various problems, especially in cases where the assignment was copied from a previous course and might require editing before it is ready for students to use in the new course.

Some issues we need to look into are:

1. How does an instructor initiate editing an assignment's configuration? An "Edit" button in the grading bar? What about non-gradable activities?
   - Current plan is to add an Edit button in the grading toolbar, and display it always, with the option to minimize it to save space.
3. What happens if the instructor attempts to change the document or groups configuration after annotations have already been made? Do we for example show a warning and allow them to continue after a confirmation?
5. What happens after the assignment configuration is updated? Can we immediately launch the assignment in viewing mode with updated settings, or will we require a page reload?
6. What properties of an assignment do we need to support editing? The same ones that can be configured in the initial creation UI (content, which group set to use if any)?
   - Initially the content selection and the groups
8. We probably need to re-design the current assignment creation UI to support editing just one aspect of the assignment. Currently the flow is a "wizard" where the user first picks the content, then the groups, in that order.
   - Lyza has a design for a vertically-tabbed UI that might work here. We could add tabs for "Content" and "Groups". A simpler variant is just to display the current content and groups selection, like the last page of the file picker UI does.

Sub-tasks:

- [ ] Add a per-instance feature flag to support editing assignments ([Slack thread](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1675178152057449))
- [ ] When the flag is enabled, display an Edit icon in what is currently called the "grading toolbar"
- [ ] When the flag is enabled, display the grading toolbar even if editing is not enabled, but without the grading UI elements
- [ ] When the "Edit" icon is clicked, open a modal dialog with "Save" and "Cancel" actions.
- [ ] When modal dialog initially opens, display the current content selection and groups (TBD: How will the client get the configuration it needs for this? See https://hypothes-is.slack.com/archives/C1MA4E9B9/p1675350353334369)
    - For an initial prototype, we can just add the `filePicker` config to all LTI launches if the flag is enabled
- [ ] Add the ability to change the content selection
- [ ] Add the ability to change the groups selection
- [ ] Actually save changes when "Save" is invoked
   - Until we get to figuring out what happens with existing annotations, we can ignore this step
- [ ] Reload the assignment to reflect the latest configuration after saving changes (TBD: How are we going to get that configuration and re-launch the frontend app?)
   - For an initial prototype, we can just tell the user to reload the page after saving changes
- [ ] Warn when exiting the dialog if there are unsaved changes

**Comment by seanh** [comment]
We did a spike for the [Instructor Email Digests](https://github.com/orgs/hypothesis/projects/107) project recently: [Spike: how can we tell which assignment an annotation belongs to?](https://github.com/hypothesis/lms/issues/4911). In particular, from that spike:

> Currently annotations are only associated with documents, not with assignments.
> 
> * If you create two assignments for the same document all the annotations created in one assignment will appear in the other assignment, because the annotations are associated with the document not with the assignments. (This is only true if the assignments are both in the same course and use the same course group, section or Canvas group. Assignments for the same document in different courses don't see each other's annotations because different courses have different groups.)
> * If you edit an assignment and change its document then all the assignment's annotations disappear. Of course the annotations would no longer anchor if the assignment has been changed to a different document with different text. But you might hope that they'd still appear as orphans. In fact the annotations are completely gone because they're associated with the document not the assignment.

The proposed solution, which we may yet end up needing for the Instructor Email Digests feature anyway, was to add special "Assignment URIs" to annotations that uniquely identify the assignment itself rather than the assignment's document. The LMS could inject the assignment URI such that the client will pick it up and include it in the annotation's URIs when annotating. Then if the client retrieves annotations using these assignment URIs then two assignments for the same document would not see each other's annotations, and an assignment whose document changes would not lose its annotations (although they may become unanchored).

In the case of two assignments for the same document we may need to be careful to prevent document equivalence from deciding that the two assignment URIs are equivalent.

**Comment by robertknight** [comment]
https://www.notion.so/Copy-course-06b9d109ca1244a59d9deed1e3c7a8fd has some notes about workflows and links to sketches on miro.com.

**Comment by robertknight** [comment]
> The proposed solution, which we may yet end up needing for the Instructor Email Digests feature anyway, was to add special "Assignment URIs" to annotations that uniquely identify the assignment itself rather than the assignment's document.

Hmm... depending on whether an assignment edit has logically changed the content or not (ie. is it "the same content" as far as the user is concerned, or a URL that looks different to us, but is the same as far as the user is concerned), that could be either helpful or confusing to have annotations "move across" to the new content. If you significantly change the content at a URL, you're likely to end up with a mix of Orphans and cases where the client has tried to anchor quotes to the best match on the page and found something textually vaguely similar but semantically unrelated to the original annotation context.

An alternative to abusing document URI manipulation for this purpose might be to introduce some kind of alternative "context ID/URI" that can be used as an additional filter to control which annotations are displayed.

If we did introduce some mechanism to isolate annotations between assignments, that would also be a potential solution for separating annotations from different chapters in books (see https://hypothes-is.slack.com/archives/C01B9TRVATZ/p1674854942709149).

**Comment by robertknight** [comment]
Another problem with abusing the document URI as a way to segregate annotations between assignments is that it will make it difficult to create views/queries (for internal or external use) over which content is being annotated, or to support things like exporting annotations for use outside the LMS.

**Comment by robertknight** [comment]
> How does an instructor initiate editing an assignment's configuration? An "Edit" button in the grading bar? What about non-gradable activities?

In cases where we don't show this UI today, we could make the grading bar available but without the grading elements. A downside is that this will take away vertical space from the content. Perhaps we could resolve that by adding an affordance to collapse/expand the toolbar, or we could just decide that the amount of space lost isn't significant.
