### ISSUE TITLE
Final wording for the "Can't find file" modal in D2L

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#4946]
Slack thread: https://hypothes-is.slack.com/archives/C04JRP516GG/p1678373845421789?thread_ts=1678361298.854569&cid=C04JRP516GG

Current placeholder looks like:

![Image](https://user-images.githubusercontent.com/1433832/215786255-c1daa094-5cc4-4434-9eb9-b2f9da3c0ba1.png)

The final version might have to:

- Include links to KB articles / D2L docs
- Mention course copy (and maybe also link to articles around that)

**Comment by marcospri** [comment]
Placeholder copy for the student and instructor versions:

Note that `If the problem persists, you can open a support ticket or visit our help documents.` is part of both versions. If we want to change that it a bit more complex so I rather get a version out and tackle that separately if we wan to do so.


## Instructor

```
Title: Hypothesis couldn't find the file in this course

This might have happened because:
- The file has been deleted from D2L
- The course was copied and the selected one is not in the new course.

To fix the issue recreate the assignment with a different file. Also check our document
Using Hypothesis With D2L Course Content Files(https://web.hypothes.is/help/using-hypothesis-with-d2l-course-content-files/)

If the problem persists, you can open a support ticket or visit our help documents.
```

## Student
```
Title: Hypothesis couldn't find the file in the course

This might have happened because:
- The file has been deleted from D2L
- The course was copied and the selected is not in the new course.

Please constant the course instructor pointing to this assignment. 

If the problem persists, you can open a support ticket or visit our help documents.
```

**Comment by nairiboo** [comment]
Instructor one looks good to me.

For the student one a couple of points:

Title: Hypothesis couldn't find the file in the course

This might have happened because:
- The file has been deleted from D2L
- The course was copied and the selected **one** is not in the new course.

Please **contact** the course instructor pointing **them** to this assignment. 

If the problem persists, you can open a support ticket or visit our help documents.
