### ISSUE TITLE
Ship the first testable implementation of instructor email digests

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#4954]
* **We won't worry about scale** (whether our implementation will work for thousands or tens-of-thousands of users). We want to ship something to a small set of users ASAP and verify the feature (https://github.com/hypothesis/lms/issues/4897)

* **We won't worry about email digests for general h users**. Again: we want to ship something to a small set of LMS users ASAP.

* **We won't worry about success metrics**. Again: we just want to ship something ASAP. We'll then be able to collect feedback from users, metrics that we already have access to, etc. (https://github.com/hypothesis/lms/issues/4900)

* **We'll ship something much simpler than the "final draft" of the email subject and body** (which was in this [google doc](https://docs.google.com/document/d/1e_CB4uEwAVM6MVqFrbMDtQ1Pd4ZtkII5gmTVfqhF1gs/)). We can then iterate on it (as separate issues from this card). (https://github.com/hypothesis/lms/issues/4915#issuecomment-1405352481)

  The first template that we'll ship will be:

  > **Subject:** There has been some activity in Hypothesis
  > 
  > **Body:**
  > 
  > Hi,
  > 
  > Your students made 34 annotations in assignments yesterday. Let your students know about the activity to encourage the ongoing conversation.
  > 
  > **Making sociology fun**  
  > Students made 30 annotations in assignments.
  > 
  > **History of jazz music**  
  > Students made 4 annotations in assignments.
  > 
  > Hypothesis Team

* **We won't worry about future iterations of the email template** yet (how to generate the data for links to courses, counts of replies, counts of launchers, assignments). We can figure those out if/when we get to them. We are planning to add LMS names and links (https://github.com/hypothesis/lms/issues/4955) and a per-course breakdown (https://github.com/hypothesis/lms/issues/4956) in quick follow-up iterations after this card. But we won't worry yet about architecting this beyond that. (https://github.com/hypothesis/lms/issues/4915#issuecomment-1410783436)

Done when:

- [x] Daily email digests are being sent ([between midnight and 5AM EST](https://github.com/hypothesis/lms/issues/4902)) to participating instructors with the email template and contents as described above
- [x] The feature is only available to institutions that have the institution-level email digests feature flag enabled (i.e. don't send emails to instructors from other institutions)
- [x] The emails cover all activity for the past 24hrs (since the last email), regardless of whether the user has already launched some assignments and potentially already seen some of the activity  
  (https://github.com/hypothesis/lms/issues/4898)
- [x] We can use Mailchimp templates to vary the wording of the emails  
  (https://github.com/hypothesis/lms/issues/4952)
- [x] Instructors at participating institutions are automatically subscribed to email digests for their courses  
  (https://github.com/hypothesis/lms/issues/4901)
- [x] Instructors can unsubscribe from email digests by clicking a link in the footers of the email themselves  
  (https://github.com/hypothesis/lms/issues/4903, https://github.com/hypothesis/lms/issues/4916)
- [x] The email digests don't include courses in which the user isn't an instructor
- [x] The email digests don't include the user's own annotations  
  (https://github.com/hypothesis/lms/issues/4925)
- [x] It doesn't send multiple emails to the same user when an institution has multiple application instances  
  (https://github.com/hypothesis/lms/issues/4953)

**Comment by darylhedley** [comment]
Looks good to me!

**Comment by seanh** [comment]
I've updated the description above to reflect a decision we agreed in yesterday's project meeting: the email digest for the first version will contain a per-course breakdown of the annotation counts with the course titles, rather than merely saying <q>Your students made 64 annotations in assignments yesterday</q> without saying which courses the annotations were in.

The reason for this change is that in order to say <q>Your students made 64 annotations in assignments yesterday</q> we actually need to figure out which course each of the 64 annotations belongs to because we need to avoid counting any annotations from courses in which the user isn't an instructor (since the same user can be an instructor in some courses and a learner in others). Once we've done that work of finding the course for each annotation we may as well do the per-course breakdown: it's hardly any more work.
