### ISSUE TITLE
Create endpoint for listing user's files in the LMS app

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#500]
This is a follow-up from https://github.com/hypothesis/lms/issues/470.

Create a backend endpoint (provisionally `/lms_files`) which lists the files that the user has access to within their LMS's cloud storage. There is a dummy implementation in the file picker prototype: https://github.com/hypothesis/lms-file-picker-prototype/blob/master/src/server/index.js

**Request**

```
GET /lms_files?path={path}
```

Where `path` is the directory path within the LMS's app's storage and defaults to `/`. Authorization should use whatever system we agree for communication between the LMS frontend and backend.

**Response**

If successful, 200 OK with a JSON response of the form:

```ts
interface LmsFilesResponse {
  files: LmsFile[]
}

interface LmsFile {
  type: 'directory' | 'file';
  // URL of an SVG icon to render.
  icon: string;
  name: string;
}
```

**Errors**

- If the user has not authorized the LMS app's access to their file storage, return a 403
- If the path does not exist, return a 404

**Comment by seanh** [comment]
We've tweaked the API design from what's described above, see https://github.com/hypothesis/lms/issues/595#issuecomment-490489929

**Comment by seanh** [comment]
I'm gonna close this as done. Error and edge cases aren't handled yet but I'm creating a separate card for those
