### ISSUE TITLE
Add "back to assignment" affordance to edit-assignment (assignment configuration) view

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#5141]
Instructors could get confused about how to get back to the launched assignment if they want to escape the edit-assignment flow. Add a link or button affordance to get "back" to the launched assignment.

**Comment by robertknight** [comment]
https://github.com/hypothesis/lms/pull/5157 added an initial solution for this in the form of a "Back to assignment" link at the top of the edit view.
