### ISSUE TITLE
Provide UI sketches for "re-select content" screen in edit-assignment workflow

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#5220]
Similarly to how some sketches were provided for the initial view for the edit-assignment workflow, provide some pattern-library sketches for the "re-select content" screen.

**Comment by robertknight** [comment]
Closed per discussion in https://hypothes-is.slack.com/archives/C4K6M7P5E/p1682348172773909. See PRs https://github.com/hypothesis/lms/pull/5211 and https://github.com/hypothesis/lms/pull/5215.
