### ISSUE TITLE
Prevent (re-)delivering RabbitMQ messages to Celery workers that're being terminated

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#5304]
### Problem

In <https://github.com/hypothesis/lms/issues/5241> I observed the following behaviour:

1. RabbitMQ delivers a message to a Celery worker
2. The worker begins executing the task
3. A deployment begins terminating all the current VMs (including the VM on which the worker is executing the task) and replacing them with new VMs
4. The Celery worker process gets suddenly terminated (no grace period) by Elastic Beanstalk in the middle of executing the task
5. RabbitMQ notices that the worker is gone (I think because a TCP connection between the worker and RabbitMQ has been closed)
6. RabbitMQ re-delivers the message to another worker, but it picks one of the other old workers on one of the other old VMs that is being terminated
7. This second worker begins executing the task from the start again but very soon gets terminated by Elastic Beanstalk as well
8. RabbitMQ re-delivers the message to a third worker. This time it chooses one of the new workers on one of the new VMs and the task is able to be executed uninterrupted

Of course this won't happen all the time: sometimes RabbitMQ will pick one of the new workers for the first re-delivery, depending on various factors (other messages in the queue, timings).

It would be better if RabbitMQ could always pick one of the new workers. For example because (as noted in <https://github.com/hypothesis/lms/issues/5241>) there may be a 10-12s delay between a worker being terminated mid-task and RabbitMQ re-delivering the message to another worker. If it ends up having to redeliver twice then that 10-12s delay becomes a 20-24s delay or more.

### Possible Solution: Consumer Priorities

RabbitMQ consumers have priority numbers and Rabbit will always deliver the next message to the highest-priority consumer that is available (and not blocked processing other messages). By default the consumer priority is always `0` so they're all equal but you can set it to any positive or negative number. See:

* https://www.rabbitmq.com/consumer-priority.html
* https://docs.celeryq.dev/projects/kombu/en/stable/userguide/consumers.html?highlight=x-priority#consumer-priorities
* A [thread in the RabbitMQ Slack](https://rabbitmq.slack.com/archives/C1EDN83PA/p1681898435857379) about this

Perhaps we can generate some kind of "deployment number" for each deployment that's always higher than the previous deployment, and pass this deployment number through to the code somehow to be used as the `x-priority`. Or alternatively maybe the code could generate an `x-priority` dynamically based on the current date and time when it connects to RabbitMQ (this would result in varying priorities among workers within the same deployment but that may be fine).

This won't completely prevent messages from being delivered to the workers that're about to be terminated: once all the new (higher-priority) consumers are busy processing messages RabbitMQ will start delivering the next messages to the old (lower-priority) consumers. But at least it should make the problem less likely to occur.

**Comment by nairiboo** [comment]
Won't fix
