### ISSUE TITLE
Add option to use YouTube video as a content source for new assignments

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#5328]
As part of https://github.com/hypothesis/product-backlog/issues/1433, we will need to add a new option to use a YouTube video as a content source for an assignment.

Issues to resolve:

1. What should the design of the picker look like?
2. What forms of URLs / video ID are accepted?
3. What is the form of the assignment URL that the picker generates?

Sub-tasks:

- [x] Add feature flag for YouTube videos as a content option:
  - https://github.com/hypothesis/lms/pull/5335 
  - https://github.com/hypothesis/lms/pull/5354
- [x] Add YouTube video option to content selector when the flag is enabled. Don't worry about any design improvements to that form for this issue
  - https://github.com/hypothesis/lms/pull/5359
- [x] Design + implement initial version of video picker
  - https://github.com/hypothesis/lms/pull/5359
  - https://github.com/hypothesis/lms/pull/5381
 - [x] Improve a bit the general content selector, as there's too many possible contents already (just a short-term improvement. Full redisgn being discussed in https://github.com/hypothesis/lms/issues/2955)

**Comment by acelaya** [comment]
> 3. What is the form of the assignment URL that the picker generates?

We still need to align this point with BE team, but there is a separated issue: https://github.com/hypothesis/lms/issues/5405
