### ISSUE TITLE
Side-by-side mode

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/lms#5386]
[**Notion Link**](https://www.notion.so/Product-03482f93028249738f5305a173a8b99f?p=ac030d09bd224a2abc150d7c8fdbf83c&pm=s)

Project to release side-by-side mode and remove FF.

Need to review how the UI will be handled for the few websites where side-by-side mode might not work (e.g. a toggle in the annotations pane to turn side-by-side mode off or set in preferences).

https://hypothes-is.slack.com/archives/C07NXBDNW/p1681675149376879

Introduce as part of video annotations

**Comment by nairiboo** [comment]
Updated Plan:

- Release before video annotations
- create new FF to release to non LMS users first
- Release to LMS users 2 weeks after non LMS users

**Comment by robertknight** [comment]
We shipped side-by-side mode for non-LMS users a couple of weeks ago, and the roll-out has gone well. We're planning to turn it on for LMS users tomorrow.

**Comment by robertknight** [comment]
This feature is now enabled for all Hypothesis users - https://hypothes-is.slack.com/archives/C4K6M7P5E/p1689149447105099.
