### ISSUE TITLE
Proxy youtube API in LMS to get video details

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#5404]
Use the official youtube API to gather metadata for the filepicker (see: https://developers.google.com/youtube/v3/docs/videos/list)

Try to gather information like: channel title, video title, video thumbnail, video duration.

- [x] Create new credentials to use the youtube API. Isolate them from other keys (ie the ones used for google drive).
- [ ] Be aware of quota costs of the API calls: https://developers.google.com/youtube/v3/getting-started#quota 
    I don't think we have to explicitly track the quota but we should at least make a back of the envelope calculation and request a quota extension to be on the safe side.
- [x] Coordinate with the frontend team to know what data we need and in which format.

**Comment by acelaya** [comment]
FE notes:

The intention is to deal with this similarly to what we do with JSTOR, with the only difference that we can do with just one endpoint, as YouTube API can return everything in one go.

With this in mind, the video ID can be provided by the FE as a route param: `/api/youtube/videos/{video_id}`.

The response could be something in the lines of:

```json
{
  "title": "Hypothesis and Atlassian New Partnership Announced at the Team23 Conference",
  "channel": "Hypothesis",
  "image": "https://i.ytimg.com/vi/EU6TDnV5osM/mqdefault.jpg",
  "duration": ...
}
```

As per how to select the image to return, the endpoint referenced by Marcos returns thumbnails with a structure looking like this:

```
{
  "default": {
    "url": "https://i.ytimg.com/vi/EU6TDnV5osM/default.jpg",
    "width": 120,
    "height": 90
  },
  "medium": {
    "url": "https://i.ytimg.com/vi/EU6TDnV5osM/mqdefault.jpg",
    "width": 320,
    "height": 180
  },
  "high": {
    "url": "https://i.ytimg.com/vi/EU6TDnV5osM/hqdefault.jpg",
    "width": 480,
    "height": 360
  },
  "standard": {
    "url": "https://i.ytimg.com/vi/EU6TDnV5osM/sddefault.jpg",
    "width": 640,
    "height": 480
  },
  "maxres": {
    "url": "https://i.ytimg.com/vi/EU6TDnV5osM/maxresdefault.jpg",
    "width": 1280,
    "height": 720
  }
}
```

I would propose we select one of them, perhaps the `standard` one, as it has a good balance on having a reasonable quality, but not being too big.

**Comment by acelaya** [comment]
Some extra thoughts. We have also discussed letting the teachers select the language of the transcript, instead of trying to pick up one by ourselves.

This would involve returning the available transcript languages here as well, so that we can present a dropdown/list of some sort from which to pick the language.

Also, there might be cases in which a potentially valid YouTube video is not eligible for an assignment. For example, videos with age restrictions won't be supported for the MVP, so we need to handle that somehow as well.

**Comment by acelaya** [comment]
> * Be aware of quota costs of the API calls: https://developers.google.com/youtube/v3/getting-started#quota
> * Returning the available transcript languages
> * There might be cases in which a potentially valid YouTube video is not eligible for an assignment. For example, videos with age restrictions won't be supported for the MVP, so we need to handle that somehow as well

We have draft entries and issues on the video annotations board to follow-up on these topics, so I'll close this issue.
