### ISSUE TITLE
Handle language preference while picking a video in LMS

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#5406]
**We are not doing this for v1. We'll rely on Via picking English for all videos.**

Currently via prefer English captions when available.

Ideally the language of the captions could be selected while creating the assignment and be the same for all the users that access the assignment.

- Gather the available captions for a given videos.

This has the extra complication of using the unsupported API on the via side. We should either use the same API to gather the languages in LMS or if using the official API make sure that the options match between the two.

- Expose the options to the frontend/user
- Expose the selected language to Via

**Comment by seanh** [comment]
Closing this in favour of https://github.com/hypothesis/lms/issues/5591 and https://github.com/hypothesis/lms/issues/5592 (although those cover only the backend parts, we'll need to create frontend issues as well at some point)
