### ISSUE TITLE
Handle assignments created with a YouTube URL using the regular `URLPicker`

### ISSUE THREAD

**Issue by acelaya** [hypothesis/lms#5499]
Right now we are using raw YouTube URLs for video transcript annotation assignments.

This means, the regular `URLPicker` can be "accidentally" used to provide a YouTube URL, with the problem that this picker does not validate the video actually exists and does not have any restrictions that would prevent its proper usage in via's video app (age-restricted, non-embeddable, etc).

There are a couple of things we could do:

1. When a YouTube URL is introduced in the `URLPicker`, we could "warn" the user and suggest switching to the proper content picker with a CTA.
2. Similar to the above, but we just display an error and prevent the user from continuing with saving the assignment.
3. Considering we are already planning to move to a smarter content picker at some point, we could just not do anything for now.

**Comment by robertknight** [comment]
> Similar to the above, but we just display an error and prevent the user from continuing with saving the assignment.

I would suggest we do this as an initial step, since it is easy to implement and it ensures that we run all of our checks of whether the video is usable before the assignment is launched. As an improvement upon that, we can add migration from the default URL picker to the dedicated one.
