### ISSUE TITLE
Remove confusion when instructors use Canvas course site copying tool

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#555]
### Background
LMSes generally allow instructors and admins to copy or "clone" the content course sites— this is useful if a professor is teaching multiple sections of the same course, reusing materials from a previous year, or if a department wants to easily disseminate reading materials to multiple instructors for use (especially popular for online courses which have standard sets of content). This copying process generally includes files, folders, and installed apps; it does not usually involve membership. 

### Use case
We just [got a report from a user](https://hypothesis.zendesk.com/agent/tickets/4171) who added Hypothesis at the account level in Canvas and built a master course site including Hypothesis-enabled readings (all using the Canvas file picker). 

When he went into one of the "clone" sites as an instructor, he was able to launch all of the Hypothesis-enabled assignments that had been copied over. When launching as a student user, he saw: 
![2019-04-23_9-40-02](https://user-images.githubusercontent.com/12087705/56588468-66cf7700-65b1-11e9-9574-332a918cd040.png)

In order to get these assignments working for student users, he had to edit each assignment and reconfigure it. 

Essentially, our Hypothesis assignments are being copied over as "placeholders." There may be additional work we can do to so that they "just work" after a course site is copied. 

### To research
- How do the various LMSes we support handle copying course content which is brought in from external apps? Will the other LMSes bring over the "placeholder" assignments like Canvas did? Does assignment launching "just work" after copying in any other LMSes?
- Is there a difference in how copying works between assignments created with the Canvas file picker / Google Drive picker / public URL options?
- Is it possible for us to carry over the document URL associated with a Hypothesis-enabled assignment to a new course site?

**Comment by klemay** [comment]
Update from user: 

> I discovered that when I provided a student in the copied course access to the original master course, he could access the assignment within the copied course.  This leads me to believe that when the master course is copied, the link to the hypothesis assignment remains the same (it links to the pdf file used in the master course instead of linking to the pdf created in the copied course).

**Comment by mkdir-washington-edu** [comment]
Other requests:
https://hypothesis.zendesk.com/agent/tickets/7291

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/7958

**Comment by mkdir-washington-edu** [comment]
Note from https://hypothesis.zendesk.com/agent/tickets/9903 - A Canvas user using course copy didn't have their Hypothesis Assignment rubric copy over. Canvas course copy already works sporadically with Hypothesis, and rubrics with External tools need a work around, so this is something to look at when the time comes.

**Comment by jeremydean** [comment]
While I want to be wary of proposing solutions to problems instead of just articulating them as problems, I'm a little concerned about the "remove confusion" emphasis here.

We can of course train folks to not copy Hypothesis assignments from one course to another.

But for better or worse the expectation that LMS users have is that course can be copied and the tools and content with them.

So I would love to see us explore how we can _support_ course or assignment copy in its various forms.

From Stanford:

> We know that our instructors heavily depend on the course copy feature in Canvas and know for certain that they will import Hypothesis assignments into the new course next quarter, expecting it to work as it did in the previous quarter. It is going to be a huge pain point for our instructors when we tell them that if they plan to use Hypothesis, they cannot rely on the course copy feature in Canvas, but instead they will need to recreate each assignment from scratch every time they offer a course. The fact that imported Hypothesis assignments functioned fine for a certain amount of time and then suddenly stopped working — gave instructors, who are currently making use of Hypothesis this quarter, an false sense of security that they were using a stable and reliable tool.I really hope your team is open to addressing the usability issues I described above. If they are unwilling to address the noted issues, we cannot support broader use of your product on our campus.

**Comment by klemay** [comment]
When instructors use course copy, the experience "breaks" in different ways depending on the LMS. 

- In Canvas, assignments in the new course work for instructors but are intermittently broken for students. ([Repro](https://github.com/hypothesis/support/issues/146#issuecomment-705693916))
- In Blackboard, the link to the Hypothesis-enabled reading appears broken for instructors (meaning, you can't click on it) and does not show up at all for students ([Repro](https://github.com/hypothesis/support/issues/146#issuecomment-706360142))
- In Moodle, the instructor can click on the link in the new course, but they will be asked to re-link the document or webpage to the assignment ([Repro](https://github.com/hypothesis/support/issues/146#issuecomment-706363912))

Note that our Blackboard AMI has recently been refreshed and the support team is working on adding the Hypothesis app to the new instance, so testing in Canvas and Moodle will be easier for the time being. 

The fact that Hypothesis assignments break with course copy is problematic in all LMSs, but we are seeing the highest volume of support tickets for Canvas, which is why this issue refers to Canvas specifically. If there is a way to fix this for all LMSes, that's ideal, but if not, I will create separate issues for our other LMSs.
