### ISSUE TITLE
Verifying student access through VS pay

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#5587]
We are working with VitalSource towards the sale of a SKU for Hypothesis to be added to a course. 

Instructor would require Hypothesis for the course. Students would pay through VitalSource, individually or through Inclusive Access. 

Hypothesis would work with the institution to install Hypothesis at the course level. 

**_But Hypothesis will need a way to get students who have not paid for the tool._** 

@jmferr0608 has experience with this workflow through Labster

**Comment by jeremydean** [comment]
[PRD](https://docs.google.com/document/d/1TX4MvBx_gehtzmnJndQCFlvDqKCBM2GhlCSfoM9kDHU/edit#heading=h.gjdgxs)

**Comment by robertknight** [comment]
VitalSource student pay has now been shipped. @marcospri knows more about the details of how this was actually implemented in the end.
