### ISSUE TITLE
Representing Assignments in Annotations

### ISSUE THREAD

**Issue by leedenison** [hypothesis/lms#5593]
Write a proposal for how to represent assignments in annotations.

**Comment by marcospri** [comment]
This are now stored on annotation_metadata https://report.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgY291bnQoKikgZnJvbSBhbm5vdGF0aW9uX21ldGFkYXRhIiwidGVtcGxhdGUtdGFncyI6e319LCJ0eXBlIjoibmF0aXZlIn0sImRpc3BsYXkiOiJzY2FsYXIiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319
