### ISSUE TITLE
Add more auto-embed options

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/lms#5603]
We currently allow for users to paste a YouTube URL into an annotation and embed the video.

We should do this for other embeddable links like Vimeo, SoundCloud and others.

**Comment by robertknight** [comment]
We already support Vimeo. The current complete set of recognized URL formats can be found at https://github.com/hypothesis/client/blob/6ebeef981b23a2df70fe5168b5938966a7811656/src/sidebar/media-embedder.ts#L184.

This currently includes:
- YouTube
- Vimeo
- Flipgrid
- Various archive.is URLs
- Any URLs ending with recognized audio extensions (eg. `.mp4`)
