### ISSUE TITLE
Warn instructor in case of page refresh/change during grading

### ISSUE THREAD

**Issue by acelaya** [hypothesis/lms#5672]
This issue is part of https://github.com/hypothesis/product-backlog/issues/1472. As part of grading comment implementation we have realized that, if the instructor refreshes the page or changes it, they could loose any unsaved data.

In order to mitigate this, try to use whatever native browser API is available to capture these changes and warn the instructor if so.

**Comment by acelaya** [comment]
I think the `window`'s `beforeunload` event is what we want to use https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event

**Comment by robertknight** [comment]
That looks right to me. I see that page has some recommendations related to performance that we need to be aware of.
