### ISSUE TITLE
Forward annotation metadata from the LMS backend to the H backend via the client

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#5698]
The LMS backend is going to generate an opaque set of metadata to store alongside annotations.

To communicate that to the H's service in the LMS context the LMS backend is going to expose a config option to the LMS front end which should be used by the client to finally pass it to the H's server.

Based on:

https://github.com/hypothesis/h/pull/8175
https://github.com/hypothesis/h/pull/8182
https://github.com/hypothesis/lms/pull/5697

---

https://github.com/hypothesis/lms/pull/5697 defines a new client configuration options which includes includes an opaque dictionary with LMS specific data.

That dictionary should be forwarded to H's API as the `metadata` key in the API, following the changes made in https://github.com/hypothesis/h/pull/8175

**Comment by robertknight** [comment]
See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1696584492777979 for updated details on what the LMS frontend and client need to do.
