### ISSUE TITLE
Support canvas pages as a document source

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#5713]
See:
-  #5703 
-  #5710 

TODO:

- [x] New AI setting for the feature
- [x] Expose canvas "file" picker settings to the front end
- [x] Show a new option in the file picker for Canvas Pages
- [x] Proxy page listing endpoints to get a list of pages relevant for the current course
- [x] Handle documents using Canvas Pages (to be broken down further as we progress)

**Comment by marcospri** [comment]
See progress over the board at: https://github.com/orgs/hypothesis/projects/126/views/1

**Comment by robertknight** [comment]
This is now shipped.
