### ISSUE TITLE
Determine why lms.views.lti_launches:lti_launches is slow between lms and h services

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/lms#572]
The request to h.views.api.users:update takes up to 8 seconds to respond, since it does not take this long in h, this must be network time. There is a potential fix in-progress that hopefully will fix this https://github.com/hypothesis/playbook/issues/196. This will need to be verified after the switch.
![image](https://user-images.githubusercontent.com/30059933/56995225-01056100-6b56-11e9-869f-716dcbc51388.png)
[detailed trace in New Relic](https://rpm.newrelic.com/accounts/1385283/applications/76030703/transactions?tw%5Bend%5D=1556660256&tw%5Bstart%5D=1556055456#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f6c6d732e76696577732e6c74695f6c61756e636865733a6c74695f6c61756e63686573222c22225d&app_trace_id=740c4403-6a49-11e9-93d3-0242ac11000f_0_2695)

More than 3% of all lti launch requests per week experience a launch time > .5s.

![image](https://user-images.githubusercontent.com/30059933/56997205-e0d8a080-6b5b-11e9-815d-0744a1dd45a4.png)

**Comment by seanh** [comment]
Some things we want to do to get to the bottom of this:

- [ ] Install New Relic's load balancer integration: https://github.com/hypothesis/playbook/issues/192
- [ ] Also install other New Relic Infrastructure integrations, such as EC2 and nginx. These should give us better insight into what's happening
- [ ] If the h application servers themselves are a bottleneck, we may give lms its own separate h app servers or configure nginx to let lms requests through immediately

**Comment by dmfine** [comment]
New Relic AWS integrations are loaded, we need to make dashboards to make them easy to use. I'll install agents for nginx next.

**Comment by hmstepanek** [comment]
Unfortunately, I wasn't able to track down a specific lms request in the AWS load balancer logs we captured this week, despite capturing a slow lms request in New Relic. Looking at the logs, it does look like there is a delay in the nginx-gunicorn layer for many requests (some of which I would expect while others I would not) which leads me to believe the occasional slowness of lms requests may be due to nginx rate limiting. Because we really shouldn't be rate limiting internal lms requests made directly to h anyway, I'm going to go ahead and file a ticket to white list lms requests in nginx and close this for now. I'd also like to look into more informative monitoring tools for nginx.

**Comment by hmstepanek** [comment]
ticket for white listing lms requests in nginx: https://github.com/hypothesis/h/issues/5649 @dmfine
