### ISSUE TITLE
Slow oath_state select query

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/lms#573]
The following select query can take > 1s to run.
![image](https://user-images.githubusercontent.com/30059933/56996321-02845880-6b59-11e9-9a6c-1664c780a591.png)
![image](https://user-images.githubusercontent.com/30059933/56996333-0912d000-6b59-11e9-9e17-032d087fbc9e.png)
![image](https://user-images.githubusercontent.com/30059933/56996407-51ca8900-6b59-11e9-9056-a60e2723dec6.png)

[detailed trace in New Relic](https://rpm.newrelic.com/accounts/1385283/applications/76030703/datastores?tw%5Bend%5D=1556661520&tw%5Bstart%5D=1556056720#/overview/Postgres/drilldown?metric=Datastore%2Fstatement%2FPostgres%2Foauth_state%2Fselect)

**Comment by seanh** [comment]
I'm gonna close this as we're very close to releasing a feature that, once released, will enable us to delete this code and DB table
