### ISSUE TITLE
Quick & dirty integration of new file picker UI into app

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#576]
Implement the prototype UI from <https://github.com/hypothesis/lms/issues/470> into the LMS app in a quick and dirty way. For example make the prototype UI appear instead of the hacky one when a teacher creates an assignment in Canvas _if the `"new_oauth"` feature flag is on.

This just needs to get the prototype UI into the app so that backend components (popup window, files API, ...) can be tested and demoed end-to-end.

Does not require the UI to be brought up to production quality, have tests, etc.

There's another card for polishing off the quality and everything: https://github.com/hypothesis/lms/issues/502

**Comment by robertknight** [comment]
This was implemented in https://github.com/hypothesis/lms/pull/593. The landed implementation does have tests what I hope is production quality code, so we won't have to go back and do that later.
