### ISSUE TITLE
Confirm that the LMS app works with "name_only" LTI privacy

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#579]
We should be able to work with the `<lticm:property name="privacy_level">name_only</lticm:property>` in https://lms.hypothes.is/config_xml set to `name_only` or even `anonymous` (although then we'll need to use LTI user IDs, rather than names, as user names).

I couldn't find any documentation of this `privacy_level` field and whether it's a Canvas thing or an LTI thing. As well as setting it in `config_xml` it can be customised by users, on a per-install basis, by editing an instance of our app in Canvas.

**Comment by seanh** [comment]
On [this Canvas page](https://canvas.instructure.com/doc/api/external_tools.html) `privacy_level` is documented as a required external tool ("LTI link") config param, "What information to send to the external tool", and can be  `“anonymous”`, `“name_only”` or `“public”`. I can't find it in the LTI spec though.

**Comment by klemay** [comment]
Some added context below. The TL;DR is that one institution edited our XML to to set the privacy level to `name_only` and the app worked in their tests. We want to do some research to ensure they won't run into problems if they roll this out to instructors.

The long version: 

In Canvas, users run into `privacy_level` during the app installation process at the point where they enter their Hypothesis credentials + the config URL. It's presented here:

![canvas_privacy_level](https://user-images.githubusercontent.com/12087705/57241459-07d11f80-6fff-11e9-8353-581c32572ed7.png)

As Sean noted above, the options presented in the dropdown are Public (`"public"`), Name Only (`"name_only"`) and Anonymous (`"anonymous"`) [as documented here](https://canvas.instructure.com/doc/api/external_tools.html). 

Sean is right that this isn't Canvas-specific. A partner institution provided this helpful info:

> Most LTI applications should be able to work without setting the privacy to "public." The "anonymous" option is usually sufficient, even for apps that utilize grade pass back. IMS, the body that governs LTI, states as much: 
> 
> "Any fields that contain user identifiable information such as the user's name or e-mail address are optional and may or may not be included in launch data at the discretion of the administrator, instructor, or even student. Tool Providers should be prepared to handle situations where this data is not provided. In particular, the user's E-Mail address is considered optional and should not be used as a primary key for a user record in the Tool Provider." https://www.imsglobal.org/basic-overview-how-lti-works.
> 
> Just about every LTI developer configures their app to "public" by default, even though they do not need all of the information that this setting provides in order for the tool to work.

This institution was able to get the app working with `name_only`: 

>  I grabbed the XML code that your config URL points to, edited the privacy setting and added the LTI via the "paste XML" method with the key and secret I generated from your site. I tried using "anonymous" but the comments were marked as such (obviously not useful). The "name_only" setting tags the comment with the correct user. Here's what the app looks like in my demo course using "name_only" privacy: https://www.screencast.com/t/5Ce4ak4Xub. The file picker worked just fine and oAuth worked as expected. The LTI does still pass the user's **internal** Canvas ID and course context, which will allow them to do anything they need with the app.

...but we want to do due diligence to make sure they wouldn't run into issues if they rolled this out to instructors.

**Comment by seanh** [comment]
There are actually four privacy settings in Canvas: public (what our app currently uses by default), name only, email only, and anonymous:

![Screenshot from 2019-07-11 13-46-45](https://user-images.githubusercontent.com/22498/61055991-86c14a80-a3ea-11e9-97c0-a49c69ae0eaa.png)

## Overall conclusion

Our app will work exactly the same with privacy set to name only as it will with public. While we _can_ work with name only privacy, I'm not sure that we want to _encourage_ users to use this setting, since it means we don't get an image or email address for the user, so we have no way to contact the user. We don't use these fields currently but might want to in future.

Our app is broken with email only or anonymous privacy because all the users appear as "Anonymous" and you can't tell them apart.

## Setting privacy to email only or anonymous will change the student names on existing annotations to "Anonymous"

If a teacher or admin edits their installation of our app in Canvas and changes the privacy setting to email only or anonymous then, the next time a given student launches any assignment that uses our app, it will **change that student's name to "Anonymous" on all their past annotations** across all assignments and **across all courses**.

It only does one student at a time, so for every student to be change to "Anonymous" every student would have to launch our app.

If the privacy setting is changed back to public or name only then the next time a student launches us their name on all their annotations will be fixed but again only for one student at a time.

So "experimenting" with setting our app to email only or anonymous is a very bad idea.

## name only privacy

The difference between public and name only privacy is that with name only:

* The `lis_person_contact_email_primary` param is missing. This is the user's email address. We don't use this param currently.
* The `user_image` param is missing (URL to an image of the user). We don't use this param currently.
* Various custom Canvas params are missing, some of which seem quite unrelated to privacy:
  * The `custom_canvas_assignment_id` param is missing (this is an opaque but predictable-looking assignment ID, e.g. `463`). We don't use this param. 
  * The `custom_canvas_user_id` param is missing (this is an opaque but predictable-looking user ID, e.g. `33`). We don't use this param.
  * The `custom_canvas_user_login_id` param is missing (this is what the user used to login to Canvas, I believe it can be either a username or an email address). We don't use this param.
  * The `custom_canvas_workflow_state` param is missing (not sure what this is, example value: `['available']`). We don't use this param.

Conclusion: Our app will work exactly the same with privacy set to name only as it will with public. While we _can_ work with name only privacy, I'm not sure that we want to _encourage_ users to use this setting, since it means we don't get an image or email address for the user, so we have no way to contact the user. We don't use these fields currently but might want to in future.

## email only privacy

* Unlike with name only, the `lis_person_contact_email_primary` param is present.

* The `lis_person_name_family`, `lis_person_name_full`, and `lis_person_name_given` params are missing. These are the params that we use to generate the user's name, for displaying on their annotations etc. When these are missing we show the user's name as "Anonymous". This means that all users will be called "Anonymous" so you won't be able to tell one person's annotations from another's.
* The same `custom_canvas_*` params are missing again
* `user_image` is missing

Conclusion: Our app is broken with email only privacy because all the users appear as "Anonymous" and you can't tell them apart.

## anonymous privacy

* `lis_person_contact_email_primary`, `lis_person_name_family`, `lis_person_name_full`, and `lis_person_name_given` are all missing, so all the users will be called "Anonymous".
* The `custom_canvas_*` params are missing
* `user_image` is missing

Conclusion: Conclusion: Our app is broken with anonymous privacy because all the users appear as "Anonymous" and you can't tell them apart.
