### ISSUE TITLE
Remove duplicate env.py file

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#6]
[alembic/env.py](https://github.com/hypothesis/lms/blob/master/alembic/env.py) was added, but [lti/migrations/env.py](https://github.com/hypothesis/lms/blob/master/lti/migrations/env.py) already existed. I think `alembic/env.py` is a dup and should be removed?

**Comment by seanh** [comment]
It looks like the `alembic.ini` file was also removed from the `conf` dir, and added to the root dir?

**Comment by dittonjs** [comment]
@seanh we did move the alembic.ini file from the conf directory to the root because if it is in the root then you dont have to specify the ini file when you run alembic. We can move it back if you prefer?

**Comment by seanh** [comment]
Ah right, you might have to update the example in the README file, but happy to leave the ini file moved
