### ISSUE TITLE
Display a better error for max-submissions-reached scenario in Canavs

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#6388]
Improve the display of the error added in https://github.com/hypothesis/lms/pull/6295, which occurs when creating a grading submission fails in Canvas due to the max submissions limit having been reached.

Slack thread: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1719220175035739.
Related to https://github.com/hypothesis/support/issues/110.

**Comment by marcospri** [comment]
Done in https://github.com/hypothesis/lms/pull/6390
