### ISSUE TITLE
Google Picker popup is blocked by browsers

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#64]
When a user clicks on *Use Google Picker* nothing happens, because the browser blocks the popup:

![peek 2017-12-15 12-31](https://user-images.githubusercontent.com/22498/34042970-e516e95e-e196-11e7-8789-e6865bcffb07.gif)

**Comment by robertknight** [comment]
I think this should be a high priority issue. I found this pretty confusing this morning using the Google file picker for the first time.

**Comment by seanh** [comment]
I agree. For now I've created a "high priority" label in this repo so we can track the ones we think are high pri

**Comment by robertknight** [comment]
Closed by https://github.com/hypothesis/lms/pull/261
