### ISSUE TITLE
Don't show empty entries in assignment filter

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#6456]
It can happen (@marcospri can you confirm how?) that we are missing a title for an assignment. This currently results in a blank item in the assignments filter drop-down. See the half-height item at the bottom of the list:

<img width="673" alt="Blank assignments" src="https://github.com/user-attachments/assets/60f39c3c-1809-483a-8202-c305159776fd">

The simplest solution is to omit these entries.  An alternative solution we can implement if it becomes sufficiently important would be to display "Untitled assignment" (or similar), with some additional information to disambiguate different entries if we have multiple.

**Comment by marcospri** [comment]
Done, the API doesn't return now empty titled assignments.

We have https://github.com/hypothesis/lms/issues/6485 to investigate why we have those assignments in the first place.
