### ISSUE TITLE
Allow sharing dashboard links between staff members

### ISSUE THREAD

**Issue by marcospri** [hypothesis/lms#6509]
Follow up to:

- https://github.com/hypothesis/lms/issues/6480

We currently scope staff dashboards to an organisation only, both for authorization purposes and to limit the amount of data we show at once (all courses/assignments/students of one org vs the full DB).

We achieve that by:

1. - Launching the dashboards with a public_id query parameter
2. - Including that value in JSConfig
3. - Forwarding the public_id to API calls to fetch data

This works as intended but the URL parameter included in 1/ disappears after any action in the app. 3/ still happens because we keep the value in the JSConfig.

This becomes a problem when sharing URLs as the public_id the view is scoped to doesn't "travel" with the URL and the new window results in and empty dashboard every if still authorized as a staff member.

### Potential solution

We could keep the public_id parameter in the URL at all times for staff members (ie if present in the JSConfig).

**Comment by acelaya** [comment]
If it's important to keep the ID in the URL at all times, I think we should reconsider supporting URLs like `/dashboard/org/{org_id}` again.

That doesn't mean we have to scope cookies to that (unless we have to), or reverting completely. We could still support `/dashboard`-prefixed URLs for LMS admins and instructors, and `/dashboard/org/{org_id}`-prefixed URLs for staff users.

The rest of the logic, where we forward the id in every API call, should be the same.

I also need to check if the client-side router we use supports this.

**Comment by marcospri** [comment]
Fixed by https://github.com/hypothesis/lms/pull/6518
