### ISSUE TITLE
Filtering inconsistency if instructor and student participated in course, but in different assignments

### ISSUE THREAD

**Issue by robertknight** [hypothesis/lms#6516]
I have a scenario locally where I have opened a dashboard as an instructor and have selected a course in the filter list, but am not seeing a student who is in that course. If I clear the course filter I do see the student in the students list, if I then select the student from that list, I *do* see the course:

Courses where student is active:

<img width="641" alt="Courses where student is active" src="https://github.com/user-attachments/assets/7d44c496-0658-4a4a-9b2d-56c5423157c4">

Students in course:

<img width="684" alt="Students active in course" src="https://github.com/user-attachments/assets/10f3bd90-7f65-42dc-b81e-068364b460a2">

Upon investigation, the issue is that although the current instructor and the student have both launched assignments in the course as an instructor and student respectively, they have launched _different_ assignments. The filtering of the lists based on the current instructor works differently for the course and student list. For the student list, it only returns entries if the instructor was seen as an instructor in the _same assignment_ where the student was a student.

I think the expected behavior here is that:

- The two lists should be filtered in the same way
- The determination of whether a user is a student and/or instructor should be done on a per-course, rather than per-assignment level. This matches the granularity at which user roles are assigned in eg. Canvas. This would align with a future where we are able to fetch the current roster for a course from the LMS.

[Slack thread](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1722518977520789).

**Comment by marcospri** [comment]
https://github.com/hypothesis/lms/pull/6533 fixed this
