### ISSUE TITLE
Propagate relevant filters when navigating between dashboard views (FE)

### ISSUE THREAD

**Issue by acelaya** [hypothesis/lms#6539]
Currently, all active filters are lost if, for example, you are in the "All courses" view and click one course form the list.

The same happens when going from there to one assignment, and something similar happens when navigating levels up using the breadcrumbs.

The behavior should be the next:

* All courses:
    * When a course is clicked, selected students and assignments should be propagated.
* Course view:
    * When an assignment is clicked, selected students should be propagated.
    * When "All courses" is clicked in the breadcrumbs, selected assignments and students should be propagated.
* Assignment view:
    * When "All courses" is clicked in the breadcrumbs, selected students should be propagated.
    * When "parent" course is clicked in the breadcrumb, selected students should be propagated.

**Comment by robertknight** [comment]
See the note in https://github.com/hypothesis/lms/pull/6540#issuecomment-2285750118 about a complication of doing this: not all of the selected filters may be available in the new view.
