### ISSUE TITLE
SpeedGrader 1/n: Submit an LTI launch URL to Canvas for grading, when a student launches an assignment

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#655]
Belongs to epic: [MVP Canvas SpeedGrader Support](https://github.com/hypothesis/lms/issues/658)

To get Canvas to launch Hypothesis in the SpeedGrader, Hypothesis first needs to submit a grading URL to Canvas. For any given assignment and student, if Hypothesis has submitted a grading URL for that assignment and student, then Canvas will use that grading URL to launch Hypothesis when an instructor views that assignment and student in SpeedGrader.

When a student launches our assignment our frontend code should make a call to [our grading submission proxy API](https://github.com/hypothesis/lms/issues/846) to submit a grading URL for this student.

The HTTP request should be asynchronous and the UX should not block waiting for the response to this request.

The frontend needs to handle error responses and timeouts etc with this request.

## Notes

* We don't need to add a <kbd>Submit</kbd> button for the user to click or anything like that. We'll just silently and automatically submit the grading URL as soon as the student opens the assignmentv every time they open it. Later, when Canvas launches us in SpeedGrader, we'll use the grading URL's query params to retrieve all of this students annotations and replies for this assignment so far.

## Error handling

We should avoid a situation where the grading submission request has failed somehow, so no submission has been made to Canvas, but Hypothesis is still showing the document and allowing the student to annotate etc. The student may do the assignment, unaware that nothing has been submitted for their teacher to see in SpeedGrader.

One possible solution when this happens would be to take over the entire frame with an error message informing the student that launching the assignment has failed, and asking them to reload the page. Mockup:

![Screenshot from 2019-07-23 11-43-50](https://user-images.githubusercontent.com/22498/61706131-3c6f9000-ad3f-11e9-80ee-b1fc3cf33fed.png)

**Comment by robertknight** [comment]
> The HTTP request should be asynchronous and the UX should not block waiting for the response to this request.

In other words, you are thinking that the frontend app can do this part _after_ it has started to load the assignment in the Via iframe?

**Comment by robertknight** [comment]
> One possible solution when this happens would be to take over the entire frame with an error message informing the student that launching the assignment has failed, and asking them to reload the page. 

If the LMS's frontend app renders the iframe, it could optimistically create the iframe and let it start loading, and then replace the iframe with an error display if the call ends up failing.

**Comment by robertknight** [comment]
Implemented in https://github.com/hypothesis/lms/pull/867
