### ISSUE TITLE
Lengthen cookie and token lifetimes to extend URL access to the LMS dashboards

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#6550]
Slack convo: https://hypothes-is.slack.com/archives/C2C2U40LW/p1723217042499239

We anticipate user behavior of the LMS dashboard to include weekly check-ins by instructors. We'd like those instructors to be able to access (and refresh their access) to the dash by opening the URL on a weekly basis.

Per the Slack conversation, we need to extend both the cookie and API token lifetimes.

**Comment by marcospri** [comment]
Changed to one week expiration, for the cookie session, the token contained in the cookie and token used to make API calls.
