### ISSUE TITLE
Make sure ISO dates include the timezone

### ISSUE THREAD

**Issue by acelaya** [hypothesis/lms#6748]
We have noticed some dates returned by the dashboard backed do not include a way to identify the fact that they are in UTC timezone, after serializing them in ISO format.

This causes the browser to think they are in the system timezone when formatting them, which is specially problematic for relative dates ("20 minutes ago", "2 hours ago", etc).

This is because date objects are not timezone-aware at the time `datetime.isoformat()` is called.

A similar issue was solved [here](https://github.com/hypothesis/lms/pull/6740/files#diff-c24e3684130237e3154d637b46b305a385ea2b78576d5e6ccf921c09727db58bR65), but we may need to find a more systematic way to solve this.

When the ISO date doesn't include the timezone, it looks like `2024-10-02T13:51:22.979735`, but a suffix like `Z` or `+00:00` would be needed.

**Comment by marcospri** [comment]
After merging https://github.com/hypothesis/lms/pull/6750 we need now to:

- First use the new renderer in all dashboard endpoints to solve the most pressing issue
- Replace one by one all usage of the json renderer by this one, making sure we don't introduce unintended consequences. 
- Replace the name of the new renderer by just `json` effectivily making it the default.

**Comment by acelaya** [comment]
> After merging [#6750](https://github.com/hypothesis/lms/pull/6750) we need now to:
> 
> * First use the new renderer in all dashboard endpoints to solve the most pressing issue
> * Replace one by one all usage of the json renderer by this one, making sure we don't introduce unintended consequences.
> * Replace the name of the new renderer by just `json` effectivily making it the default.

I think this issue can be closed once the first point has been done. For the rest we can create separated LMS generic issues.
