### ISSUE TITLE
Authorize dialog looks off-center when launching Canvas file assignment

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#768]
When launching a Canvas file assignment and we need to ask the user for authorization (e.g. we don't have an access token for this user yet) our dialog looks off center. I think it _is_ actually centered in the iframe, but the positioning of the iframe within Canvas's page and the fact that you can't see the boundaries of the iframe make our dialog look off-center:

![Screenshot from 2019-07-05 16-53-25](https://user-images.githubusercontent.com/22498/60733833-ed0b2080-9f45-11e9-80ff-d00b42240b09.png)

I think this could be solved by putting the dialog in a small white box within a darker background:

![Screenshot from 2019-07-05 16-55-04](https://user-images.githubusercontent.com/22498/60733855-feecc380-9f45-11e9-89fc-bda854408194.png)

But unlike in that mockup the design should match other dialogs elsewhere in our app, for example:

![Screenshot from 2019-07-05 16-58-40](https://user-images.githubusercontent.com/22498/60733934-35c2d980-9f46-11e9-93eb-2598c89e51a0.png)

Although note that there should not be any <kbd>x</kbd> or <kbd>Cancel</kbd> buttons when launching an assignment.

**Comment by seanh** [comment]
This also clearly delineates where Canvas ends and the Hypothesis app begins, and makes it clear that the message comes from Hypothesis not Canvas. With the current approach on master it's not clear that it isn't a message from Canvas itself. (Adding the Hypothesis logo somewhere might also help with this but is beyond the scope of this issue.)

**Comment by hmstepanek** [comment]
I just had trouble finding the 'try again' on this page after keys have been revoked and the user attempts to re-launch the assignment. It wasn't at all obvious to me that the try again was connected with the error message. Definitely defining the border would help. 
![image](https://user-images.githubusercontent.com/30059933/62151185-9a0e5a00-b2b4-11e9-9c02-a671b0807420.png)
