### ISSUE TITLE
Different pages of the app use different styles

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#780]
There are two entirely different sets of HTML layouts and CSS styles used within the LMS app.

## First style

The first style is used on the https://lms.hypothes.is/welcome page:

![Screenshot from 2019-07-09 15-53-52](https://user-images.githubusercontent.com/22498/60899078-c577c900-a261-11e9-98f8-7e231e980084.png)

![Screenshot from 2019-07-09 16-03-04](https://user-images.githubusercontent.com/22498/60899841-120fd400-a263-11e9-807f-18c71b6a11a6.png)

This style is also used on the error page if a student tries to launch an assignment that the teacher hasn't configured yet:

![Screenshot from 2019-07-09 15-54-55](https://user-images.githubusercontent.com/22498/60899173-ee985980-a261-11e9-86f5-3787d9e6d96b.png)

And it might be used in some other places as well.

## Second style

The second style is used for the various dialogs and error dialogs when creating assignments with the `new_oauth` feature flag on. Examples:

![Screenshot from 2019-07-09 16-00-24](https://user-images.githubusercontent.com/22498/60899649-b5acb480-a262-11e9-876f-e72c25c8c85b.png)
![Screenshot from 2019-07-09 15-59-20](https://user-images.githubusercontent.com/22498/60899650-b5acb480-a262-11e9-9aac-93bee8ffb60a.png)
![Screenshot from 2019-07-09 15-58-50](https://user-images.githubusercontent.com/22498/60899651-b5acb480-a262-11e9-930b-ba3c73328f1f.png)
![Screenshot from 2019-07-09 15-58-12](https://user-images.githubusercontent.com/22498/60899652-b6454b00-a262-11e9-8670-94458ec94c9d.png)
![Screenshot from 2019-07-09 15-57-56](https://user-images.githubusercontent.com/22498/60899653-b6454b00-a262-11e9-84fe-dc022e921b3b.png)
![Screenshot from 2019-07-09 15-57-43](https://user-images.githubusercontent.com/22498/60899655-b6454b00-a262-11e9-8f89-cd1f3affa671.png)

## Solution

More work has been done on the second style, which includes modal dialogs with action and cancel buttons, lists/tables of files, error dialogs, etc. So we should probably change the pages that use the first style to use the second, rather than vice-versa.

But we may need to introduce an optional larger font to the second style to make it able to handle some of these pages. See https://github.com/hypothesis/lms/issues/675

**Comment by robertknight** [comment]
> More work has been done on the second style, which includes modal dialogs with action and cancel buttons, lists/tables of files, error dialogs, etc.

The second set of styles was also adapted from h and the client in an effort to be more consistent with those projects.

**Comment by robertknight** [comment]
The configuration form mentioned with the first style was removed from the public-facing app. Most of the error dialogs that a user can encounter now use the Preact-based frontend too. I think the only remaining exception are the 404 dialogs if LTI authorization fails. On that basis I'm going to close this.
