### ISSUE TITLE
Feature flags cookie settings need to be tri-state not two-state

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#790]
# Context

The way the feature flags mechanism works is that it consults a list of feature flag "providers" in this order:

- Config file
- Environment variable
- Cookie
- Query string

When queried about a particular feature flag each provider can return `None`, `True` or `False`, and the last provider to return either `True` or `False` is used. `None` means that this particular flag is not set either on or off in this provider, so other providers should be consulted.

So for example the feature flags cookie can return `True` to enable a feature that is either unset (`None`) or actively disabled (`False`) in the config file and environment variables, because the
cookie is consulted after the config file and environment variables.

# Problem

Unfortunately the way that the feature flags cookie provider is currently implemented it always returns either `True` or `False`, never `None`, for every feature flag listed in the `FEATURE_FLAGS_ALLOWED_IN_COOKIE` setting. Its UI is based on on/off checkboxes:

![Screenshot from 2019-07-10 11-45-26](https://user-images.githubusercontent.com/22498/60963274-412c5100-a308-11e9-804a-ca67776e740a.png)

This means that for all flags in `FEATURE_FLAGS_ALLOWED_IN_COOKIE` the cookie provider always returns `True` or `False` and always overrides config file and environment variables, even if the user has never visited the feature flags cookie page to turn a flag on or off. If a feature is in `FEATURE_FLAGS_ALLOWED_IN_COOKIE` then it cannot be enabled for all users in the config file or environment.

# Solution

The feature flags cookie page needs to be changed to allow three values for each cookie instead of two:

1. Unset (`None`) (the default, meaning the cookie neither sets or unsets this flag and the setting from the environment or config file should be used)
2. On (`True`)
3. Off (`False`)

The UI will need to be changed to use a three-way radio button or switch rather than a checkbox. Perhaps something like this:

![Peek 2019-07-10 11-35](https://user-images.githubusercontent.com/22498/60963204-13470c80-a308-11e9-8328-5d6f096b0670.gif)

**Comment by seanh** [comment]
Another way I've seen this done is to have a separate "Use default" toggle (not shown in this example but this also provides a space to display what the current default value is):

![Peek 2019-07-10 11-54](https://user-images.githubusercontent.com/22498/60963762-97e65a80-a309-11e9-8cf5-6d118f40a254.gif)

**Comment by seanh** [comment]
An alternative solution would be to stick to binary on/off checkboxes but have unchecked mean _not set / fall back to default_ rather than meaning off. This might be simpler but it doesn't allow you to use the cookie to turn _off_ a feature that is _on_ by default.

**Comment by jon-betts** [comment]
I've also seen this as a check box which cycles through `[ ] -> [tick] -> [x] -> [ ]`
