### ISSUE TITLE
KeyError: 'resource_link_id'

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#795]
The `unconfigured_basic_lti_launch()` view crashes if the request has no `"resource_link_id"` param, when it [tries to access that param directly from `request.params`](https://github.com/hypothesis/lms/blob/master/lms/views/basic_lti_launch.py#L166).

```
KeyError: 'resource_link_id'
(8 additional frame(s) were not displayed)
...
  File "pyramid/viewderivers.py", line 436, in rendered_view
    result = view(context, request)
  File "newrelic/hooks/framework_pyramid.py", line 140, in _wrapper
    return wrapper(context, request)
  File "pyramid/viewderivers.py", line 132, in _class_view
    response = getattr(inst, attr)()
  File "lms/views/basic_lti_launch.py", line 166, in unconfigured_basic_lti_launch
    "resource_link_id": self.request.params["resource_link_id"],
  File "webob/multidict.py", line 344, in __getitem__
    raise KeyError(key)
```

https://sentry.io/organizations/hypothesis/issues/1106379969/?referrer=github_plugin

## Validation schemas in the LMS app

This is happening because the view has no validation schema, and rather than adding logic into the view code itself the solution should be to add a validation schema to the view.

The pattern in the LMS app is that we [define validation schemas in `lms/validation/`](https://github.com/hypothesis/lms/tree/master/lms/validation) (these schemas are written using [marshmallow](https://marshmallow.readthedocs.io/en/2.x-line/) and [webargs](https://webargs.readthedocs.io/en/latest/)) and then apply them to views. For example [the `configure_module_item()` view](https://github.com/hypothesis/lms/blob/d80c8bb311a6b6da04b3e17e2ea21663e36c9177/lms/views/basic_lti_launch.py#L202-L231) has a schema applied like this:

```python
@view_config(
    ...,
    schema=ConfigureModuleItemSchema,
)
def configure_module_item(self):
    ...
```

This means that:

1. The schema will be run against the request first, before the view is called
2. If schema validation fails the view will never be called
3. If validation succeeds then the parsed and validated params will be available as `request.parsed_params` when the view is called
4. The view can just use `request.parsed_params` blindly, assuming that all params will be valid and all required params will be present, and doesn't need to contain any logic or tests about missing or invalid params
5. Views should not access `request.params` directly, they should use `request.parsed_params`

## Other notes

* `"resource_link_id"` isn't the only key that  `unconfigured_basic_lti_launch()` accesses directly on `request.params`. A quick look at the code shows that the view is also accessing `"tool_consumer_instance_guid"` and `"context_id"`

* It also accesses `self.context.lms_url`, which calls [`LTILaunchResource.lms_url()`](https://github.com/hypothesis/lms/blob/d80c8bb311a6b6da04b3e17e2ea21663e36c9177/lms/resources/_lti_launch.py#L249-L281), which accesses either `"custom_canvas_api_domain"` or `"oauth_consumer_key"`

* A good technique might be to identify the minimum parameters that  `unconfigured_basic_lti_launch()` requires by sending it a request with no parameters and then adding parameters one by one until it succeeds.

* A lot (maybe all) of the parameters that  `unconfigured_basic_lti_launch()` needs are also needed by other LTI launch views in the same file and in [`content_item_selection.py`](https://github.com/hypothesis/lms/blob/master/lms/views/content_item_selection.py). It's likely that these views can all share the same schema. Some of them may need to use schemas that are subclasses of a shared schema, for example to add additional view-specific fields.

* There is already a [`LaunchParamsSchema`](https://github.com/hypothesis/lms/blob/master/lms/validation/_launch_params.py) which should probably form the basis of this.

  But note that `LaunchParamsSchema` is [used by our authentication policies to verify the request's OAuth 1 signature and authenticate the LTI user](https://github.com/hypothesis/lms/blob/68a1ab45a149f2c26a84df3413621e3f22995178/lms/authentication/_helpers.py#L38). If we just add more required params to `LaunchParamsSchema`, such as `"resource_link_id"`, that will cause _authentication_ to fail and send back an authentication error. That's not what we want. If the request is validly signed and contains those params needed for authentication then we want authentication to succeed and then, if a param like `"resource_link_id"` is missing, view validation should fail and send back a validation error.

  To achieve this, if new required params like `"resource_link_id"` have been added to `LaunchParamsSchema`, then [the code that uses `LaunchParamsSchema` to authenticate the user](https://github.com/hypothesis/lms/blob/d80c8bb311a6b6da04b3e17e2ea21663e36c9177/lms/validation/_launch_params.py#L45-L57) will have to _subset_ the schema to apply only those params needed for authentication and ignore the rest of the schema's params. This can be done using a marshmallow feature called [partial loading](https://marshmallow.readthedocs.io/en/3.0/quickstart.html#partial-loading).

**Comment by seanh** [comment]
One thing to keep in mind here: the fact that our app crashed is what notified us that someone at blackboard.stevenson.edu was trying and failing to use our app. If we fix the crash then it'll no longer be reported to Sentry, and the user will be shown a helpful error message that might help them to correct the problem themselves, but we might not have noticed that a potential user was s trying and failing to use our app. So we should make sure that these failed attempts are still logged somewhere we can track them. Probably Papertrail.

**Comment by marcospri** [comment]
I reckon this has changed quite a lot since 2019 to still be relevant. We'll keep an eye on sentry to see if it's a problem again.
