### ISSUE TITLE
Provide Canvas-like file picker for Blackboard

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#802]
From https://github.com/hypothesis/lms/issues/257. 

The Canvas file picker provides a key piece of functionality for the workflow of teachers using the LMS app. They are able to use PDFs housed in the course itself where they typically store course materials, rather than hosting them somewhere else like Google Drive or the web. Providing a similar option for users of the app in other LMSs would bring parity to those institutions.

We should prioritize the job for each based on some combination of market share and current usage of Hypothesis, likely starting with Blackboard and then Moodle.

**Comment by mkdir-washington-edu** [comment]
When working on this, perhaps we can investigate if students can upload files teachers can then access for assignment creation.
https://hypothesis.zendesk.com/agent/tickets/7350
(Also, in ZD search `blackboard-files`).

**Comment by klemay** [comment]
> When working on this, perhaps we can investigate if students can upload files teachers can then access for assignment creation.

This isn't something we have control over - Blackboard would need to add a feature allowing students to upload files to the [Course Files tool](https://help.blackboard.com/Learn/Instructor/Course_Content/Course_Files). If Blackboard added this feature, those files would be available through our future file picker tool. (I know you know this, but am chiming in for others who may come across this issue)

**Comment by mkdir-washington-edu** [comment]
In the previously linked ticket, the user says:

> Blackboard does have a document repository for each user. However – we have only turned that on for faculty and staff...

Which to me implies that they can turn the file repository on for students, but choose not to.

**Comment by klemay** [comment]
See: https://github.com/hypothesis/lms/issues/1319

**Comment by mkdir-washington-edu** [comment]
Requests:
https://hypothesis.zendesk.com/agent/tickets/11175

**Comment by seanh** [comment]
Closing in favour of https://github.com/hypothesis/lms/issues/1324
