### ISSUE TITLE
Provide Canvas-like file picker for Moodle

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#803]
From https://github.com/hypothesis/lms/issues/257. 

The Canvas file picker provides a key piece of functionality for the workflow of teachers using the LMS app. They are able to use PDFs housed in the course itself where they typically store course materials, rather than hosting them somewhere else like Google Drive or the web. Providing a similar option for users of the app in other LMSs would bring parity to those institutions.

We should prioritize the job for each based on some combination of market share and current usage of Hypothesis, likely starting with Blackboard and then Moodle.

Here's a resource on Moodle file APIs that might be useful when we get to this issue:

https://docs.moodle.org/dev/File_API_internals

**Comment by mkdir-washington-edu** [comment]
https://hypothesis.zendesk.com/agent/tickets/6021

> ...it would be great to be informed if the LMS works with a moodle file picker. In German educational institutions we are not allowed any storage that is connected to Google, Facebook etc. because of data security so it is crucial to us to have a file picker that works on Moodle or Illias.

**Comment by dwhly** [comment]
This will be useful for ETH Zurich too, which is on Moodle and will likely have the same requirements.

**Comment by upats** [comment]
Plus one for this enhancement! I'm at a Moodle school that does not supply Google accounts for faculty. This would eliminate a significant barrier for us.

**Comment by marcospri** [comment]
Handled on https://github.com/hypothesis/product-backlog/issues/1473
