### ISSUE TITLE
Add support for Canvas API scoped developer keys

### ISSUE THREAD

**Issue by seanh** [hypothesis/lms#806]
## Problem

When creating or editing a developer key in Canvas there's an **Enforce Scopes** option that you can use to limit what "scopes" a client using this developer key has access to (basically which API endpoints the client can use).

Our app currently doesn't declare to Canvas what scopes it needs, which means that Canvas treats us as a client that requires every scope, so either an unscoped dev key or one with every scope checked will work. But if the user creates a dev key with any scopes unchecked then, when we open the Canvas authorization popup window, the user sees this error message from Canvas:

![error-when-scope-is-wrong](https://user-images.githubusercontent.com/22498/61131925-3f9e8c80-a4b2-11e9-87d0-a2cafa9d218a.png)

## We don't want to encourage scoped dev keys

We absolutely **do not want to encourage** people to use scoped developer keys with our app. Using a scoped developer key means that users might deny us a scope that, while we don't need it now, we might need that additional scope in the future, and when we add code that uses that scope our users will be faced with the unfriendly error message from Canvas shown above.

Canvas does not provide any way for our app to request additional scopes, it just runs users into the above error message.

Until we've found a way to implement good error handling for when the developer key is missing a scope that we need, we shouldn't encourage scoped developer keys.

Having said that, some users insist on using scoped keys, so our app should support them.

## Creating a scoped developer key

To create a scoped developer key you need to:

1. Login to Canvas as an admin
2. Go to **Admin -> University of Hypothesis -> Developer keys**
3. Either **create a new developer key** or **edit an existing one**
4. Turn on the **Enforce Scopes** option
5. Check the scopes that you want to allow
6. Click **Save**

Any application installs that use this developer key will now be scoped.

![Peek 2019-07-12 14-29](https://user-images.githubusercontent.com/22498/61131730-e20a4000-a4b1-11e9-889e-ce770be5762a.gif)

## Scopes our app needs

Our app currently uses two Canvas API endpoints:

1. [List a course's files](https://canvas.instructure.com/doc/api/files.html#method.files.api_index), which requires the `"url:GET|/api/v1/courses/:course_id/files"` scope
2. [Get a download URL for a file](https://canvas.instructure.com/doc/api/files.html#method.files.public_url), requires the `"url:GET|/api/v1/files/:id/public_url"`

## How to add scopes support to our app

When we need to get a Canvas API access token our app shows the user an <kbd>Authorize</kbd> button that, when clicked, opens a popup window whose URL is `https://lms.hypothes.is/api/canvas/authorize`. Our view that responds to that URL then redirects the popup window (with an HTTP 302 response) to Canvas's OAuth 2 login page.

As you can see from [the docs for Canvas's OAuth 2 login page](https://canvas.instructure.com/doc/api/file.oauth_endpoints.html#get-login-oauth2-auth) it supports an optional query parameter `scope`.

Our app currently does not send the `scope` param. To add scoped dev keys support we need to add the `scope` param to the Canvas OAuth 2 login URL that we redirect to, with the two scopes that we need as its value.

It needs to be **a single query parameter called `scope`**, not multiple separate query params, and the param's value needs to be a **space-separated list of scopes**:

```
?scope=url:GET|/api/v1/courses/:course_id/files url:GET|/api/v1/files/:id/public_url
```

## Code design

The view that redirects the popup window to Canvas's OAuth 2 login page is [`views/api/canvas/authorize.py::CanvasAPIAuthorizeViews.authorize()`](https://github.com/hypothesis/lms/blob/8703a9e78ea8e76320ac791aa7c77b0d6dc09fbd/lms/views/api/canvas/authorize.py#L18-L39). That view generates the URL and returns a redirect to that URL. This is where the `scope` param needs to be added.

### What about users who already have access tokens?

What will happen if our database already has an access token for a user, given to us before we added support for scoped developer keys, and then we ship scoped keys support, an admin edits the dev keys and scopes it, and then that user tries to use our app with their preexisting access token in our DB?

We should check that this works fine.

### Are there any other scopes we should ask for?

We should look over [the list of Canvas API endpoints](https://canvas.instructure.com/doc/api/all_resources.html) and see if there's any that we think we might need for upcoming features that we should tell admins to grant now so that they don't have problems later when we ship new feature.

### Error handling for when our developer key lacks the scopes we need?

If a scoped developer key lacks one of the scopes that we request then, when we redirect the popup window to Canvas's OAuth 2 login page with the `?scope=...` param, Canvas responds to the browser with an unfriendly error page (see screenshot above).

This error page is sent directly from Canvas to the user's browser and neither our frontend or backend code can detect it.

But we might be able to do something like have our server send a test `GET` request to this URL, with the `scope` param, and test the response, before redirecting the user's browser to it. If the response is the error page then we could direct our user's to a friendly error page telling them that an admin needs to add these scopes to our key, instead of directing the browser to Canvas's failing login page.

**Comment by robertknight** [comment]
> Canvas responds to the browser with an unfriendly error page (see screenshot above).

According to [the OAuth 2 spec](https://tools.ietf.org/html/rfc6749#section-4.1.2.1) authorization errors other than an invalid redirect URI are supposed to be handled by redirecting but with error details in the query params.

If Canvas isn't doing this, we should discuss this issue with them upstream. In the interim some workaround might be required.

**Comment by robertknight** [comment]
The Canvas OAuth 2 [authorize endpoint implementation](https://github.com/instructure/canvas-lms/blob/master/app/controllers/oauth2_provider_controller.rb) indeed appears to raise an error rather than redirecting the user in the event of an invalid scope.

**Comment by robertknight** [comment]
The issue of handling adding new required scopes for Canvas as we add new LMS features in future is a hazard. Naively adding new scopes to the authorization code request could break existing installs that were configured with only the minimal scopes that the app needed at the time. We could potentially have per-install feature flags that affect what scopes are used. This would enable us to launch a new feature without breaking existing app installations.

**Comment by seanh** [comment]
I think we could have our JavaScript code `GET` the login page with our scopes and test the result. We can look at the response status or, if the status's differ, we'd have to parse the response HTML. This can be done in pure JS or via one of our proxy APIs if necessary. And if the page is an error we display a "Your admin needs to give us these scopes" page, or if the page is not an error we redirect to it.

But even if we did that, it's not a great solution, since it means our app is refusing to work until an admin fixes the key.

We could re-try the login page with fewer and fewer scopes but I think that's getting silly.

**Comment by seanh** [comment]
We actually have no way of knowing what scopes the developer key for a given application instance currently has. We know what scopes we asked for the last time we asked for an authorization code using that dev key. That tells us that the key had at least those scopes at that time. But the key's scopes could have been modified in Canvas since.

**Comment by seanh** [comment]
> Naively adding new scopes to the authorization code request could break existing installs that were configured with only the minimal scopes that the app needed at the time.

Right now all Hypothesis developer keys in the wild, all the ones that are working anyway, are unscoped, because our app doesn't support scopes yet. So right now, the _first_ time we start asking for a list of scopes, we have an opportunity to ask for a few extra ones that we don't use yet but think we might in the future.

Once we have scoped developer keys in the wild then adding any further scopes to the list that we request is going to be problematic and might require us to invent some kind of awkward workaround.

**Comment by hmstepanek** [comment]
I spoke with @robertknight about how we might address changing scopes in the future yesterday. The conclusion we came to was while an additional feature may require additional scopes in the future we don't need to handle this at the moment.  There are a couple things that would most likely need to happen if we need to add additional scopes at some point to existing keys:

1. We would need to track the scope with the key in our app as now there would be existing keys with old scopes and new keys with new scopes. This means most likely all existing keys would get assigned the old scope and new keys going forward would get assigned a scope at the time of entry.
2. We would need to somehow indicate to users/admins that in order to use the new feature they need to use the new scopes.
3. The application would need to know when the new feature that depends on the new scope is available to the user/when it's not.

With the first addition of scopes, all existing keys have the permissions they need and so we should be able to go ahead and add the scopes (I need to test this to make sure) without tracking existing scopes on existing keys. It also remains to be seen whether we will need to handle adding additional scopes in the future-that is speculation. If we do need to do this however, we could do this at that time by following the above steps. There isn't anything we need to do now to enable this in the future as I see it.

It would probably behoove us to add a comment into the code explaining that if the scope does need to be changed in the future, the scope can't just simply be changed for all keys or it will break existing keys.

**Comment by hmstepanek** [comment]
Additional endpoints:
- I think there was some mention on slack about this last week but, if we want to ever have support for multiple groups such as teacher+student or a class broken up into sub-groups I think we would need access to [these endpoints] (https://canvas.instructure.com/doc/api/all_resources.html#method.group_categories.users) which require additional scopes such as `url:GET|/api/v1/group_categories/:group_category_id/users`.
- If we ever wanted to be able to filter a student's annotations not just by the user but also by the datetime the annotation was made (if the assignment has a deadline for example) then we might need access to [assignments](https://canvas.instructure.com/doc/api/all_resources.html#method.assignments_api.index) in which case these endpoints would also require scopes such as `url:GET|/api/v1/courses/:course_id/assignments/:id`. I should point out it's not super clear to me whether 'dates' which is returned as part of the assignment information actually includes the assignment due date here although I think it does. I believe we have avoided calling out assignments directly in favor of files so this is not something I anticipate we'll need in the short term.

**Comment by hmstepanek** [comment]
Developer Key Permissions currently required:
![image](https://user-images.githubusercontent.com/30059933/62153071-ae545600-b2b8-11e9-8ece-2346b56cecc9.png)

![image](https://user-images.githubusercontent.com/30059933/62153103-bc09db80-b2b8-11e9-8a24-a1153d5bb852.png)

**Comment by hmstepanek** [comment]
Wanted to make sure everything related to this issue get's tracked/linked here in some form:

I have [notified](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1564596987091700) @jeremydean and @klemay of the release of the addition of scopes. They will be updating our Wiki post and notifying the customers for whom this is relevant. 

I'm working on opening an issue against canvas for the incorrect oauth2 error response on invalid scopes (I'll link it here when it's been opened). After that, I think we can close this issue.

**Comment by hmstepanek** [comment]
https://github.com/instructure/canvas-lms/issues/1483
