### ISSUE TITLE
Set up hosted Blackboard instance

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#849]
We've been approved to add [Blackboard Learn for REST and LTI Developers](https://aws.amazon.com/marketplace/pp/B077T4SX2B#pdp-pricing) to our AWS subscriptions. 

Next steps:
- [x] add the subscription to our account 
- [x] set up our Blackboard instance
- [x] grant access to H team members
- [x] install a proper https certificate

**Comment by dmfine** [comment]
It Lives at https://blackboard.svc.hypothes.is I'm going to install a proper SSL certificate before closing this ticket

**Comment by klemay** [comment]
Awesome. I'll grant access to team members today & check that box when it's done!

**Comment by klemay** [comment]
Access has been granted to team members!

**Comment by dmfine** [comment]
SSL cert installed. The URL is https://blackboard.hypothes.is now
