### ISSUE TITLE
Integrate with `GET /users/{user}` endpoint and generate settings object for grading mode

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/lms#879]
Depends on https://github.com/hypothesis/h/issues/5671
Part of https://github.com/hypothesis/lms/issues/658

This issue is for the work needed to "wire up" the LMS app to the new user-focus mode in the client by availing of the to-be-built `GET /users/{user}` API endpoint and generating an appropriate `settings` object for client config.

- [x] Integrate new focus mode into SpeedGrader
- [x] Complete [follow-up work](https://github.com/hypothesis/lms/issues/879#issuecomment-521565364)

**Comment by robertknight** [comment]
This was implemented in https://github.com/hypothesis/lms/pull/888. There are some follow-up refactorings to do. See the comments on that PR for details:

- [ ] Rename `HypothesisAPIService` to `HAPIRequests`
- [ ] Make `LTILaunchResource` use the `HUser` class
- [ ] Review PR for any other follow-up work that needs to happen
