### ISSUE TITLE
Run IMS Certification Tests for LTI 1.1

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#932]
Part of https://github.com/hypothesis/lms/issues/705, not blocked by https://github.com/hypothesis/lms/issues/876 but it may not make sense to run the tests until #876 is implemented. 

The IMS website is so confusing/complicated that they created a video for members to teach them how to navigate it... I'll try to point y'all to where you need to go. 

To run the test:

1. Go to https://www.imsglobal.org/user and log in (credentials in Passpack)
2. Go to https://www.imsglobal.org/lti-v1-certification-suite (if you skip step 1 you will be redirected to the login page and likely won't be able to navigate your way here - so please log in first!)
3. Click on "Process for Tool Providers"
![screenshot-www imsglobal org-2019 08 22-15-32-55](https://user-images.githubusercontent.com/12087705/63544092-43322400-c4f2-11e9-9eef-214e6b513b97.png)
4. You'll be directed to a "wizard" that will walk you through the testing process

The testing process is divided into the following stages:
- Overview
- Configuration (basically you'll create a key and secret to use with their testing suite)
- Tests
- Results (this will tell us if we need to make any changes to get certified)
- Submit (and then we wait for IMS to get back to us)

The certification tests are divided into the following sections:

- Tool registration (5 tests)
- Invalid Launch Requests (9 tests)
- Valid Launch Requests (4 tests)
- Types of User Roles (8 tests)
- Levels of User Information (7 tests)
- Deep Linking Message (2 tests)
- Outcomes 1.0 service (4 tests)
- Tool Consumer Profile (1 test)
- Tool Settings service (4 tests)
- Names and Roles Service (4 tests)

**Comment by seanh** [comment]
I've run the test suite:

## Summary

If I'm reading the certification suite tool correctly, there appear to be several separate certifications here. Some of the certifications apply to our app, and some don't. And there are different tests for each certification:

* 1.0
* 1.1
* 1.2 (doesn't apply to us)
* Deep Linking (doesn't seem to apply to us / I don't understand the tests, see below for details)
* Outcomes-1 (doesn't apply to us until we have released grading for all LMS's, but looks as if it _may_ be required for 1.1 certification, unclear, see below for details)
* Tool Settings (service) (doesn't apply to us)
* Names and Roles (service) (doesn't apply to us)

In order to pass all the tests that the test suite claims "apply to" LTI 1.0 and 1.1 we need to:

1. Fix 7 easy-looking "Invalid Launch Requests" test fails
2. Fix 2 easy-looking "Levels of User Information" test fails (which look like they may both be the same one bug)
3. For LTI 1.1 certification (but not 1.0), if I'm reading the tool correctly, I think we  need to finish grading and release it **for all LMS's** and then run one "Outcomes 1.0 service" test and pass it. It seems odd to me that grading support would be required for LTI 1.1 certification. Surely grading isn't applicable to all apps? But the test suite says it "Applies to: 1.1, Outcomes-1 [required]".

I've created separate issues for each thing we'd need to fix and given them all the [LTI 1.1 Certification](https://github.com/hypothesis/lms/labels/LTI%201.1%20Certification) label.

## Details

* **Section 1: Invalid Launch Requests**: We fail many of the tests in this section either because our app crashes or (mostly) because our app displays its own error page when it's supposed to "return to tool consumer with error message". Even though we have 7 failures in this section, I think they will all be quite quick and easy to fix.

* **Section 2: Valid Launch Requests**: We passed all these.

* **Section 3: Type of User Roles**: I think we can fairly claim to pass all these but I did create one issue about how we could improve our app's behavior with anonymous users: https://github.com/hypothesis/lms/issues/1123

* **Section 4: Levels of User Information**: We failed two tests. Both appear to be [the same issue](https://github.com/hypothesis/lms/issues/1124). I think this would be an easy fix.

* **Section 5: Deep Linking Message**: There are two tests in this section. I don't think our app passes either of them. I don't understand what the tests are supposed to be testing, or what our app is supposed to do here. Apparently our app is supposed to "return an LTI link" in the first test, and in the second test we're supposed to "return the data parameter". I would have to read up on the spec to get a better understanding of what's required to fix our app here. I don't think we need to pass this section for LTI 1.0 & 1.1 certification. I think it's only needed for a separate Deep Linking certification.

* **Section 6: Outcomes 1.0 service**: Our app does not make use of the outcomes service **until we have released grading for all LMS's**. Once we've released that we could run these tests. Until then they're inapplicable to our app. But the first test in this section is **required** for 1.1 certification, if I'm reading the tool correctly.

* **Section 7: Tool Consumer Profile**: Not applicable to our app. I don't think we need to pass this for LTI 1.1 certification, it's only for LTI 1.2 certification.

** **Section 8: Tool Settings service**: Not applicable to our app. I don't think we need to pass this for LTI 1.1 certification, it's only for `Tool Settings [service]` certification.

* **Section 9:  Names and Roles Service**:  Not applicable to our app. I don't think we need to pass this for LTI 1.1 certification, it's only for `Names and Roles [service]` certification.

## Full results

<table class="table table-bordered table-sm table-hover table-responsive mt-3">
    <thead class="thead-inverse">
      <tr>
        <th>Test</th><th>Applies to</th><th>Status</th><th>&nbsp;</th>
      </tr>
    </thead>
    <tbody>
          <tr>
    <td><strong><a href="#" onclick="return gotoTest(2, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section comprises tests using invalid launch requests.</p>">1&nbsp; Invalid Launch Requests</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="Return user to the Tool Consumer with an error message">1.1&nbsp; No resource_link_id provided</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="A user-friendly error message">1.2&nbsp; No resource_link_id or return URL provided</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="A user-friendly error message">1.3&nbsp; Invalid OAuth consumer key</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="A user-friendly error message">1.4&nbsp; Invalid OAuth signature</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 5);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="Return user to the Tool Consumer with an error message">1.5&nbsp; Invalid LTI version</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 6);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="Return user to the Tool Consumer with an error message">1.6&nbsp; Wrong LTI version</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 7);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="Return user to the Tool Consumer with an error message">1.7&nbsp; Missing LTI version</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 8);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="Return user to the Tool Consumer with an error message">1.8&nbsp; Invalid LTI message type</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(2, 9);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="Return user to the Tool Consumer with an error message">1.9&nbsp; Missing LTI message type</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(3, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section performs a variety of launch requests for instructors and students.  Each launch changes one or more of the following parameters:</p><div style=&quot;text-align: left;&quot;><ul>
  <li>context</li>
  <li>resource link</li>
  <li>user</li>
  <li>user role</li>
  <li>user information</li>
</ul>
</div>">2&nbsp; Valid Launch Requests</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(3, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have whatever privileges are appropriate to an instructor; e.g. able to edit">2.1&nbsp; Launch as an instructor</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(3, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="The user should have whatever privileges are appropriate to an instructor (e.g. able to edit) but within a new instance of the tool in the same course (context) as the previous test">2.2&nbsp; Launch as an instructor from a different resource link</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(3, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given whatever privileges are appropriate to a student">2.3&nbsp; Launch as a learner</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(3, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given whatever privileges are appropriate to a student">2.4&nbsp; Launch as a learner from a different resource link</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(4, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section performs a variety of launch requests with different values for the roles parameter</p>">3&nbsp; Types of User Roles</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have whatever privileges are appropriate to an instructor; e.g. able to edit">3.1&nbsp; Launch as an instructor using a fully-qualified URN</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have whatever privileges are appropriate to an instructor; e.g. able to edit">3.2&nbsp; Launch as an instructor with a list of roles</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have whatever privileges are appropriate to an instructor; e.g. able to edit">3.3&nbsp; Launch as an instructor using a full URN role in a list</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given whatever privileges are appropriate to a student">3.4&nbsp; Launch as a learner using a full URN role in a list</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 5);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given whatever privileges are appropriate to a user with no role, which could be that they are denied access">3.5&nbsp; Launch as a user with no context role</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 6);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given privileges appropriate to a user with no context role, which could be that they are denied access">3.6&nbsp; Launch as a user with an institution role but no context role</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 7);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given privileges appropriate to a user with no context role, which could be that they are denied access">3.7&nbsp; Launch as a user with an institution role which has no corresponding context role</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(4, 8);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should be given privileges appropriate to a user with no context role, which could be that they are denied access">3.8&nbsp; Launch as a user with an unrecognised role</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(5, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section performs a series of tests that each provides less and less information until they get to the minimum possible.  Each test uses the same resource_link_id (in a new context) but a different value for the user_id parameter.  These tests only apply to LTI 1</p>">4&nbsp; Levels of User Information</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="The tool should handle the lack of name information in a user-friendly manner, which could be that they are denied access">4.1&nbsp; Launch as a learner with email but no name</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="The tool should detect the user's name">4.2&nbsp; Launch as a learner with given/family but no full name</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="The tool should detect the user's name">4.3&nbsp; Launch as a learner with a full name but no given or family names</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have privileges appropriate to an instructor (e.g. able to edit) unless personal information is required in which case access should be denied and the user returned to the Tool Consumer with a user-friendly message">4.4&nbsp; Launch as an instructor with no personal information</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 5);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have privileges appropriate to an instructor (e.g. able to edit) unless context and/or personal information is required in which case access should be denied and the user returned to the Tool Consumer with a user-friendly message">4.5&nbsp; Launch as an instructor with no context or personal information apart from the context ID</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 6);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should have privileges appropriate to an instructor (e.g. able to edit) unless context and/or personal information is required in which case access should be denied and the user returned to the Tool Consumer with a user-friendly message">4.6&nbsp; Launch as Instructor with no context information</a></td><td>1.0, 1.1, 1.2</td><td class="table-danger text-center">Failed</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(5, 7);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="The user should provide whatever access is relevant to a guest or respond with an error message">4.7&nbsp; Launch with only resource_link_id</a></td><td>1.0, 1.1, 1.2</td><td class="table-success text-center">Passed</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(6, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>Tests for different types of Deep Linking item; at least LTI links must be supported.</p>">5&nbsp; Deep Linking Message</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(6, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="User should select/configure and return an LTI link.">5.1&nbsp; Create an LTI link</a></td><td>Deep Linking</td><td class="table-info text-center">&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(6, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="This test checks the data parameter is correctly returned for each Deep Linking workflow">5.2&nbsp; Supports data parameter</a></td><td>Deep Linking</td><td class="table-info text-center">&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(7, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section contains tests of the Outcomes 1.0 service.  The tests only require outcomes to be sent to the Tool Consumer for users with Learner roles.  However, it is not necessary for the grades to be returned via the Learner sessions; it is possible to use Instructor launches as an alternative mechanism for returning grades for students.</p>
<p>These tests require outcomes to be generated in at least 2 different contexts, for at least 2 different resource links within the same context, and for at least 2 different users for the same resource link.</p>">6&nbsp; Outcomes 1.0 service</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(7, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="All replaceResult requests for outcomes should be properly formed.">6.1&nbsp; replaceResult requests</a></td><td>1.1, Outcomes-1</td><td class="table-info text-center">&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(7, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="If the tool sends any readResult requests for outcomes they should be properly formed.">6.2&nbsp; readResult requests</a></td><td>1.1, Outcomes-1</td><td class="table-warning text-center">OK</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(7, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="If the tool sends any deleteResult requests for outcomes they should be properly formed.">6.3&nbsp; deleteResult requests</a></td><td>1.1, Outcomes-1</td><td class="table-warning text-center">OK</td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(7, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="This test is passed when all the required outcome values listed below have been processed <br /><b>You must have an outcome value set in more than one context, and in at least one context there must be<br/> outcomes for more than one resource link and more than one user</b>">6.4&nbsp; Processing of Gradebook entries</a></td><td>1.1, Outcomes-1</td><td class="table-info text-center">&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(8, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section verifies proper support for the Tool Consumer Profile.</p>">7&nbsp; Tool Consumer Profile</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(8, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="This test checks the request made for the Tool Consumer Profile to ensure it is valid">7.1&nbsp; Valid request</a></td><td>1.2</td><td class="table-info text-center">&nbsp;</td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(10, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section confirms the results of any requests to the Tool Settings service.  It is not necessary for Tool Provider to use the Settings service but, if it does, any requests should be properly formed.</p>">8&nbsp; Tool Settings service</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(10, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="GET requests for settings should be properly formed">8.1&nbsp; GET requests</a></td><td>Tool Settings</td><td class="table-active text-center"><input type="checkbox" id="service_10_3" onclick="toggleService(this);"></td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(10, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="PUT requests for settings should be properly formed">8.2&nbsp; PUT requests</a></td><td>Tool Settings</td><td class="table-active text-center"><input type="checkbox" id="service_10_4" onclick="toggleService(this);"></td><td>&nbsp;</td>
    </tr>
    <tr>
    <td><strong><a href="#" onclick="return gotoTest(11, 0);" data-toggle="tooltip" data-placement="top" data-html="true" data-container="body" data-delay="500" title="" data-original-title="<p>This section contains tests of the Names and Roles service.  The tests only require a valid request to be sent to the endpoint offered for this service.</p>">9&nbsp; Names and Roles Service</a></strong></td><td colspan="3">&nbsp;</td>
  </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(11, 1);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="GET requests for Names and Roles containers should be properly formed">9.1&nbsp; GET Names and Roles container requests</a></td><td>Names and Roles</td><td class="table-active text-center"><input type="checkbox" id="service_11_1" onclick="toggleService(this);"></td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(11, 2);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="GET requests for Names and Roles containers should be properly formed">9.2&nbsp; GET Names and Roles container requests for a resource link</a></td><td>Names and Roles</td><td class="table-active text-center"><input type="checkbox" id="service_11_2" onclick="toggleService(this);"></td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(11, 3);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="GET requests for Names and Roles containers should be properly formed">9.3&nbsp; Include 'role' query parameter</a></td><td>Names and Roles</td><td class="table-active text-center"><input type="checkbox" id="service_11_3" onclick="toggleService(this);"></td><td>&nbsp;</td>
    </tr>
    <tr>
      <td><a href="#" onclick="return gotoTest(11, 4);" data-toggle="tooltip" data-placement="right" data-container="body" data-delay="500" data-html="true" title="" data-original-title="GET requests for Names and Roles containers should be properly formed">9.4&nbsp; Include 'limit' query parameter</a></td><td>Names and Roles</td><td class="table-active text-center"><input type="checkbox" id="service_11_4" onclick="toggleService(this);"></td><td>&nbsp;</td>
    </tr>
    </tbody>
  </table>
