### ISSUE TITLE
Run IMS Certification Tests for  LTI Advantage Complete

### ISSUE THREAD

**Issue by klemay** [hypothesis/lms#933]
Once we got the basic "LTI Adventage" certification using LTI1.3 Core and Assignment and Grade Services 2.0 a next step would be to get the full certification "LTI Advantage Complete" with the two remaining APIs.

---
http://www.imsproject.org/spec/lti/v1p3/cert/

Required specs:

 - [x] LTI 1.3 Core
 - [ ] Deep Linking 2.0
 - [x] Assignment and Grade Services 2.0
 - [ ] Names and Role Provisioning Services 2.0

**Comment by marcospri** [comment]
https://docs.google.com/document/d/1FQ06m55RDmHH0mnEpSN9ArqBformfdc4fH2tWy9PgQY/

**Comment by marcospri** [comment]
We've run the certification now but we are waiting for the results. We'll open specific issues if it comes up negative for some reason.
