### ISSUE TITLE
Canvas instructor app not able to access Hypothesis assignments

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/lms#973]
Using the Canvas instructor app from the Google Play store, when trying to access Hypothesis assignments (with or without SpeedGrader) I get the following pages:

First page:
**Authorize Hypothesis**
Hypothesis needs your authorization to launch this assignment.

After clicking the "Authorize" button, I get:
while(1):{"error":"invalid_client","error_description":"unknown client"}

**Comment by mkdir-washington-edu** [comment]
In a second pass at this, I was **not** able to replicate the problem, trying every combination of websites and PDFs, in and out of SpeedGrader.

I'm now on my home network, which is significantly faster than the crowded coffee shop I was in this morning when I experienced the bug.

**Comment by klemay** [comment]
I downloaded the Canvas Student and Canvas Teacher apps; both worked just fine for me. Going to close this issue, but we'll have it on record & can reopen if others run into this in the future.
